(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.scatola = function() {
	this.initialize(img.scatola);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,175,124);


(lib.valigetta = function() {
	this.initialize(img.valigetta);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,219,117);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.unabuonaidea = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E7CEB5").s().p("AgWAXQgKgJAAgOQAAgMAKgKQAJgJANAAQANAAAKAJQAKAKAAAMQAAAOgKAJQgKAJgNAAQgNAAgJgJg");
	this.shape.setTransform(197.125,12.95);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E7CEB5").s().p("AB0CnQgHAAgDgHIgehBIiYAAIgdBBQgDAHgIAAIgdAAQgGAAgCgEQgCgEACgEICQk8QADgFAFAAIAEAAQAFAAADAFICPE8QACAEgCAEQgDAEgFAAgAA7A3Ig6iAIgCAAIg5CAIB1AAg");
	this.shape_1.setTransform(176.5194,-0.925);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E7CEB5").s().p("AhdClQgJAAAAgKIAAk2QAAgIAJgBIC7AAQAJABAAAIIAAAbQAAAJgJgBIiTAAIAABgIB8AAQAJAAAAAJIAAAaQAAAJgJAAIh8AAIAABlICTAAQAJAAAAAIIAAAaQAAAKgJAAg");
	this.shape_2.setTransform(148.45,-0.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#E7CEB5").s().p("AiDClQgJAAAAgKIAAk2QAAgIAJgBIBsAAQBDAAAwAxQAxAwAABDQAABEgxAxQgwAvhDABgAhcB4IA+AAQAzgBAighQAigiAAg0QAAg0gighQgigigzAAIg+AAg");
	this.shape_3.setTransform(117.625,-0.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#E7CEB5").s().p("AgPClQgIAAgBgKIAAk2QABgIAIgBIAfAAQAIABABAIIAAE2QgBAKgIAAg");
	this.shape_4.setTransform(92.3,-0.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E7CEB5").s().p("AB0CnQgHAAgDgHIgehBIiYAAIgdBBQgDAHgIAAIgdAAQgGAAgCgEQgCgEACgEICQk8QADgFAFAAIAEAAQAFAAADAFICPE8QACAEgCAEQgDAEgFAAgAA7A3Ig6iAIgCAAIg5CAIB1AAg");
	this.shape_5.setTransform(60.0694,-0.925);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E7CEB5").s().p("ABzCpIjLjxIAAAAIAADjQAAAKgJAAIgeAAQgJAAAAgKIAAk6QAAgJAJAAIAMAAIDLDqIABAAIAAjdQAAgIAJgBIAeAAQAJABAAAIIAAE8QAAAIgJAAg");
	this.shape_6.setTransform(26.625,-0.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E7CEB5").s().p("Ah3B4QgxgxAAhGQAAhGAxgyQAxgxBGAAQBGAAAyAxQAxAyAABGQAABGgxAxQgxAxhHAAQhGAAgxgxgAhVhVQgkAkAAAyQAAAyAkAjQAkAkAxAAQAyAAAkgkQAkgjAAgyQAAgygkgkQgkgkgyAAQgxAAgkAkg");
	this.shape_7.setTransform(-10.35,-0.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#E7CEB5").s().p("AhbCCQgkgkAAg3IAAjEQAAgJAJAAIAfAAQAJAAAAAJIAADBQAAAkAWAYQAVAYAjAAQAjAAAWgYQAVgXAAgkIAAjCQAAgJAJAAIAgAAQAJAAAAAJIAADEQAAA3glAkQgkAlg3AAQg2AAglglg");
	this.shape_8.setTransform(-45.975,-0.475);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#E7CEB5").s().p("AhlClQgJAAAAgKIAAk2QAAgIAJgBIBoAAQAqAAAdAZQAbAZAAAlQAAAvgxAcQA7AYAAA0QAAAngdAaQgdAagtAAgAg/B5IBHAAQAVABAPgPQAPgPAAgWQAAgVgSgOQgQgOgYAAIhAAAgAg+gVIA+AAQAXAAANgOQANgOAAgWQAAgVgNgOQgNgOgXAAIg+AAg");
	this.shape_9.setTransform(-76.15,-0.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#E7CEB5").s().p("AB0CnQgHAAgDgHIgehBIiYAAIgdBBQgDAHgIAAIgdAAQgGAAgCgEQgCgEACgEICQk8QADgFAFAAIAEAAQAFAAADAFICPE8QACAEgCAEQgDAEgFAAgAA7A3Ig6iAIgCAAIg5CAIB1AAg");
	this.shape_10.setTransform(-117.0306,-0.925);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#E7CEB5").s().p("ABzCpIjLjxIAAAAIAADjQAAAKgJAAIgeAAQgJAAAAgKIAAk6QAAgJAJAAIAMAAIDLDqIABAAIAAjdQAAgIAJgBIAeAAQAJABAAAIIAAE8QAAAIgJAAg");
	this.shape_11.setTransform(-150.475,-0.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#E7CEB5").s().p("AhbCCQgkgkAAg3IAAjEQAAgJAJAAIAfAAQAJAAAAAJIAADBQAAAkAWAYQAVAYAjAAQAjAAAWgYQAVgXAAgkIAAjCQAAgJAJAAIAgAAQAJAAAAAJIAADEQAAA3glAkQgkAlg3AAQg2AAglglg");
	this.shape_12.setTransform(-185.275,-0.475);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.unabuonaidea, new cjs.Rectangle(-204.3,-35.6,408.6,71.2), null);


(lib.tx3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E7CEB5").s().p("AgoApQgQgRAAgYQAAgXAQgRQARgRAXAAQAYAAARARQARARAAAXQAAAYgRARQgRAQgYAAQgXAAgRgQgAgcgcQgMAMAAAQQAAASAMAMQALALARAAQARAAAMgLQANgMAAgSQAAgQgNgMQgMgNgRAAQgQAAgMANg");
	this.shape.setTransform(0.15,-0.25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.tx3, new cjs.Rectangle(-8.4,-13.4,16.8,26.9), null);


(lib.tx2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E7CEB5").s().p("AAnA5QAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIgKgWIgzAAIgKAWQAAABgBAAQAAABAAAAQgBAAAAABQgBAAgBAAIgKAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgCIAwhrQABgBAAAAQAAAAABAAQAAgBABAAQAAAAAAAAIABAAQAAAAABAAQAAAAABABQAAAAAAAAQAAAAAAABIAxBrIAAACQAAABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAgAAUATIgTgrIgBAAIgTArIAnAAg");
	this.shape.setTransform(78.85,-0.325);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E7CEB5").s().p("AgfApQgRgRAAgYQAAgXARgRQARgRAXAAQAVAAASAPQAAABABABQAAAAAAABQAAAAAAABQgBAAAAABIgHAHQgBABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQgNgLgPAAQgQABgMALQgLANAAAQQAAARALAMQAMAMAQAAQAOAAAOgLQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAIAHAIQAAAAABABQAAAAAAABQAAAAAAABQgBAAAAABQgQAPgXAAQgXAAgRgQg");
	this.shape_1.setTransform(68.3875,-0.25);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E7CEB5").s().p("AgEA4QgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhpQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAJAAQABAAABAAQAAAAAAABQABAAAAABQAAAAAAABIAABpQAAABAAAAQAAABgBAAQAAABAAAAQgBAAgBAAg");
	this.shape_2.setTransform(60.675,-0.25);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#E7CEB5").s().p("AgBA5QAAAAAAAAQgBAAAAAAQgBAAAAAAQAAgBAAAAIgdhIIgBAAIgMBGQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIgLAAQAAAAgBAAQgBAAAAgBQAAAAgBgBQAAgBAAAAIAUhrQAAgBAAAAQABgBAAAAQABAAAAAAQAAgBABAAIACAAQABAAAAABQABAAAAAAQABAAAAAAQAAABAAAAIAhBRIAAAAIAhhRQABAAAAgBQAAAAABAAQAAAAAAAAQABgBAAAAIADAAQABAAAAABQABAAAAAAQAAAAABABQAAAAAAABIATBrQABADgEAAIgKAAQgBAAAAAAQAAAAgBgBQAAAAgBAAQAAgBAAAAIgMhGIAAAAIgdBIQAAAAAAABQgBAAAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_3.setTransform(51.6569,-0.25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#E7CEB5").s().p("AAoA5QgBAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIgKgWIg0AAIgJAWQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAIgLAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAAAgBgBIAAgCIAyhrQAAgBAAAAQAAAAABAAQAAgBABAAQAAAAAAAAIABAAQABAAAAAAQAAAAABABQAAAAAAAAQAAAAABABIAxBrIAAACQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAAAAAgAAUATIgUgrIAAAAIgTArIAnAAg");
	this.shape_4.setTransform(39.75,-0.325);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E7CEB5").s().p("AAYA4QgBAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAAAIgVgrIgXAAIAAApQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAIgLAAQAAAAgBAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAhpQAAgBAAAAQABgBAAAAQAAgBABAAQABAAAAAAIArAAQAOAAAKAKQALAKAAAOQAAALgHAJQgGAIgLAEIAWAoIAAAEQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAgAgXAAIAcAAQAHgBAGgFQAGgGAAgJQAAgHgGgGQgGgFgHgBIgcAAg");
	this.shape_5.setTransform(29.775,-0.25);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E7CEB5").s().p("AgfA4QgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAhpQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIA/AAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAIgxAAIAAAhIApAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIAAAHQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgpAAIAAAjIAxAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_6.setTransform(20.1,-0.25);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E7CEB5").s().p("AgfApQgRgRAAgYQAAgXARgRQARgRAXAAQAVAAASAPQAAABABABQAAAAAAABQAAAAAAABQgBAAAAABIgHAHQgBABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQgNgLgPAAQgQABgMALQgLANAAAQQAAARALAMQAMAMAQAAQAOAAAOgLQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAIAHAIQAAAAABABQAAAAAAABQAAAAAAABQgBAAAAABQgQAPgXAAQgXAAgRgQg");
	this.shape_7.setTransform(9.8875,-0.25);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#E7CEB5").s().p("AgEA4QgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhpQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAJAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAABpQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_8.setTransform(-1.025,-0.25);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#E7CEB5").s().p("AgsA4QgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAhpQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAkAAQAXAAAQAQQARARAAAWQAAAXgRAQQgQARgXAAgAgfApIAWAAQAQAAALgMQAMgLAAgSQAAgRgMgMQgLgLgQAAIgWAAg");
	this.shape_9.setTransform(-8.6,-0.25);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#E7CEB5").s().p("AgoApQgRgRAAgYQAAgXARgRQARgRAXAAQAYAAAQARQARARABAXQgBAYgRARQgQAQgYAAQgXAAgRgQgAgdgcQgMAMABAQQgBASAMAMQANALAQAAQARAAAMgLQAMgMAAgSQAAgQgMgMQgMgNgRAAQgQAAgNANg");
	this.shape_10.setTransform(-24.3,-0.25);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#E7CEB5").s().p("AAnA5IhEhRIgBAAIAABNQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAIgJAAQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhqQAAgBAAgBQAAAAAAgBQABAAAAAAQABgBABAAIADAAIBFBPIAAhKQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIALAAQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABIAABrQAAABgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_11.setTransform(-36.7,-0.25);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#E7CEB5").s().p("AgEA4QgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhpQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAJAAQABAAABAAQAAAAAAABQABAAAAABQAAAAAAABIAABpQAAABAAAAQAAABgBAAQAAABAAAAQgBAAgBAAg");
	this.shape_12.setTransform(-44.975,-0.25);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#E7CEB5").s().p("AgEA4QgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhdIgaAAQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAgJQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIBDAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAJQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAIgaAAIAABdQAAABAAAAQAAABgBAAQAAABAAAAQgBAAgBAAg");
	this.shape_13.setTransform(-50.925,-0.25);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#E7CEB5").s().p("AgEA4QgBAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAhdIgaAAQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAgJQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIBDAAQABAAABAAQAAAAAAABQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAABgBAAQAAABAAAAQgBAAgBAAIgaAAIAABdQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_14.setTransform(-58.425,-0.25);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#E7CEB5").s().p("AAnA5QAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIgKgWIgzAAIgKAWQAAABgBAAQAAABAAAAQgBAAAAABQgBAAgBAAIgKAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgCIAwhrQABgBAAAAQAAAAABAAQAAgBABAAQAAAAAAAAIABAAQAAAAABAAQAAAAABABQAAAAAAAAQAAAAAAABIAyBrIAAACQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAgAAUATIgTgrIgBAAIgTArIAnAAg");
	this.shape_15.setTransform(-67.3,-0.325);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#E7CEB5").s().p("AggApQgQgRAAgYQAAgXAQgRQARgRAXAAQAWAAARAPQABABAAABQAAAAAAABQAAAAAAABQAAAAgBABIgHAHQAAABgBAAQAAAAgBAAQAAAAgBAAQgBAAAAgBQgNgLgOAAQgQABgMALQgLANAAAQQAAARALAMQAMAMAQAAQAKABAOgGIAAgSIgQAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAgJQAAgBAAgBQAAAAABgBQAAAAABAAQAAAAABAAIAdAAQABAAABAAQAAAAAAAAQABABAAAAQAAABAAABIAAAnQAAAAAAAAQAAABAAAAQAAAAgBAAQAAABAAAAQgRAKgXAAQgXAAgRgQg");
	this.shape_16.setTransform(-78.175,-0.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.tx2, new cjs.Rectangle(-85.9,-13.4,171.8,26.9), null);


(lib.tx1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E7CEB5").s().p("AgGAYIgDgCQAAgBAAAAQAAAAAAgBQAAAAAAgBQABgBAAAAQALgKAAgLIgEABQgEAAgDgDQgDgEAAgEQAAgFADgDQADgDAFAAQAFAAADADQAEAFABAJQgBAKgFAKQgFAHgEAEIgCABIgCgBg");
	this.shape.setTransform(51.2,5.825);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E7CEB5").s().p("AgEA4QgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhpQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAJAAQABAAABAAQAAAAAAABQABAAAAABQAAAAAAABIAABpQAAABAAAAQAAABgBAAQAAABAAAAQgBAAgBAAg");
	this.shape_1.setTransform(47.175,-0.25);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E7CEB5").s().p("AAAA5QgBAAAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBIgxhrIAAgCQABgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIALAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAAAIAjBOIAAAAIAkhOQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAMAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAQAAAAAAABQAAAAgBAAIgxBrQAAABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAg");
	this.shape_2.setTransform(39.8125,-0.175);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#E7CEB5").s().p("AAnA5QAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIgKgWIgzAAIgKAWQAAABgBAAQAAABAAAAQgBAAAAABQgBAAgBAAIgKAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAAAgBgBIAAgCIAxhrQABgBAAAAQAAAAABAAQAAgBABAAQAAAAAAAAIABAAQAAAAABAAQAAAAABABQAAAAAAAAQAAAAAAABIAyBrIAAACQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAgAAUATIgTgrIgBAAIgTArIAnAAg");
	this.shape_3.setTransform(29.55,-0.325);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#E7CEB5").s().p("AgEA4QgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhpQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAJAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAABpQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_4.setTransform(22.175,-0.25);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E7CEB5").s().p("AAhA4QgBAAgBAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAgvIg5AAIAAAvQAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBAAIgKAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAhpQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAKAAQABAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAtIA5AAIAAgtQAAgBAAAAQAAgBABAAQAAgBABAAQABAAABAAIAKAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAABpQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_5.setTransform(14,-0.25);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E7CEB5").s().p("AgfApQgRgRAAgYQAAgXARgRQARgRAXAAQAVAAASAPQAAABABABQAAAAAAABQAAAAAAABQgBAAAAABIgHAHQgBABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQgNgLgPAAQgQABgMALQgLANAAAQQAAARALAMQAMAMAQAAQAOAAAOgLQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAIAHAIQAAAAABABQAAAAAAABQAAAAAAABQgBAAAAABQgQAPgXAAQgXAAgRgQg");
	this.shape_6.setTransform(2.6875,-0.25);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E7CEB5").s().p("AAnA5QAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIgKgWIgzAAIgKAWQAAABgBAAQAAABAAAAQgBAAAAABQgBAAgBAAIgKAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgCIAwhrQABgBAAAAQAAAAABAAQAAgBABAAQAAAAAAAAIABAAQAAAAABAAQAAAAABABQAAAAAAAAQAAAAAAABIAyBrIAAACQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAgAAUATIgTgrIgBAAIgTArIAnAAg");
	this.shape_7.setTransform(-7.9,-0.325);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#E7CEB5").s().p("AgEA4QgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhdIgaAAQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAgJQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIBDAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAJQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAIgaAAIAABdQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_8.setTransform(-16.775,-0.25);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#E7CEB5").s().p("AAYA4QgBAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAAAIgVgrIgXAAIAAApQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAIgLAAQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAhpQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAIArAAQAOAAAKAKQALAKAAAOQAAALgHAJQgGAIgLAEIAWAoIAAAEQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAgAgXAAIAcAAQAHgBAGgFQAGgGAAgJQAAgHgGgGQgGgFgHgBIgcAAg");
	this.shape_9.setTransform(-25.375,-0.25);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#E7CEB5").s().p("AgoApQgRgRAAgYQAAgXARgRQARgRAXAAQAYAAAQARQARARAAAXQAAAYgRARQgQAQgYAAQgXAAgRgQgAgdgcQgLAMgBAQQABASALAMQAMALARAAQARAAAMgLQAMgMAAgSQAAgQgMgMQgMgNgRAAQgQAAgNANg");
	this.shape_10.setTransform(-37.15,-0.25);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#E7CEB5").s().p("AgiA4QgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAhpQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAIAkAAQAPAAAKALQALAKAAAOQAAAPgLAKQgKALgPgBIgWAAIAAAmQAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAgAgUAAIAVAAQAIAAAGgGQAGgFAAgJQAAgIgGgFQgGgGgIAAIgVAAg");
	this.shape_11.setTransform(-47.525,-0.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.tx1, new cjs.Rectangle(-54.9,-13.4,109.9,26.9), null);


(lib.txfine = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E7CEB5").s().p("AguBIQgLgUADgfQgJAAgGgFQgHgEABgFQABgDAFAAQAIAJAIABQAIgnAYggQAYgjAbAAQAQAAgDAVQgEAUgVAcQgVAbgZALQgKBDAoAAQAYAAAUgfQARgZAKgnIADAAQgKArgTAdQgXAhgcABQgegBgMgUgAgDg3QgRAdgHAkQAXgKATgbQARgYADgUQACgPgJAAQgPABgQAeg");
	this.shape.setTransform(136.8433,-15.65);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E7CEB5").s().p("Ag8A5QAGgnARg6QgzgEAGgkQAEgbAcgOIAEgCQABAAAAABQAAAAAAAAQAAAAAAABQAAAAAAABIgCAFQgUAJgDATQgEAaApAGQATg9AKgZQAEgLAIAAQAHAAAGAGQgKAQgWBMQA6gBAdgaIAFgBQABAAAAAAQABAAAAAAQABAAAAAAQAAABAAAAIgCADQgNAQgcAKQgbAKgdADQgTBBgIAuQgMBGAVAAQATAAATgmQAOgcAGgZIAEAAQgKAkgOAbQgUAngZAAQgkAAAQhgg");
	this.shape_1.setTransform(128.0684,-22.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E7CEB5").s().p("AAABNQgIgNAEgVQgYAugZAAQgrAAAKg/QAHgoAZgkQAagmAbAAQAQAAADAYIAIgBQAQAAgCAOQgUBCgFAfQgFAgARAAQATAAAUgmQANgcAGgYIAEAAQgJAjgOAaQgVAogZAAQgOAAgGgMgAglgtQgQAhgGAmQgJA0ASAAQAdAAAVg9IALgvQAHg0gTAAQgSAAgSAlg");
	this.shape_2.setTransform(112.547,-15.675);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#E7CEB5").s().p("Ag7CQQgEghAJg1IABgLIgPALIgDgEIAUgNQAMg/AXg4QAYg+AbgZQAPgPAKAAQAQAAgFAeQgGAhgYAuQgcA0giAkQgKAkgGAjQgNBRAXAAQATABATgnQAOgbAGgaIAEAAQgKAlgOAaQgUAngZAAQgUABgFglgAAtieQgfAughB5QAegjAYgxQAXgsAFgdQADgXgIAAQgFAAgIANg");
	this.shape_3.setTransform(100.286,-24.85);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#E7CEB5").s().p("AhBBHQgKgVAFggQAHgnAYggQAZgjAegFQABAAAAABQABAAAAAAQABABAAAAQAAABAAAAQgXAJgSAeQgOAagGAhQgFAfAFAVQAGAWAPABQAVAAAOgYQANgUAFgfQADgPgBgOIgSADQgRAAgIgLQgHgJACgNQACgLAHgHQAHgIALAAQAbAAADAuQAOgGANgLIADACQgRAOgNAHIgCAdQgGAkgRAZQgSAcgZABQgcgBgMgWgAgGg2QgBAKAGAIQAHAJAPAAIANgCQgDgngWAAQgMAAgDAOg");
	this.shape_4.setTransform(85.8305,-15.85);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E7CEB5").s().p("Ag7BGQgMgWAGgiQAHgoAXggQAbgjAbAAQAOAAAFAMQAGAKgDAPQgCAPgIAKQgJAMgLAAQgLAAACgNQADgVAbgBIABgIQAEgXgSgBQgSAAgSAfQgRAdgGAjQgFAgAIAUQAIAXAYAAQAXAAAUgfQARgaAJgmIAEAAQgKArgTAdQgXAhgdAAQghAAgNgYg");
	this.shape_5.setTransform(71.911,-15.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E7CEB5").s().p("AhBBHQgKgVAFggQAHgnAYggQAZgjAegFQABAAAAABQABAAAAAAQABABAAAAQAAABAAAAQgXAJgSAeQgOAagGAhQgFAfAFAVQAGAWAPABQAVAAAOgYQANgUAFgfQADgPgBgOIgSADQgRAAgIgLQgHgJACgNQACgLAHgHQAHgIALAAQAbAAADAuQAOgGANgLIADACQgRAOgNAHIgCAdQgGAkgRAZQgSAcgZABQgcgBgMgWgAgGg2QgBAKAGAIQAHAJAPAAIANgCQgDgngWAAQgMAAgDAOg");
	this.shape_6.setTransform(57.2805,-15.85);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E7CEB5").s().p("AABCpQgHgNADgVQACgOANgoQAOgpACgOQADgRgIAAQgOAAgVAiQgWAfgQAoIgJA7IgJACQgNgBABgMIAXiAQgSAQgNAIIgCgEQAQgIASgRQAgioApgfQAMgKAJAAQASAAgEAeQgGAegWAtQgZAwggAkIgKA1IgFAjQAwhgAfgBQAbABgFAhQgEAXgPApQgPAogCALQgEAUAPAAQAUABATgnQAOgbAGgaIAEAAQgJAlgOAaQgWAngZAAQgNABgHgMgAAVihQgaAkgbB9QAdgiAVgsQAUgrAFgbQAEgWgMgBQgHAAgHAKg");
	this.shape_7.setTransform(41.45,-24.85);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#E7CEB5").s().p("AjTE2QglhiAZiZQAei1BdiOQBmibB1AAQA+AAAfA2QAhA5gQBnQgOBTgrA8QguBAg6AAQguAAgSgmQgPgiAJg5QALhGAng6QAqg/AxgHQABAAAAAAQABAAABABQAAAAAAAAQABABgBABIgCAEQgqALgjA7QggA0gLBAQgIAzAMAhQAPAkAlAAQAsAAAjg2QAigyALhIQARhlgdg6QgZg1g2AAQhjAAhUCPQhOCBgcCtQgZCXAeBiQAgBuBcABQBAAAA3hFQAzg/ANhNQAMhHgUgoQgQgigkgBQgqABgpAsQguAygWBOQgLABACgMQAXhSA1gwQAtgtAxABQAsgBAXAlQAZAogLBGQgOBXg9BHQhCBNhPAAQhvAAgrhtg");
	this.shape_8.setTransform(14.4,-17.45);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#E7CEB5").s().p("AD3CpQAZiVA1irQA0ijAmg6Qg4A4hZCrQhICNhKCtQgDAcgFAfQgJA3gUBBQgZBRgTAAQgQAAAGglQAFgdAihZIACgLQAHgqAEhwIAHjQQg8CnhPCDQiIDdiHAAQhXAAglhMQgihEARhmQAViCBLhOQBChFBKAAQA7AAAgAvQAjAygPBWQgBAHgEAAQgBAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQANhPgegxQgdgwg6AAQhIAAg4BPQgzBHgRBlQgQBiAbBDQAeBKBIAAQByAAB7i6QBeiPBIjKQAHhiALhFQAKg6ATgqQARglAMAAQAOAAgJA0QgNBSgiBsIACCmQACBlgGBFQBTi/BPiTQBgiyA0ggQALgHAOAAQAGAAgBAEQgkBAg+DCQhFDXgZCZQghDNA/AAQAXAAAdg3QAeg6AOhNIAFAAQgQBbgjA8QghA2gfAAQhXAAAskMgAAqGKQgBAKACAAQAFAAAQhSQgTA1gDATgACXmFIgLApQgJA5gCBDQAchbAJg7QAJgxgHAAQgGAAgLAig");
	this.shape_9.setTransform(-108.0534,-17.925);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#E7CEB5").s().p("AhiDKQgGgOAEgaQAIgvAggsQAWgfAqgmIAHg5QgSAVgSAAQgoAAAPheQAIgrAKgcQAFgPARAAIAKACIgNAoQgLAmgFAeQgKA+AVAAQAQAAAOgTIAKhCQAGgmANgaQALgYAJAAQAKAAgFAhQgHAsgVApIgHBLQAdgbAKgPQAUgdAJgnIAEAAQgKApgTAdQgKAQgiAgIgFAgQgPBfgiA4QgcAvgbAAQgNAAgGgOgAhYCeQgIAvAUAAQASAAAUgoQAYgvANhSIAEgaQhPBNgMBHgAAsiJIgEAcQAPgkAGggQAEgbgDAAQgHAAgLBDg");
	this.shape_10.setTransform(-28.2714,-3.675);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#E7CEB5").s().p("AgiBDQAEgUAUgvQATgvACgMQABgJgFAAIgkADQgBASgDAUQgJA0gWAiIgFgCQAXghAJg0QADgRAAgUQgYgBADgUQADgOALAAQAKAAABAbIAEAAQAMAAAbgEQAWAAgEAbQgCAKgSApQgRAsgDASQgEAXAOAAQAOAAAVgbQAUgZAKgsIAEAAQgLAvgTAaQgcAmgaAAQgZAAAFgig");
	this.shape_11.setTransform(-40.625,-15.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#E7CEB5").s().p("AgiBDQAEgUAUgvQATgvACgMQABgJgFAAIgkADQgBASgDAUQgJA0gWAiIgFgCQAXghAJg0QADgRAAgUQgYgBADgUQADgOALAAQAKAAABAbIAEAAQAMAAAbgEQAWAAgEAbQgCAKgSApQgRAsgDASQgEAXAOAAQAOAAAVgbQAUgZAKgsIAEAAQgLAvgTAaQgcAmgaAAQgZAAAFgig");
	this.shape_12.setTransform(-52.975,-15.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#E7CEB5").s().p("AguBIQgLgUADgfQgJAAgGgFQgHgEABgFQABgDAFAAQAIAJAIABQAIgnAYggQAYgjAbAAQAQAAgDAVQgEAUgVAcQgVAbgZALQgKBDAoAAQAYAAAUgfQARgZAKgnIADAAQgKArgTAdQgXAhgcABQgegBgMgUgAgDg3QgRAdgHAkQAXgKATgbQARgYADgUQACgPgJAAQgPABgQAeg");
	this.shape_13.setTransform(-65.9567,-15.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.txfine, new cjs.Rectangle(-159.7,-44.7,311.7,107.6), null);


(lib.txcta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgfA4QgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAhpQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIA/AAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAIgyAAIAAAhIAqAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIAAAHQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgqAAIAAAjIAyAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape.setTransform(108.05,-0.25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgcA4QAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhpQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAAAAAIALAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAABdIAqAAQABAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAJQAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_1.setTransform(100.05,-0.25);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAnA5QAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIgKgWIg0AAIgJAWQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAIgLAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAAAgBgBIAAgCIAyhrQAAgBAAAAQAAAAABAAQAAgBABAAQAAAAAAAAIABAAQABAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAyBrIAAACQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAgAAUATIgUgrIAAAAIgTArIAnAAg");
	this.shape_2.setTransform(90.4,-0.325);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgEA4QgBAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAhdIgaAAQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAgJQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIBDAAQABAAABAAQAAAAAAABQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAABgBAAQAAABAAAAQgBAAgBAAIgaAAIAABdQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_3.setTransform(81.525,-0.25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAnA5QAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIgKgWIgzAAIgKAWQAAABgBAAQAAABAAAAQgBAAAAABQgBAAgBAAIgKAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgCIAwhrQABgBAAAAQAAAAABAAQAAgBABAAQAAAAAAAAIABAAQAAAAABAAQAAAAABABQAAAAAAAAQAAAAAAABIAyBrIAAACQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAgAAUATIgTgrIgBAAIgTArIAnAAg");
	this.shape_4.setTransform(72.65,-0.325);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAoA5IhFhRIAAAAIAABNQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgLAAQAAAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIAAhqQAAgBABgBQAAAAAAgBQABAAAAAAQABgBAAAAIAFAAIBEBPIAAhKQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAKAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAABrQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAgBAAg");
	this.shape_5.setTransform(61.45,-0.25);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgEA4QgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhpQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAJAAQABAAABAAQAAAAAAABQABAAAAABQAAAAAAABIAABpQAAABAAAAQAAABgBAAQAAABAAAAQgBAAgBAAg");
	this.shape_6.setTransform(49.975,-0.25);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgsA4QgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAhpQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAlAAQAWAAAQAQQARARAAAWQAAAXgRAQQgQARgWAAgAgfApIAVAAQARAAAMgMQALgLAAgSQAAgRgLgMQgMgLgRAAIgVAAg");
	this.shape_7.setTransform(42.4,-0.25);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgfA4QgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAhpQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIA/AAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAIgyAAIAAAhIAqAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIAAAHQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgqAAIAAAjIAyAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_8.setTransform(28.8,-0.25);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgEA4QgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhdIgaAAQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAgJQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIBDAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAJQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAIgaAAIAABdQAAABAAAAQAAABgBAAQAAABAAAAQgBAAgBAAg");
	this.shape_9.setTransform(20.175,-0.25);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAYA4QgBAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAAAIgVgrIgXAAIAAApQAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAIgLAAQAAAAgBAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAhpQAAgBAAAAQABgBAAAAQAAgBABAAQABAAAAAAIArAAQAOAAAKAKQALAKAAAOQAAALgHAJQgGAIgLAEIAWAoIAAAEQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAgAgXAAIAcAAQAHgBAGgFQAGgGAAgJQAAgHgGgGQgGgFgHgBIgcAAg");
	this.shape_10.setTransform(11.575,-0.25);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgfA4QgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAhpQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIA/AAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAIgxAAIAAAhIApAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIAAAHQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgpAAIAAAjIAxAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_11.setTransform(1.9,-0.25);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgfA4QgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAhpQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIA/AAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAIgyAAIAAAlIAqAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAIQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAIgqAAIAAAqQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_12.setTransform(-6.85,-0.25);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgfA4QgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAhpQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIA/AAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAIgyAAIAAAlIAqAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAIQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAIgqAAIAAAqQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_13.setTransform(-15.6,-0.25);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgoApQgRgRAAgYQAAgXARgRQARgRAXAAQAYAAAQARQARARAAAXQAAAYgRARQgQAQgYAAQgXAAgRgQgAgdgcQgLAMgBAQQABASALAMQAMALARAAQARAAAMgLQAMgMAAgSQAAgQgMgMQgMgNgRAAQgQAAgNANg");
	this.shape_14.setTransform(-26.8,-0.25);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgfA4QgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAhpQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIA/AAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAIgxAAIAAAhIApAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIAAAHQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgpAAIAAAjIAxAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_15.setTransform(-40.55,-0.25);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgbA4QgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhpQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAKAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAABdIAqAAQABAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAJQAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_16.setTransform(-48.55,-0.25);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgEA4QgBAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAhpQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIAJAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAABpQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_17.setTransform(-58.525,-0.25);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAYA4QgBAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAAAIgVgrIgXAAIAAApQAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAIgLAAQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAhpQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAIArAAQAOAAAKAKQALAKAAAOQAAALgHAJQgGAIgLAEIAWAoIAAAEQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAgAgXAAIAcAAQAHgBAGgFQAGgGAAgJQAAgHgGgGQgGgFgHgBIgcAAg");
	this.shape_18.setTransform(-65.575,-0.25);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgiA4QgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAhpQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAIAkAAQAPAAAKALQALAKAAAOQAAAPgLAKQgKALgPgBIgWAAIAAAmQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAgAgUAAIAVAAQAIAAAGgGQAGgFAAgJQAAgIgGgFQgGgGgIAAIgVAAg");
	this.shape_19.setTransform(-75.075,-0.25);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgoApQgQgRgBgYQABgXAQgRQARgRAXAAQAYAAAQARQASARgBAXQABAYgSARQgQAQgYAAQgXAAgRgQgAgcgcQgMAMgBAQQABASAMAMQALALARAAQARAAAMgLQAMgMAAgSQAAgQgMgMQgMgNgRAAQgQAAgMANg");
	this.shape_20.setTransform(-86.55,-0.25);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgfApQgRgRAAgYQAAgXARgRQARgRAXAAQAVAAASAPQAAABABABQAAAAAAABQAAAAAAABQgBAAAAABIgHAHQgBABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQgNgLgPAAQgQABgMALQgLANAAAQQAAARALAMQAMAMAQAAQAOAAAOgLQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAIAHAIQAAAAABABQAAAAAAABQAAAAAAABQgBAAAAABQgQAPgXAAQgXAAgRgQg");
	this.shape_21.setTransform(-98.2125,-0.25);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AghAtQgDgCACgDIAEgHQACgDADACQANALAMAAQAIAAAFgFQAFgDAAgHQAAgHgGgFQgGgFgLgFQgOgGgHgGQgIgIAAgNQAAgLAIgJQAJgJARgBQAQAAANAKQADACgCADIgEAHQgCADgDgCQgNgIgIAAQgJAAgFAFQgEAEAAAGQAAALATAJQARAGAHAGQALAJAAAOQAAAMgKAIQgLAKgPgBQgUAAgNgMg");
	this.shape_22.setTransform(-107.74,-0.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.txcta, new cjs.Rectangle(-114.2,-13.4,228.4,26.9), null);


(lib.txcioccola = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E7CEB5").s().p("AiJB6QgQgjAQg4QAUhCAzg4QA2g9A6gHQAHAAgCAFQgvAPglAzQghAtgRA5QgPA1AGAkQAHAmAdAAQAnAAAggnQAdgjAPg1QAIgaABgZIgiAGQgiAAgNgSQgMgQAGgXQAGgTAOgMQAQgOAVAAQA0AAgEBPQAcgKAcgUIAEAFQgiAXgaAMIgKAyQgSA/gkArQgpAwgvAAQg2AAgRgmgAgChdQgFARALAOQANAPAcAAIAYgCQAChEgpAAQgaAAgGAYg");
	this.shape.setTransform(84.6687,-5.675);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E7CEB5").s().p("AiLBiQAThCAqhlQhggHARg9QAOgvA5gYIAGgCQABAAABAAQAAAAAAABQABAAAAABQAAABgBABQgBAEgEAFQgmAPgKAhQgMArBMALQAuhqAYgpQALgTAQAAQAMAAAKAJQgUAcg5CDQBvgCA9gtQAFgCAEAAQAFAAgBADIgDAEQgcAcg3ARQg2ATg3ADQgxBxgXBPQgjB4AnAAQAlAAAshCQAfgvAQgsIAHAAQgZA/geAtQgvBDgwAAQhFAAAwikg");
	this.shape_1.setTransform(74.224,-16.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E7CEB5").s().p("AgMCEQgMgWAKgkQg0BOgxAAQhRAAAfhrQAUhGA2g8QA5hCAyAAQAfAAACAoIAQgBQAegBgHAZQgwBygPA1QgQA3AfAAQAlAAAshCQAggvAPgrIAHAAQgYA+gfAtQgvBDgwAAQgZAAgMgUgAg7hNQgkA3gUBDQgaBaAjAAQA3AAAzhpIAehSQAWhZglAAQghAAgpBAg");
	this.shape_2.setTransform(48.4479,-5.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#E7CEB5").s().p("AiUD3QgDg4AbhdIAFgRIghASIgDgGIAngWQAjhtA2hhQA5hpA4gsQAggYATAAQAdAAgPAyQgQA4g4BRQg9BXhIA/QgZA9gRA+QgpCLAsAAQAlAAAshCQAfgvAPgsIAHAAQgYA/geAtQgvBDgwAAQgmAAgCg+gABnkPQhDBNhVDRQBAg8A3hTQAzhNAPgyQAKgmgPAAQgLAAgRAWg");
	this.shape_3.setTransform(34.7667,-21.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#E7CEB5").s().p("AiJB6QgQgjAQg4QAUhCAzg4QA2g9A6gHQAHAAgCAFQgvAPglAzQghAtgRA5QgPA1AGAkQAHAmAdAAQAnAAAggnQAdgjAPg1QAIgaABgZIgiAGQgiAAgNgSQgMgQAGgXQAGgTAOgMQAQgOAVAAQA0AAgEBPQAcgKAcgUIAEAFQgiAXgaAMIgKAyQgSA/gkArQgpAwgvAAQg2AAgRgmgAgChdQgFARALAOQANAPAcAAIAYgCQAChEgpAAQgaAAgGAYg");
	this.shape_4.setTransform(11.3687,-5.675);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E7CEB5").s().p("Ah7B4QgTglARg7QAUhFA0g4QA3g7A1AAQAaAAAJAUQAIARgHAaQgHAZgRATQgTAUgUAAQgXAAAHgXQAKgjAzgEIAEgMQAMgogjAAQgjAAgnA0QglAxgSA9QgQA3ALAiQAMAoAtAAQAsAAAsg1QAlgtAZhCIAHAAQgbBKgqAyQgxA5g3AAQg/AAgVgpg");
	this.shape_5.setTransform(-8.782,-5.575);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E7CEB5").s().p("Ah7B4QgTglARg7QAUhFA0g4QA3g7A1AAQAaAAAJAUQAIARgHAaQgHAZgRATQgTAUgUAAQgXAAAHgXQAKgjAzgEIAEgMQAMgogjAAQgjAAgnA0QglAxgSA9QgQA3ALAiQAMAoAtAAQAsAAAsg1QAlgtAZhCIAHAAQgbBKgqAyQgxA5g3AAQg/AAgVgpg");
	this.shape_6.setTransform(-27.282,-5.575);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E7CEB5").s().p("AiJB6QgQgjAQg4QAUhCAzg4QA2g9A6gHQAHAAgCAFQgvAPglAzQghAtgRA5QgPA1AGAkQAHAmAdAAQAnAAAggnQAdgjAPg1QAIgaABgZIgiAGQgiAAgNgSQgMgQAGgXQAGgTAOgMQAQgOAVAAQA0AAgEBPQAcgKAcgUIAEAFQgiAXgaAMIgKAyQgSA/gkArQgpAwgvAAQg2AAgRgmgAgChdQgFARALAOQANAPAcAAIAYgCQAChEgpAAQgaAAgGAYg");
	this.shape_7.setTransform(-48.0813,-5.675);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#E7CEB5").s().p("AhNBUQARg6AXg1QANgeAeAAQANAAgCAGQgnBggUBFQgjB3AoABQAlgBArhBQAfgwAQgrIAHAAQgYA+ggAtQguBEgwAAQhIAAAwiogAAgjRQAFgQAMgMQAOgOARAAQAXAAgIAcQgFAQgMAMQgOAOgQAAQgYAAAIgcg");
	this.shape_8.setTransform(-65.0084,-15.35);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#E7CEB5").s().p("Ah7B4QgTglARg7QAUhFA0g4QA3g7A1AAQAaAAAJAUQAIARgHAaQgHAZgRATQgTAUgUAAQgXAAAHgXQAKgjAzgEIAEgMQAMgogjAAQgjAAgnA0QglAxgSA9QgQA3ALAiQAMAoAtAAQAsAAAsg1QAlgtAZhCIAHAAQgbBKgqAyQgxA5g3AAQg/AAgVgpg");
	this.shape_9.setTransform(-81.432,-5.575);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.txcioccola, new cjs.Rectangle(-111,-53.8,222.2,107.69999999999999), null);


(lib.stella = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EDD691").s().p("AgRAPIgtgSIAwgLIAGgwIAXAqIAwgLIghAjIAYApIgtgTIggAlg");
	this.shape.setTransform(0.025,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.stella, new cjs.Rectangle(-6.2,-6.2,12.5,12.5), null);


(lib.sempre = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E7CEB5").s().p("AhdClQgJAAAAgKIAAk2QAAgIAJgBIC7AAQAJABAAAIIAAAbQAAAJgJgBIiTAAIAABgIB8AAQAJAAAAAJIAAAaQAAAJgJAAIh8AAIAABlICTAAQAJAAAAAIIAAAaQAAAKgJAAg");
	this.shape.setTransform(95.5,-0.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E7CEB5").s().p("ABGClQgGAAgCgEIg+h9IhGAAIAAB3QAAAKgJAAIgfAAQgJAAAAgKIAAk2QAAgIAJgBIB/AAQAqAAAeAeQAfAdAAAqQAAAggUAaQgTAYgfAMIBBB4QACAEgCAFQgDAEgGABgAhFgEIBSAAQAXABARgSQASgRAAgYQAAgWgSgSQgRgQgXAAIhSAAg");
	this.shape_1.setTransform(66.225,-0.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E7CEB5").s().p("AhlClQgJAAAAgKIAAk2QAAgIAJgBIBrAAQArAAAfAfQAfAfAAAqQAAAsgfAeQgfAfgrAAIhDAAIAABuQAAAKgJAAgAg9AAIBAAAQAYAAASgRQARgSAAgZQAAgXgRgSQgSgPgYAAIhAAAg");
	this.shape_2.setTransform(37.725,-0.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#E7CEB5").s().p("AgECpQgGAAgBgFIhWjXIgBAAIgiDRQgBAGgIABIgeAAQgLAAACgLIA6k7QACgHAGAAIAIAAQAGAAACAFIBiDvIABAAIBijvQACgFAGAAIAIAAQAGAAACAHIA6E7QACALgLAAIgeAAQgHgBgCgGIgjjRIgBAAIhVDXQgCAFgGAAg");
	this.shape_3.setTransform(2.0066,-0.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#E7CEB5").s().p("AhdClQgJAAAAgKIAAk2QAAgIAJgBIC7AAQAJABAAAIIAAAbQAAAJgJgBIiUAAIAABgIB9AAQAJAAAAAJIAAAaQAAAJgJAAIh9AAIAABlICUAAQAJAAAAAIIAAAaQAAAKgJAAg");
	this.shape_4.setTransform(-30.9,-0.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E7CEB5").s().p("AhjCEQgIgHAFgIIAMgTQAHgLAJAHQAnAgAjABQAYgBAPgNQAOgMAAgSQAAgUgSgQQgQgPgkgOQgpgSgTgSQgZgZAAgmQAAghAXgZQAcgdAzAAQAvAAAoAbQAJAGgHALIgLASQgHAKgKgGQgkgXgaAAQgbAAgPAOQgLAMAAAQQAAAjA6AYQAxAUAWASQAeAbAAAoQAAAkgdAaQgeAagtAAQg9AAgnglg");
	this.shape_5.setTransform(-57.8712,-0.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E7CEB5").s().p("AhdDZQgJAAAAgJIAAk2QAAgJAJAAIC7AAQAJAAAAAJIAAAaQAAAJgJAAIiUAAIAABfIB9AAQAJAAAAAJIAAAaQAAAJgJAAIh9AAIAABlICUAAQAJAAAAAJIAAAaQAAAJgJAAgAAfiSIhOgiQgGgDAEgIIAKgVQAEgHAIAGIBJAqQAGADgDAGIgHAOQgCADgEAAIgFgBg");
	this.shape_6.setTransform(-93.15,-5.921);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.sempre, new cjs.Rectangle(-110.1,-35.6,220.2,71.2), null);


(lib.prodotto2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.instance = new lib.scatola();
	this.instance.parent = this;
	this.instance.setTransform(-87.5,-62);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.prodotto2, new cjs.Rectangle(-87.5,-62,175,124), null);


(lib.prodotto1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.instance = new lib.valigetta();
	this.instance.parent = this;
	this.instance.setTransform(-109.5,-58.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.prodotto1, new cjs.Rectangle(-109.5,-58.5,219,117), null);


(lib.lunetta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FAF5E2").s().p("AswMwQlSlSAAneQAAndFSlTQFTlSHdAAQHeAAFSFSQFTFTAAHdQAAHelTFSQlSFTneAAQndAAlTlTg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.lunetta, new cjs.Rectangle(-115.5,-115.5,231,231), null);


(lib.logobianco = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgoCGQgOgFgLgOQgRgVgBgcQgBgcAPgWQAKgOAAgHQAAgIgKgQQgPgWAFgbQAGgaAWgQQAzglA0AnQAVAQAGAXQAHAagQAYQgLAQAAAIQAAAHALAOQAPAWgBAcQgBAcgRAVQgLAOgOAFQgNAFgcAAQgbAAgNgFgAgbAdQgRAPAAALQAAAhAgANQAgAMAPgcQALgVgBgKQgCgLgOgNQgGgHgJgFQgIgEgGAAQgLAAgQAPgAgOhdQgKABgDADQgLAKAEAXQAFAWAOAIQASAKARgNQAQgNgDgYQgDgYgZgDIgJgBIgKABg");
	this.shape.setTransform(54.2012,16.6067,0.2518,0.2518);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag0CHQAAgHATgxIBDixIgmAAQgZAAgHADQgIAEAAANQAAAUgUAAQgMAAgEgIQgEgHAAgZIAAgoIBUAAQA5AAAOADQAOADgBALQAAAHgNApQgOApgUAwQgdBJgNAZQgNAXgOACIgKAAQgKAAAAgEg");
	this.shape_1.setTransform(49.1531,16.6906,0.2518,0.2518);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgUCIQgqgHgRgoQgQgnAZgiQAJgMAAgIQAAgIgJgSQgPgcACgRQACgRAWgVQAXgXAfgCQAbgCAZAQQAZAPAHAYQAIAbgRAaQgLARAAAHQAAAIALANQAhAwggArQgaAjgrAAQgKAAgMgDgAgdAcQgPARAAAPQAAAeAhAJQAgAJAOgaQAKgUgBgLQgBgKgOgOQgGgGgJgFQgJgFgFAAQgOAAgPARgAgOhgQgKABgDADQgLALAEAWQAFAXAOAHQASALARgNQAQgOgDgYQgCgNgGgGQgHgGgNgCIgKAAIgJAAg");
	this.shape_2.setTransform(43.8885,16.6689,0.2518,0.2518);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AADB+QgDgOAAhXIAAh0IgxAuIAAgZQAAgbAcgUQAMgJANgGQAPgGAJAAQASAAACARQADARgDBnQgCBjgDAUQgEASgQADIgEAAQgNAAgDgNg");
	this.shape_3.setTransform(38.4533,16.6837,0.2518,0.2518);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhlBWQgCgEAJgUQAIgUAOgYQA1haAqgPQASgGAYAAQAZAAAKAHQAMAHgvBJQgvBIgZAPQgVALghACIgKAAQgYAAgGgIg");
	this.shape_4.setTransform(56.0566,-11.1842,0.2518,0.2518);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("ATYK2QghgwAAhCIAAg0IhDA+QhyBrhHAZQhHAYg2gyQgagYgGgPQgGgPgDgyQgDhAAUgzQAVgzBViIQBLh3APgjQAPgigQgRQgPgQgXAHQhIAWijDAQijC/hYCmIghA/IiyAAIAshUQAeg6ADgKQACgKgSAPQhwBcg0AfQg0Agg/ANQhbAThAg4QhBg5AAhlIAAgkIhNBLQh1BxhDAdQhEAdgygqQhghSA6iOQAKgXAjhAQAlhBAnhCQAphFAbgzQAcg0gCgIQgEgVgaACQgbABgmAWQgSAKgxAqQgwAqgyAwQhhBgg7BQQg7BQg7B2IgxBiIhYAAQhYAAADgIIBZitIhDA3QhmBUhuApQhtAphJgUQgrgMglglQgmgmgMgrQgWhRAjhiQAghcBLhVQBLhWBgg3QBng8BmgKQBfgKAXA4QAWA5hCBTQgkAuhPAxQhPAyhlApIhiAoIgiBGQgeBAgDAsQgDAtAZANQAYANA4gIQA3gHAxgXQBugyB2hsQB2hsBKh2QA7hdAegjQAdgjAkgTQAagNAqgNQAqgOAAAFIgyBuIgyBsIBfhbQBYhUAygeQAxgfAxgBQAdAAAPAFQAPAEASASQAVAVAQAkQAPAlAAAeQAABIhvC3QhkCkgRAxQgRAzAvgKQA7gMB9h2QB9h2AWhBQAqh8COhuQCPhvCPgTQA7gIA5AEQA6ADAHAMQAGAJgrAPQgrAQgpADQgVABgcAJQgdAHgTAJQhiAvh5CoQh5CogNBpQgGA6AIAXQAJAWAfAGQA9ALBPgrQBQgrBrhlQBNhJBBhdQA/hdBcirQDfmhB/ivQB9iuBsgoQAkgMAeAAIAjgBIgtAlQhxBehaCOQhbCLjEGBIiXEpIBJhQQB5iFBMg9QBLg9AsAAQAXAAAiAaQAiAZAOAdQAUAmgCA4QgCA3gWAuQgeA/hBBpQhFBygVArQgWArAFANQANAiBNgvQBNguBghkQAwgyAmgxQAmgzAnhBQAegyAhgxQAggvANgQQAcghAsgXQAsgYAiAAIAgAAIiREjQg6B0gsBdQgrBaAAAGQAAATAWACQAWABAhgSQATgKAngiQAngjAkgnQBahfAPAHQAPAFgJATQgKARgxA6QhHBUhIAzQhIA0gtAAQguAAghgugAyKBOQgvAdgvAvQguAvg9BVQg+BUAHAHQAEAEBigvQA2gaAjgYQAkgYAhgiQA4g3AXgoQAXgngMgUQgEgHgHgGQgIgFgGgBIgGgBQgXAAgoAag");
	this.shape_5.setTransform(14.4027,-7.5371,0.2518,0.2518);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag7DEQgHgcgBgTQgCgXAFgXQAEgWARg2QATg6AGgZQAGgZABgcQABghgFgTQgFgTgPgNQgKgKgPgEQgOgEgQABQgfADgcAUQgcAUgVAgQgVAggKAnQgMApACAoQABAeAFAMQAEAMALALQALAKAMAEIAKAFIAHAEQABAAABABQAAAAAAABQABAAgBAAQAAABAAAAIgQAAQgWgBgOgKQgPgJgIgTQgQgiAHg0QAHg2AagsQAagsAmgdQAlgcAngFIAKgCQAFAAAPADQAQAEAGAEQAaANANAfQAPAfAAAqQAAAbgEAXQgEAXgLAiIgiBxQgIAcgDAQQgFAdADAAQAEAAAOgfQAWgyAhg3QAhg3AhgqIAYgbIAbgdQAjgiAcgUQAcgTAUgDIAJAAIgDAEQgCACgGAEIgLAGQgcANgzAzQgaAbgUAXQgTAXgSAZQgTAcgdAxQgeAygVAqIgSAfQgIANgBAAQgEAAgIgcg");
	this.shape_6.setTransform(-31.3808,-10.5531);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.logobianco, new cjs.Rectangle(-57.6,-32.9,116.30000000000001,53.099999999999994), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#552D00").s().p("AgoCGQgOgFgLgOQgRgVgBgcQgBgcAPgWQAKgOAAgHQAAgIgKgQQgPgWAFgbQAGgaAWgQQAzglA0AnQAVAQAGAXQAHAagQAYQgLAQAAAIQAAAHALAOQAPAWgBAcQgBAcgRAVQgLAOgOAFQgNAFgcAAQgbAAgNgFgAgbAdQgRAPAAALQAAAhAgANQAgAMAPgcQALgVgBgKQgCgLgOgNQgGgHgJgFQgIgEgGAAQgLAAgQAPgAgOhdQgKABgDADQgLAKAEAXQAFAWAOAIQASAKARgNQAQgNgDgYQgDgYgZgDIgJgBIgKABg");
	this.shape.setTransform(54.2012,16.6067,0.2518,0.2518);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#552D00").s().p("Ag0CHQAAgHATgxIBDixIgmAAQgZAAgHADQgIAEAAANQAAAUgUAAQgMAAgEgIQgEgHAAgZIAAgoIBUAAQA5AAAOADQAOADgBALQAAAHgNApQgOApgUAwQgdBJgNAZQgNAXgOACIgKAAQgKAAAAgEg");
	this.shape_1.setTransform(49.1531,16.6906,0.2518,0.2518);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#552D00").s().p("AgUCIQgqgHgRgoQgQgnAZgiQAJgMAAgIQAAgIgJgSQgPgcACgRQACgRAWgVQAXgXAfgCQAbgCAZAQQAZAPAHAYQAIAbgRAaQgLARAAAHQAAAIALANQAhAwggArQgaAjgrAAQgKAAgMgDgAgdAcQgPARAAAPQAAAeAhAJQAgAJAOgaQAKgUgBgLQgBgKgOgOQgGgGgJgFQgJgFgFAAQgOAAgPARgAgOhgQgKABgDADQgLALAEAWQAFAXAOAHQASALARgNQAQgOgDgYQgCgNgGgGQgHgGgNgCIgKAAIgJAAg");
	this.shape_2.setTransform(43.8885,16.6689,0.2518,0.2518);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#552D00").s().p("AADB+QgDgOAAhXIAAh0IgxAuIAAgZQAAgbAcgUQAMgJANgGQAPgGAJAAQASAAACARQADARgDBnQgCBjgDAUQgEASgQADIgEAAQgNAAgDgNg");
	this.shape_3.setTransform(38.4533,16.6837,0.2518,0.2518);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#552D00").s().p("AhlBWQgCgEAJgUQAIgUAOgYQA1haAqgPQASgGAYAAQAZAAAKAHQAMAHgvBJQgvBIgZAPQgVALghACIgKAAQgYAAgGgIg");
	this.shape_4.setTransform(56.0566,-11.1842,0.2518,0.2518);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#552D00").s().p("ATYK2QghgwAAhCIAAg0IhDA+QhyBrhHAZQhHAYg2gyQgagYgGgPQgGgPgDgyQgDhAAUgzQAVgzBViIQBLh3APgjQAPgigQgRQgPgQgXAHQhIAWijDAQijC/hYCmIghA/IiyAAIAshUQAeg6ADgKQACgKgSAPQhwBcg0AfQg0Agg/ANQhbAThAg4QhBg5AAhlIAAgkIhNBLQh1BxhDAdQhEAdgygqQhghSA6iOQAKgXAjhAQAlhBAnhCQAphFAbgzQAcg0gCgIQgEgVgaACQgbABgmAWQgSAKgxAqQgwAqgyAwQhhBgg7BQQg7BQg7B2IgxBiIhYAAQhYAAADgIIBZitIhDA3QhmBUhuApQhtAphJgUQgrgMglglQgmgmgMgrQgWhRAjhiQAghcBLhVQBLhWBgg3QBng8BmgKQBfgKAXA4QAWA5hCBTQgkAuhPAxQhPAyhlApIhiAoIgiBGQgeBAgDAsQgDAtAZANQAYANA4gIQA3gHAxgXQBugyB2hsQB2hsBKh2QA7hdAegjQAdgjAkgTQAagNAqgNQAqgOAAAFIgyBuIgyBsIBfhbQBYhUAygeQAxgfAxgBQAdAAAPAFQAPAEASASQAVAVAQAkQAPAlAAAeQAABIhvC3QhkCkgRAxQgRAzAvgKQA7gMB9h2QB9h2AWhBQAqh8COhuQCPhvCPgTQA7gIA5AEQA6ADAHAMQAGAJgrAPQgrAQgpADQgVABgcAJQgdAHgTAJQhiAvh5CoQh5CogNBpQgGA6AIAXQAJAWAfAGQA9ALBPgrQBQgrBrhlQBNhJBBhdQA/hdBcirQDfmhB/ivQB9iuBsgoQAkgMAeAAIAjgBIgtAlQhxBehaCOQhbCLjEGBIiXEpIBJhQQB5iFBMg9QBLg9AsAAQAXAAAiAaQAiAZAOAdQAUAmgCA4QgCA3gWAuQgeA/hBBpQhFBygVArQgWArAFANQANAiBNgvQBNguBghkQAwgyAmgxQAmgzAnhBQAegyAhgxQAggvANgQQAcghAsgXQAsgYAiAAIAgAAIiREjQg6B0gsBdQgrBaAAAGQAAATAWACQAWABAhgSQATgKAngiQAngjAkgnQBahfAPAHQAPAFgJATQgKARgxA6QhHBUhIAzQhIA0gtAAQguAAghgugAyKBOQgvAdgvAvQguAvg9BVQg+BUAHAHQAEAEBigvQA2gaAjgYQAkgYAhgiQA4g3AXgoQAXgngMgUQgEgHgHgGQgIgFgGgBIgGgBQgXAAgoAag");
	this.shape_5.setTransform(14.4027,-7.5371,0.2518,0.2518);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#552D00").s().p("Ag7DEQgHgcgBgTQgCgXAFgXQAEgWARg2QATg6AGgZQAGgZABgcQABghgFgTQgFgTgPgNQgKgKgPgEQgOgEgQABQgfADgcAUQgcAUgVAgQgVAggKAnQgMApACAoQABAeAFAMQAEAMALALQALAKAMAEIAKAFIAHAEQABAAABABQAAAAAAABQABAAgBAAQAAABAAAAIgQAAQgWgBgOgKQgPgJgIgTQgQgiAHg0QAHg2AagsQAagsAmgdQAlgcAngFIAKgCQAFAAAPADQAQAEAGAEQAaANANAfQAPAfAAAqQAAAbgEAXQgEAXgLAiIgiBxQgIAcgDAQQgFAdADAAQAEAAAOgfQAWgyAhg3QAhg3AhgqIAYgbIAbgdQAjgiAcgUQAcgTAUgDIAJAAIgDAEQgCACgGAEIgLAGQgcANgzAzQgaAbgUAXQgTAXgSAZQgTAcgdAxQgeAygVAqIgSAfQgIANgBAAQgEAAgIgcg");
	this.shape_6.setTransform(-31.3808,-10.5531);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-57.6,-32.9,116.30000000000001,53.099999999999994), null);


(lib.interrogativo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E7CEB5").s().p("AgYCFQgHgJAAgLQAAgLAHgIQAIgIALAAQALAAAIAIQAIAIAAALQAAALgIAJQgIAHgLAAQgLAAgIgHgAgPAeQgHAAAAgHIAAgQQAAgWAbgVQAPgMAEgFQAJgLAAgMQAAgMgJgJQgJgJgQAAQgRAAgOAJIgRAPQgEADgFgDIgNgNQgEgEAEgGQAZgjAwAAQAfAAAUASQAVASAAAbQAAAbgeAZIgVAQQgKAJAAAIIAAAOQAAAJgIgBg");
	this.shape.setTransform(-0.0375,-0.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.interrogativo, new cjs.Rectangle(-10.8,-29.9,21.6,59.8), null);


(lib.il = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E7CEB5").s().p("AhTClQgJAAAAgKIAAk2QAAgIAJgBIAfAAQAJABAAAIIAAEUIB/AAQAJAAAAAIIAAAaQAAAKgJAAg");
	this.shape.setTransform(9.075,-0.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E7CEB5").s().p("AgOClQgJAAAAgKIAAk2QAAgIAJgBIAdAAQAKABgBAIIAAE2QABAKgKAAg");
	this.shape_1.setTransform(-11.45,-0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.il, new cjs.Rectangle(-20.5,-35.6,41,71.2), null);


(lib.txfineanim = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{apri:1});

	// timeline functions:
	this.frame_0 = function() {
		this.visible=false;
		this.stop();
	}
	this.frame_1 = function() {
		this.visible=true;
	}
	this.frame_3 = function() {
		this.parent.logolunetta.gotoAndPlay("apri");
	}
	this.frame_18 = function() {
		this.stop();
		this.parent.cta.gotoAndPlay("apri");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(2).call(this.frame_3).wait(15).call(this.frame_18).wait(1));

	// Livello_1
	this.instance = new lib.txfine();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({scaleX:2.62,scaleY:2.62,alpha:0},0).to({scaleX:1,scaleY:1,alpha:1},17,cjs.Ease.backOut).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-418.4,-117.2,816.7,281.9);


(lib.txcioccolaanim = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{"apri":1,cambio:10});

	// timeline functions:
	this.frame_0 = function() {
		this.visible=false;
		this.stop();
	}
	this.frame_1 = function() {
		this.visible=true;
	}
	this.frame_10 = function() {
		this.stop();
	}
	this.frame_14 = function() {
		this.parent.stelle.gotoAndPlay("apri");
	}
	this.frame_45 = function() {
		var tl=this;
		tl.stop();
		var delay = 2000;
		var startTime=createjs.Ticker.getTime();
		createjs.Ticker.addEventListener('tick',f);
		function f(e){
		    if(createjs.Ticker.getTime()-startTime>delay){
		       tl.play();
		        createjs.Ticker.removeEventListener('tick',f);
		    }
		}
	}
	this.frame_67 = function() {
		var tl=this;
		tl.stop();
		var delay = 1000;
		var startTime=createjs.Ticker.getTime();
		createjs.Ticker.addEventListener('tick',f);
		function f(e){
		    if(createjs.Ticker.getTime()-startTime>delay){
		       tl.play();
		        createjs.Ticker.removeEventListener('tick',f);
		    }
		}
	}
	this.frame_77 = function() {
		this.stop();
		this.parent.testofine.gotoAndPlay("apri");
		this.parent.stelle.gotoAndPlay("fine");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(9).call(this.frame_10).wait(4).call(this.frame_14).wait(31).call(this.frame_45).wait(22).call(this.frame_67).wait(10).call(this.frame_77).wait(1));

	// interrogativo
	this.instance = new lib.interrogativo();
	this.instance.parent = this;
	this.instance.setTransform(108.45,-3.5,1.04,1.04,0,0,0,0.1,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({x:191.7},0).to({x:108.45},9,cjs.Ease.backOut).to({regX:0.2,regY:-0.2,scaleX:0.55,scaleY:0.55,x:108.4,y:-17,alpha:0},8,cjs.Ease.get(-1)).wait(60));

	// cioccolato
	this.instance_1 = new lib.txcioccola();
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({scaleX:2.76,scaleY:2.76,alpha:0},0).to({scaleX:1,scaleY:1,alpha:1},9,cjs.Ease.backOut).to({regY:-0.1,scaleX:0.59,scaleY:0.59,x:-41.1,y:-123.1},8,cjs.Ease.backOut).wait(49).to({alpha:0},10,cjs.Ease.get(-1)).wait(1));

	// una_buona_idea
	this.instance_2 = new lib.unabuonaidea();
	this.instance_2.parent = this;
	this.instance_2.setTransform(0,-91.65,0.2,0.2,0,0,0,0,-0.2);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(31).to({_off:false},0).to({scaleX:0.5336,scaleY:0.5336},7,cjs.Ease.backOut).wait(29).to({alpha:0},10,cjs.Ease.get(-1)).wait(1));

	// sempre
	this.instance_3 = new lib.sempre();
	this.instance_3.parent = this;
	this.instance_3.setTransform(76.3,-126.15,0.2,0.2,0,0,0,0.2,-0.2);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(24).to({_off:false},0).to({regX:0,regY:0,scaleX:0.5336,scaleY:0.5336},7,cjs.Ease.backOut).wait(36).to({alpha:0},10,cjs.Ease.get(-1)).wait(1));

	// il
	this.instance_4 = new lib.il();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-114.15,-125.4,0.23,0.23,0,0,0,-0.2,0);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(17).to({_off:false},0).to({regX:-0.1,scaleX:0.5336,scaleY:0.5336},7,cjs.Ease.backOut).wait(43).to({alpha:0},10,cjs.Ease.get(-1)).wait(1));

	// prodotto1
	this.instance_5 = new lib.prodotto1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-285,-13.5);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(38).to({_off:false},0).to({x:0},7,cjs.Ease.backOut).to({scaleX:0.59,scaleY:0.59,alpha:0},11,cjs.Ease.get(1)).to({_off:true},1).wait(21));

	// prodotto2
	this.instance_6 = new lib.prodotto2();
	this.instance_6.parent = this;
	this.instance_6.setTransform(-285,-13.5);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(52).to({_off:false},0).to({x:0},15,cjs.Ease.backOut).to({scaleX:0.68,scaleY:0.68,y:-13.45,alpha:0},10,cjs.Ease.get(-1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-394.5,-164.6,701.3,313.29999999999995);


(lib.txaperturaanim = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{"apri":1});

	// timeline functions:
	this.frame_0 = function() {
		this.visible=false;
		this.stop();
	}
	this.frame_1 = function() {
		this.visible=true;
	}
	this.frame_9 = function() {
		var tl=this;
		tl.stop();
		var delay = 200;
		var startTime=createjs.Ticker.getTime();
		createjs.Ticker.addEventListener('tick',f);
		function f(e){
		    if(createjs.Ticker.getTime()-startTime>delay){
		       tl.play();
		        createjs.Ticker.removeEventListener('tick',f);
		    }
		}
	}
	this.frame_17 = function() {
		var tl=this;
		tl.stop();
		var delay = 200;
		var startTime=createjs.Ticker.getTime();
		createjs.Ticker.addEventListener('tick',f);
		function f(e){
		    if(createjs.Ticker.getTime()-startTime>delay){
		       tl.play();
		        createjs.Ticker.removeEventListener('tick',f);
		    }
		}
	}
	this.frame_25 = function() {
		this.parent.txcioccola.gotoAndPlay("apri");
		
		var tl=this;
		tl.stop();
		var delay = 1500;
		var startTime=createjs.Ticker.getTime();
		createjs.Ticker.addEventListener('tick',f);
		function f(e){
		    if(createjs.Ticker.getTime()-startTime>delay){
		       tl.play();
		        createjs.Ticker.removeEventListener('tick',f);
		    }
		}
	}
	this.frame_33 = function() {
		this.stop();
		this.parent.txcioccola.gotoAndPlay("cambio");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(8).call(this.frame_9).wait(8).call(this.frame_17).wait(8).call(this.frame_25).wait(8).call(this.frame_33).wait(1));

	// tx3
	this.instance = new lib.tx3();
	this.instance.parent = this;
	this.instance.setTransform(0,22.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},1).wait(16).to({_off:false,regY:0.1,scaleX:0.42,scaleY:0.42,alpha:0},0).to({regY:0,scaleX:1,scaleY:1,alpha:1},8,cjs.Ease.backOut).to({regY:0.1,scaleX:0.42,scaleY:0.42,alpha:0},8).wait(1));

	// tx2
	this.instance_1 = new lib.tx2();
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({_off:true},1).wait(8).to({_off:false,scaleX:0.35,scaleY:0.35,alpha:0},0).to({scaleX:1,scaleY:1,alpha:1},8,cjs.Ease.backOut).wait(8).to({scaleX:0.35,scaleY:0.35,alpha:0},8).wait(1));

	// tx1
	this.instance_2 = new lib.tx1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(0,-22.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1).to({scaleX:0.41,scaleY:0.41,alpha:0},0).to({scaleX:1,scaleY:1,alpha:1},8,cjs.Ease.backOut).wait(16).to({scaleX:0.41,scaleY:0.41,alpha:0},8).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-91.2,-36.3,182.5,72.5);


(lib.stelleanim = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{"apri":1,fine:30});

	// timeline functions:
	this.frame_0 = function() {
		this.visible=false;
		this.stop();
	}
	this.frame_1 = function() {
		this.visible=true;
	}
	this.frame_30 = function() {
		this.stop();
	}
	this.frame_40 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(29).call(this.frame_30).wait(10).call(this.frame_40).wait(1));

	// stella
	this.instance = new lib.stella();
	this.instance.parent = this;
	this.instance.setTransform(-95.95,-46.6,0.68,0.68);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},1).wait(2).to({_off:false,x:-124.2,y:-171.3},0).to({y:-73.4},13,cjs.Ease.backOut).wait(14).to({x:-95.95,y:-46.6},10,cjs.Ease.backOut).wait(1));

	// stella
	this.instance_1 = new lib.stella();
	this.instance_1.parent = this;
	this.instance_1.setTransform(63.4,-41.45,0.36,0.36,0,0,0,0,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({_off:true},1).wait(4).to({_off:false,regY:0,scaleX:0.46,scaleY:0.46,x:-90.9,y:-171.3},0).to({y:74.75},13,cjs.Ease.backOut).wait(12).to({regY:-0.1,scaleX:0.36,scaleY:0.36,x:63.4,y:-41.45},10,cjs.Ease.backOut).wait(1));

	// stella
	this.instance_2 = new lib.stella();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-132.75,-26.35,1.03,1.03);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},1).wait(7).to({_off:false,x:-128.2,y:-171.3},0).to({y:-6.4},13,cjs.Ease.backOut).wait(9).to({x:-132.75,y:-26.35},10,cjs.Ease.backOut).wait(1));

	// stella
	this.instance_3 = new lib.stella();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-128.2,62.7,1.03,1.03);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({_off:true},1).wait(16).to({_off:false,y:-171.3},0).to({y:62.7},13,cjs.Ease.backOut).wait(11));

	// stella
	this.instance_4 = new lib.stella();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-117.9,63,0.46,0.46);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({_off:true},1).wait(11).to({_off:false,y:-171.3},0).to({y:63},13,cjs.Ease.backOut).wait(16));

	// stella
	this.instance_5 = new lib.stella();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-105.95,24.4,0.46,0.46);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1).to({scaleX:0.3,scaleY:0.3,x:-100.3,y:-171.3},0).to({y:45.1},13,cjs.Ease.backOut).wait(16).to({scaleX:0.46,scaleY:0.46,x:-105.95,y:24.4},10,cjs.Ease.backOut).wait(1));

	// stella
	this.instance_6 = new lib.stella();
	this.instance_6.parent = this;
	this.instance_6.setTransform(45.65,-52.35,0.3,0.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({_off:true},1).wait(1).to({_off:false,x:-88.55,y:-171.3},0).to({y:54.85},13,cjs.Ease.backOut).wait(15).to({x:45.65,y:-52.35},10,cjs.Ease.backOut).wait(1));

	// stella
	this.instance_7 = new lib.stella();
	this.instance_7.parent = this;
	this.instance_7.setTransform(57.25,-40.45,0.3,0.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({_off:true},1).wait(5).to({_off:false,x:-81.55,y:-171.3},0).to({y:54.35},13,cjs.Ease.backOut).wait(11).to({x:57.25,y:-40.45},10,cjs.Ease.backOut).wait(1));

	// stella
	this.instance_8 = new lib.stella();
	this.instance_8.parent = this;
	this.instance_8.setTransform(125.9,51.1,0.3,0.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({_off:true},1).wait(12).to({_off:false,x:115.2,y:-171.3},0).to({y:1.95},13,cjs.Ease.backOut).wait(4).to({x:125.9,y:51.1},10,cjs.Ease.backOut).wait(1));

	// stella
	this.instance_9 = new lib.stella();
	this.instance_9.parent = this;
	this.instance_9.setTransform(132.75,47.35,0.3,0.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({_off:true},1).wait(6).to({_off:false,x:122.05,y:-171.3},0).to({y:-1.8},13,cjs.Ease.backOut).wait(10).to({x:132.75,y:47.35},10,cjs.Ease.backOut).wait(1));

	// stella
	this.instance_10 = new lib.stella();
	this.instance_10.parent = this;
	this.instance_10.setTransform(132.75,30.6,0.3,0.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({_off:true},1).wait(2).to({_off:false,x:122.05,y:-171.3},0).to({y:-18.55},13,cjs.Ease.backOut).wait(14).to({x:132.75,y:30.6},10,cjs.Ease.backOut).wait(1));

	// stella
	this.instance_11 = new lib.stella();
	this.instance_11.parent = this;
	this.instance_11.setTransform(116.6,-68.1,1.33,1.33);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({_off:true},1).wait(8).to({_off:false,x:114.5,y:-171.3},0).to({y:-61.1},13,cjs.Ease.backOut).wait(8).to({x:116.6,y:-68.1},10,cjs.Ease.backOut).wait(1));

	// stella
	this.instance_12 = new lib.stella();
	this.instance_12.parent = this;
	this.instance_12.setTransform(110.85,-28.85,0.6299,0.6299);

	this.timeline.addTween(cjs.Tween.get(this.instance_12).to({_off:true},1).wait(7).to({_off:false,x:98.85,y:-171.25},0).to({y:-27.5},13,cjs.Ease.backOut).wait(9).to({x:110.85,y:-28.85},10,cjs.Ease.backOut).wait(1));

	// stella
	this.instance_13 = new lib.stella();
	this.instance_13.parent = this;
	this.instance_13.setTransform(-23.1,-37.6,1.4,1.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(1).to({x:125.85,y:-171.3},0).to({y:65},13,cjs.Ease.backOut).wait(16).to({x:-23.1,y:-37.6},10,cjs.Ease.backOut).wait(1));

	// stella
	this.instance_14 = new lib.stella();
	this.instance_14.parent = this;
	this.instance_14.setTransform(-134.75,-121.55,0.34,0.34,0,0,0,-0.1,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_14).to({_off:true},1).wait(29).to({_off:false,y:-170.55},0).to({y:-121.55},10,cjs.Ease.backOut).wait(1));

	// stella
	this.instance_15 = new lib.stella();
	this.instance_15.parent = this;
	this.instance_15.setTransform(-128.45,-120.85,0.34,0.34,0,0,0,-0.1,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_15).to({_off:true},1).wait(29).to({_off:false,y:-169.85},0).to({y:-120.85},10,cjs.Ease.backOut).wait(1));

	// stella
	this.instance_16 = new lib.stella();
	this.instance_16.parent = this;
	this.instance_16.setTransform(-114.75,-131.45,0.34,0.34,0,0,0,-0.1,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_16).to({_off:true},1).wait(29).to({_off:false,y:-180.45},0).to({y:-131.45},10,cjs.Ease.backOut).wait(1));

	// stella
	this.instance_17 = new lib.stella();
	this.instance_17.parent = this;
	this.instance_17.setTransform(-2.5,-140.9,0.59,0.59,0,0,0,0,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_17).to({_off:true},1).wait(29).to({_off:false,y:-189.9},0).to({y:-140.9},10,cjs.Ease.backOut).wait(1));

	// stella
	this.instance_18 = new lib.stella();
	this.instance_18.parent = this;
	this.instance_18.setTransform(-13.95,-140.85,0.91,0.91);

	this.timeline.addTween(cjs.Tween.get(this.instance_18).to({_off:true},1).wait(29).to({_off:false,y:-189.85},0).to({y:-140.85},10,cjs.Ease.backOut).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-139.6,-195.5,275.29999999999995,297.2);


(lib.logolunettaanim = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{"apri":1});

	// timeline functions:
	this.frame_0 = function() {
		this.visible=false;
		this.stop();
	}
	this.frame_1 = function() {
		this.visible=true;
	}
	this.frame_22 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(21).call(this.frame_22).wait(1));

	// Livello_1
	this.instance = new lib.logo();
	this.instance.parent = this;
	this.instance.setTransform(-0.8,22.35,1.3074,1.3074,0,0,0,-0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},1).wait(8).to({_off:false,y:127.4},0).to({y:22.35},13,cjs.Ease.backOut).wait(1));

	// Livello_2
	this.instance_1 = new lib.lunetta();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,68.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({y:181.1},0).to({y:68.3},13,cjs.Ease.backOut).wait(9));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-115.5,-58.2,231,354.8);


(lib.logobiancoanim = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{"apri":1});

	// timeline functions:
	this.frame_0 = function() {
		this.visible=false;
	}
	this.frame_1 = function() {
		this.visible=true;
	}
	this.frame_14 = function() {
		this.stop();
		this.parent.testoapertura.gotoAndPlay("apri");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(13).call(this.frame_14).wait(1));

	// Livello_1
	this.instance = new lib.logobianco();
	this.instance.parent = this;
	this.instance.setTransform(-0.4,5.4,0.84,0.84);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({y:72.9},0).to({y:5.4},13,cjs.Ease.backOut).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-48.8,-28.9,97.8,118.80000000000001);


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_2
	this.instance = new lib.txcta();
	this.instance.parent = this;
	this.instance.setTransform(0.1,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// base
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#004D71").s().p("AzRCkIAAlHMAmjAAAIAAFHg");
	this.shape.setTransform(0.05,-0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.CTA, new cjs.Rectangle(-123.3,-16.4,246.8,32.8), null);


(lib.CTAanim = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{"apri":1});

	// timeline functions:
	this.frame_0 = function() {
		this.visible=false;
		this.stop();
	}
	this.frame_1 = function() {
		this.visible=true;
	}
	this.frame_14 = function() {
		var tl = this;
		tl.stop();
		var delay = 1000;
		var startTime = createjs.Ticker.getTime();
		createjs.Ticker.addEventListener('tick', f);
		function f(e) {
			if (createjs.Ticker.getTime() - startTime > delay) {
				tl.play();
				createjs.Ticker.removeEventListener('tick', f);
			}
		}
	}
	this.frame_44 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(13).call(this.frame_14).wait(30).call(this.frame_44).wait(1));

	// Livello_1
	this.cta = new lib.CTA();
	this.cta.name = "cta";
	this.cta.parent = this;
	this.cta.setTransform(0,0.05);

	this.timeline.addTween(cjs.Tween.get(this.cta).wait(1).to({scaleX:0.14,scaleY:0.14},0).to({scaleX:1,scaleY:1},13,cjs.Ease.backOut).to({scaleX:0.7656,scaleY:0.7656,y:0},5,cjs.Ease.sineOut).to({scaleX:1,scaleY:1,y:0.05},5,cjs.Ease.sineIn).to({scaleX:0.7656,scaleY:0.7656,y:0},5,cjs.Ease.sineOut).to({scaleX:1,scaleY:1,y:0.05},5,cjs.Ease.sineIn).to({scaleX:0.7656,scaleY:0.7656,y:0},5,cjs.Ease.sineOut).to({scaleX:1,scaleY:1,y:0.05},5,cjs.Ease.sineIn).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-133.7,-17.7,267.6,35.5);


// stage content:
(lib._300x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cornice
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#552D00").ss(2,1,0,3).p("A3bzhMAu3AAAMAAAAnDMgu3AAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// logolunetta
	this.logolunetta = new lib.logolunettaanim();
	this.logolunetta.name = "logolunetta";
	this.logolunetta.parent = this;
	this.logolunetta.setTransform(150.8,255.85,0.64,0.64,0,0,0,0.1,70.1);

	this.timeline.addTween(cjs.Tween.get(this.logolunetta).wait(1));

	// logo
	this.instance = new lib.logobiancoanim();
	this.instance.parent = this;
	this.instance.setTransform(149.95,223.85,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// txcioccola
	this.txcioccola = new lib.txcioccolaanim();
	this.txcioccola.name = "txcioccola";
	this.txcioccola.parent = this;
	this.txcioccola.setTransform(147.25,159.45);

	this.timeline.addTween(cjs.Tween.get(this.txcioccola).wait(1));

	// testoapertura
	this.testoapertura = new lib.txaperturaanim();
	this.testoapertura.name = "testoapertura";
	this.testoapertura.parent = this;
	this.testoapertura.setTransform(156,64.45,1.41,1.41);

	this.timeline.addTween(cjs.Tween.get(this.testoapertura).wait(1));

	// testofine
	this.testofine = new lib.txfineanim();
	this.testofine.name = "testofine";
	this.testofine.parent = this;
	this.testofine.setTransform(155.15,73.7,0.98,0.98,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.testofine).wait(1));

	// CTA
	this.cta = new lib.CTAanim();
	this.cta.name = "cta";
	this.cta.parent = this;
	this.cta.setTransform(150,152.2,0.93,0.93);

	this.timeline.addTween(cjs.Tween.get(this.cta).wait(1));

	// stelle
	this.stelle = new lib.stelleanim();
	this.stelle.name = "stelle";
	this.stelle.parent = this;
	this.stelle.setTransform(154.6,158.45);

	this.timeline.addTween(cjs.Tween.get(this.stelle).wait(1));

	// fondo
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CC0935").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape_1.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(148.6,124,155.4,204.60000000000002);
// library properties:
lib.properties = {
	id: 'A5824EF831524BA88269F5180A0CAEF6',
	width: 300,
	height: 250,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"scatola.png?1572260057940", id:"scatola"},
		{src:"valigetta.png?1572260057940", id:"valigetta"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['A5824EF831524BA88269F5180A0CAEF6'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;