(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.immagine = function() {
	this.initialize(img.immagine);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,499,600);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.tx2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgYA3QgLgGgFgKQgGgLAAgNIAAgPIAAgOQAAgNAGgLQAFgKALgGQAKgGAOAAQAOAAALAGQAKAGAGAKQAFALABANIAAAOIAAAPQgBANgFALQgGAKgKAGQgLAGgOAAQgOAAgKgGgAgVglQgIAIgBAQIAAANIAAAOQABAQAIAIQAIAIANAAQANAAAJgIQAIgIABgQIAAgOIAAgNQgBgQgIgIQgJgIgNAAQgNAAgIAIg");
	this.shape.setTransform(100.375,63.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgDA8QAAgBAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgDIAAhiIggAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBIgBgDIAAgGIABgDQAAAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAIBOAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQAAABAAAAQABABAAAAIAAAGQAAAAgBABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgfAAIAABiQAAAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAIgEACg");
	this.shape_1.setTransform(89.85,63.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAtA8QgFAAgBgEIgJgYIg7AAIgIAYQgBAEgFAAIgHAAIgCgBQgBgBAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIABgDIAphqQACgGAGABIAJAAQAGgBACAGIAqBqIAAADIgBADIgDABgAAYARIgXg7IgXA7IAuAAg");
	this.shape_2.setTransform(79.2,63.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgWA5QgLgGgFgHQgGgHgBgHIABgDIADgBIAHAAIADAAIACAEQADAFAHAGQAHAFAMAAQAMAAAJgFQAIgGAAgJQAAgFgEgEQgFgDgIgDIgVgHQgRgEgHgHQgIgJAAgLQAAgJAFgIQAFgHAJgFQAJgEANAAQAMAAAKAFQAJAFAFAHQAGAIAAAFIgBADIgDABIgHAAIgDgBIgCgDQgDgEgGgGQgHgFgKAAQgKAAgHAFQgHAEAAAJQAAAGADADQAEAEAHACIAUAHQATAFAIAGQAJAIAAAMQAAALgGAHQgGAJgKAEQgLAEgNAAQgMAAgKgEg");
	this.shape_3.setTransform(68.175,63.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgiAvQgLgNAAgWIAAhDQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgBABAAIADgBIAHAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAIABADIAABEQAAARAIAIQAIAIANAAQAOAAAIgIQAIgIAAgRIAAhEQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAIADgBIAHAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABQABAAAAAAQAAABAAAAIAABDQAAAWgMANQgLANgXAAQgWAAgMgNg");
	this.shape_4.setTransform(57.025,63.875);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYA3QgLgGgFgKQgGgLAAgNIAAgPIAAgOQAAgNAGgLQAFgKALgGQAKgGAOAAQAOAAALAGQAKAGAGAKQAFALABANIAAAOIAAAPQgBANgFALQgGAKgKAGQgLAGgOAAQgOAAgKgGgAgVglQgIAIgBAQIAAANIAAAOQABAQAIAIQAIAIANAAQANAAAJgIQAIgIABgQIAAgOIAAgNQgBgQgIgIQgJgIgNAAQgNAAgIAIg");
	this.shape_5.setTransform(41.325,63.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAiA8QgBgBAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAIgDgEIg2hSIAABTQAAAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAQAAAAgBABIgHAAIgDgCQAAAAgBgBQAAAAAAAAQAAgBAAAAQgBgBAAAAIAAhtQAAAAABgBQAAAAAAgBQAAAAAAAAQABgBAAAAIADgBIAGAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAIADADIA2BTIAAhTQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAQAAAAABAAIAHAAIADABQAAAAABABQAAAAAAAAQAAABAAAAQAAABABAAIAABtQgBAAAAABQAAAAAAABQAAAAAAAAQgBABAAAAIgDACg");
	this.shape_6.setTransform(29.75,63.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAtA8QgFAAgCgEIgJgYIg5AAIgJAYQgCAEgFAAIgGAAIgDgBQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIABgDIAqhqQACgGAFABIAKAAQAFgBACAGIApBqIABADIgBADIgCABgAAYARIgYg7IgXA7IAvAAg");
	this.shape_7.setTransform(18.05,63.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgDA8QgGAAgDgIIgkhpIgBgCIABgCIADgBIAGAAQAGgBABAFIAgBgIAghgQACgFAGABIAGAAIACABIABACIAAACIglBpQgBAEgCACQgDABgDABg");
	this.shape_8.setTransform(6.85,63.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgDA8IgDgCQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAhtQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAIADgBIAGAAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAIAABtQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBABg");
	this.shape_9.setTransform(-0.875,63.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgpA8IgDgCQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAhtQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAIADgBIAnAAQANgBALAGQALAFAHALQAGAKAAAPIAAAMIAAAOQAAANgGALQgGAKgLAGQgLAFgNABgAgdAsIAcAAQAQAAAHgJQAIgIAAgOIAAgNIAAgMQAAgNgIgKQgIgIgQAAIgbAAg");
	this.shape_10.setTransform(-8.725,63.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgYA3QgLgGgFgKQgGgLAAgNIAAgPIAAgOQAAgNAGgLQAFgKALgGQAKgGAOAAQAOAAALAGQAKAGAGAKQAFALABANIAAAOIAAAPQgBANgFALQgGAKgKAGQgLAGgOAAQgOAAgKgGgAgVglQgIAIgBAQIAAANIAAAOQABAQAIAIQAIAIANAAQANAAAJgIQAIgIABgQIAAgOIAAgNQgBgQgIgIQgJgIgNAAQgNAAgIAIg");
	this.shape_11.setTransform(-24.575,63.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgiAvQgLgNAAgWIAAhDQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgBABAAIADgBIAHAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAIABADIAABEQAAARAIAIQAIAIANAAQAOAAAIgIQAIgIAAgRIAAhEQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAIADgBIAHAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABQABAAAAAAQAAABAAAAIAABDQAAAWgMANQgLANgXAAQgWAAgMgNg");
	this.shape_12.setTransform(-36.225,63.875);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgDA8QAAgBAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBgDIAAhiIggAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBgBIAAgDIAAgGIAAgDQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAIBOAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQAAABAAAAQABABAAAAIAAAGQAAAAgBABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgfAAIAABiQAAAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAIgEACg");
	this.shape_13.setTransform(-46.95,63.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgiA8IgDgCQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAhtQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAIADgBIAHAAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAIAABiIA5AAIADABQAAABAAAAQABABAAAAQAAABAAAAQAAAAAAABIAAAGQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAIgDACg");
	this.shape_14.setTransform(-60.125,63.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgDA8IgDgCQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAhtQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAIADgBIAGAAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAIAABtQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBABg");
	this.shape_15.setTransform(-67.725,63.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAhA8QgFgBgCgEIgZgrIgcAAIAAArQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBABIgHAAIgDgCQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAhtQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAIADgBIApAAQARgBAMAKQAMAIAAASQAAANgHAIQgHAHgLAEIAaAtIAAACIgBADIgCABgAgbgDIAcAAQAZAAAAgUQAAgLgGgFQgHgEgMAAIgcAAg");
	this.shape_16.setTransform(-79.275,63.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgiA8IgDgCQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAhtQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBAAAAIADgBIBDAAQAAAAABAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAAAIAAAGQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAIg2AAIAAAjIAyAAIAEACIABADIAAAGIgBACIgEACIgyAAIAAAlIA3AAIADABQABABAAAAQAAABABAAQAAABAAAAQAAAAAAABIAAAGQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAIgDACg");
	this.shape_17.setTransform(-89.85,63.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgnA8IgDgCQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAhtQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAIADgBIAqAAQASgBAMAKQALAJAAASQAAALgFAJQgGAHgJAEQgJAEgMABIgeAAIAAApQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBABgAgbgBIAdAAQANAAAHgFQAGgFAAgLQAAgVgaAAIgdAAg");
	this.shape_18.setTransform(-100.175,63.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AhVDpQgzgbgdgvQgdgugBg7IgrAAQgJAAgFgGQgGgGAAgHIAAhEQAAgJAGgFQAFgGAJAAIArAAQABg6AdgvQAdgvAzgaQAzgbBAAAQA6AAA1AWQA0AYAhAnQAgAoABAwQAAAHgEAEQgGAGgGgBIheAAQgLAAgEgDIgKgSQgNgagTgNQgVgOgpAAQgrAAgYAZQgYAZgBAoIBoAAQAIAAAGAGQAFAFAAAJIAABEQAAAHgFAGQgGAGgIAAIhoAAQABAoAYAZQAYAZArAAQApAAAVgOQATgNANgaIAKgRQAEgEALAAIBeAAQAGAAAGAEQAEAFAAAGQgBAxggAnQghAog0AXQg1AXg6AAQhAAAgzgag");
	this.shape_19.setTransform(80.1,15.95);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AiZDMQgzg2gFhWIgCg/IAChAQAFhWAzg3QA0g2BlAAQBmAAA0A2QAzA3AFBWIACBAIgCA/QgFBWgzA2Qg0A3hmAAQhlAAg0g3gAg5h5QgRAWgCAnIgCA8IACA8QABAoASAWQASAWAnAAQAoAAASgWQASgWABgoIACg8IgCg8QgCgngSgWQgRgWgoAAQgnAAgSAWg");
	this.shape_20.setTransform(12.225,15.95);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AiZDMQgzg2gFhWIgCg/IAChAQAFhWAzg3QA0g2BlAAQBmAAA0A2QAzA3AFBWIACBAIgCA/QgFBWgzA2Qg0A3hmAAQhlAAg0g3gAg5h5QgRAWgCAnIgCA8IACA8QABAoASAWQASAWAnAAQAoAAASgWQASgWABgoIACg8IgCg8QgCgngSgWQgRgWgoAAQgnAAgSAWg");
	this.shape_21.setTransform(-37.275,15.95);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AhtDrQgwgVgZgkQgZgjgBgoQAAgGAEgFQAFgFAGAAIBcAAQAQAAAKAMQAPATAQAMQAPALAdgBQAgAAAWgQQAWgQAAgeQAAgZgUgPQgTgQghAAIgSADIgWAJIgTAGIhxAAQgIAAgGgFQgFgGAAgIIAWkAQABgIAFgFQAFgHAJAAIEzAAQAHAAAGAHQAGAFAAAIIAABNQAAAHgGAGQgGAFgHAAIjRAAIgFBAQAegQAkAAQA4AAAtAVQAsATAZAnQAZAlAAA2QAAA4gbAoQgbAogwAVQgvAVg8gBQg/AAgugUg");
	this.shape_22.setTransform(-85.65,16.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AheC8QgogVgWgjQgWgkgCgsIgBgzIABgzQACgtAWgjQAWgkAogVQAogVA2AAQA3AAAoAVQAoAVAWAkQAWAjACAtIABAzIgBAzQgCAsgWAkQgWAjgoAVQgoAVg3AAQg2AAgogVgAgzhhQgTATgDAeIgBAwIABAxQADAfATASQASASAhAAQAiAAATgSQASgSADgfIABgxIgBgwQgDgegSgTQgTgSgiAAQghAAgSASg");
	this.shape_23.setTransform(88.375,-47.225);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("ABuDLQgGAAgFgFQgFgFABgFIAAi/Ig3BeIgJAKQgFAFgIAAIgkAAQgHAAgFgFIgJgKIg2heIAAC/QAAAFgFAFQgFAFgGAAIhMAAQgGAAgFgFQgFgFAAgFIAAl3QAAgGAFgFQAFgEAGAAIBDAAQARAAAIAPIBdChIBeihQAJgPAQAAIBDAAQAGAAAFAEQAFAFAAAGIAAF3QAAAFgFAFQgFAFgGAAg");
	this.shape_24.setTransform(43.35,-47.2);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AglDLQgGAAgFgFQgFgFAAgFIAAl3QAAgGAFgFQAFgEAGAAIBLAAQAGAAAFAEQAFAFAAAGIAAF3QAAAFgFAFQgFAFgGAAg");
	this.shape_25.setTransform(9.675,-47.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("ABeDLQgJAAgGgEIgJgKIiEjFIAADEQABAFgFAFQgFAFgGAAIhMAAQgHAAgEgFQgFgFAAgFIAAl3QAAgGAFgFQAEgEAHAAIA8AAQAJAAAGAEIAJAJICEDFIAAjDQAAgGAFgFQAEgEAGAAIBNAAQAGAAAFAEQAEAFAAAGIAAF3QAAAFgEAFQgFAFgGAAg");
	this.shape_26.setTransform(-20.8,-47.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AglDLQgGAAgFgFQgFgFAAgFIAAl3QAAgGAFgFQAFgEAGAAIBLAAQAGAAAFAEQAFAFAAAGIAAF3QAAAFgFAFQgFAFgGAAg");
	this.shape_27.setTransform(-51.275,-47.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("ABuDLQgGAAgFgFQgFgFABgFIAAi/Ig3BeIgJAKQgFAFgIAAIgkAAQgHAAgFgFIgJgKIg2heIAAC/QAAAFgFAFQgFAFgGAAIhMAAQgGAAgFgFQgFgFAAgFIAAl3QAAgGAFgFQAFgEAGAAIBDAAQARAAAIAPIBdChIBeihQAJgPAQAAIBDAAQAGAAAFAEQAFAFAAAGIAAF3QAAAFgFAFQgFAFgGAAg");
	this.shape_28.setTransform(-84.9,-47.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#59828C").s().p("AwYQaQj7AAAAj9IAA45QAAj9D7AAMAgxAAAQAzAAApAKIAdAAIAAAKQCCAzAAC2IAAY5QAAD9j7AAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.tx2, new cjs.Rectangle(-130,-105,260,210), null);


(lib.tx1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgTAjQgGAAgFgEQgEgFAAgGIAAgnQAAgGAEgFQAFgEAGAAIAmAAQAHAAAEAEQAFAFAAAGIAAAnQAAAGgFAFQgEAEgHAAg");
	this.shape.setTransform(101.375,63.45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACZDLQgRAAgFgOIgfhOIjIAAIgeBOQgFAOgSAAIgVAAQgFAAgEgEQgEgEAAgFIADgIICOltQAHgTATAAIAhAAQATAAAHATICPFtIABAIQAAAFgDAEQgEAEgFAAgABQA7IhQjOIhQDOICgAAg");
	this.shape_1.setTransform(74.5,46.65);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgLDLQgGAAgFgEQgFgFABgGIAAl3QgBgGAFgEQAFgFAGAAIAWAAQAHAAAFAFQAEAEABAGIAAF3QgBAGgEAFQgFAEgHAAg");
	this.shape_2.setTransform(47.1,46.65);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ABxDLQgQAAgJgPIhUiVIhjAAIAACVQAAAGgEAFQgFAEgHAAIgXAAQgHAAgEgEQgFgFAAgGIAAl3QAAgGAFgEQAEgFAHAAICLAAQA9AAAnAeQAoAeAAA8QAAAtgXAdQgWAbgnAMIBYCYIACAHQAAAFgEAEQgEAEgFAAgAhfgMIBhAAQBYAAAAhGQAAgkgWgQQgWgQgsAAIhhAAg");
	this.shape_3.setTransform(21.675,46.65);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhUC8QgkgVgTgjQgTgkgBgsIgBg0IABgyQABgtATgjQASgkAkgVQAkgVAxAAQAxAAAkAVQAkAVATAkQASAjACAtIABAyIgBA0QgCAsgTAkQgTAjgjAVQgkAVgxAAQgxAAgjgVgAhKiAQgcAbgCA1IgBAwIABAxQACA1AcAcQAcAbAuAAQAuAAAcgbQAdgcACg1IABgxIgBgwQgCg1gdgbQgcgbguAAQguAAgcAbg");
	this.shape_4.setTransform(-17.825,46.625);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgLDLQgHAAgEgEQgEgFgBgGIAAlSIhsAAQgGAAgFgEQgFgFAAgHIAAgVQAAgGAFgEQAFgFAGAAIEPAAQAGAAAFAFQAEAEAAAGIAAAVQAAAHgEAFQgFAEgGAAIhtAAIAAFSQABAGgFAFQgFAEgGAAg");
	this.shape_5.setTransform(-53.85,46.65);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhODBQgjgQgUgaQgVgZgBgZQAAgFAEgEQAEgEAFAAIAYAAIAKADIAIAKQAJAVAZASQAYARAqAAQAqAAAdgSQAegTAAgdQAAgTgQgNQgPgNgbgKIhNgWQg4gOgZgbQgZgbAAgpQAAgeAPgaQAQgZAfgQQAggQAsAAQArAAAhARQAhASASAZQASAZABAVQABAFgEADQgEAEgFAAIgYAAIgLgDIgHgJQgKgTgXgRQgWgRglAAQgjAAgYAPQgYAQAAAdQAAAUAMAMQAMANAYAJQAYAIAwANQBCASAbAYQAcAZAAAsQAAAjgUAaQgTAbgkAPQgjAPguAAQgqAAgkgQg");
	this.shape_6.setTransform(-88.375,46.625);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AA+BTQgHAAgCgHIgMgfIhRAAIgMAfQgCAHgIAAIgIAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAgDIA6iUQADgIAIABIANAAQAIgBADAIIA5CUIABADQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAABgBAAgAAhAYIghhUIggBUIBBAAg");
	this.shape_7.setTransform(97.025,6.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAuBTQgHgBgDgGIgig8IgoAAIAAA8QAAABAAAAQAAABAAAAQgBABAAAAQAAABgBABQAAAAgBAAQAAABgBAAQAAAAgBAAQgBABAAAAIgKAAQgBAAAAgBQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAiYQAAAAAAgBQAAAAAAgBQAAAAABgBQAAgBAAAAQABAAAAgBQABAAAAAAQABAAABAAQAAAAABAAIA4AAQAZAAAQAMQAQAMAAAYQAAATgJALQgJALgQAEIAkA+IAAADQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAABgBAAgAgmgFIAnAAQAjABAAgdQAAgOgJgHQgIgGgSAAIgnAAg");
	this.shape_8.setTransform(81.825,6.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgEBTQAAAAgBgBQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAiIIgsAAQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBgBgBQAAAAAAgBIAAgJQAAAAAAgBQABAAAAgBQAAAAAAgBQABgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAABAAIBtAAQABAAAAAAQABAAABAAQAAAAABAAQAAABABAAQAAAAABABQAAABAAAAQABABAAAAQAAABAAAAIAAAJQAAABAAAAQAAABgBABQAAAAAAABQgBAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAQAAABgBAAIgsAAIAACIQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBABQAAAAgBAAQAAABgBAAQAAAAgBAAQgBABAAAAg");
	this.shape_9.setTransform(66.975,6.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgvBTQgBAAAAgBQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAiYQAAAAAAgBQAAAAAAgBQAAAAABgBQAAgBAAAAQABAAAAgBQABAAAAAAQABAAABAAQAAAAABAAIAKAAQAAAAABAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQABABAAAAQAAABAAAAQAAABAAAAIAACKIBPAAQAAAAABAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQAAABABAAQAAABAAAAQAAABAAAAIAAAJQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBABQAAAAgBAAQAAABgBAAQAAAAgBAAQgBABAAAAg");
	this.shape_10.setTransform(54.375,6.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AA+BTQgHAAgCgHIgMgfIhRAAIgMAfQgCAHgIAAIgIAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAgDIA6iUQADgIAIABIANAAQAIgBADAIIA5CUIABADQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAABgBAAgAAhAYIghhUIggBUIBBAAg");
	this.shape_11.setTransform(38.925,6.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgBAaQgBAAAAAAQgBAAAAAAQgBgBgBAAQAAAAgBgBQgCgBAAgEIgEgkQgBgEACgCQACgCADAAIAMAAQAEAAABACQACACAAAEIgFAkQAAAEgCABQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_12.setTransform(28.4083,0.625);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAvBTQgDAAgCgCIgFgGIhLhyIAABzQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAABQgBAAAAAAQgBABAAAAQgBAAAAAAQgBABgBAAIgKAAQAAAAgBgBQAAAAgBAAQAAAAgBgBQgBAAAAAAQAAgBgBgBQAAAAAAgBQAAAAAAgBQgBAAAAgBIAAiYQAAAAABgBQAAAAAAgBQAAAAAAgBQABgBAAAAQAAAAABgBQABAAAAAAQABAAAAAAQABAAAAAAIAJAAQADAAACABIAEAFIBMByIAAhzQAAAAAAgBQAAAAAAgBQABAAAAgBQAAgBABAAQAAAAABgBQABAAAAAAQABAAAAAAQABAAAAAAIAKAAQABAAAAAAQABAAAAAAQABAAAAAAQABABABAAQAAAAAAABQABABAAAAQAAABAAAAQABABAAAAIAACYQAAABgBAAQAAABAAAAQAAABgBAAQAAABAAABQgBAAgBAAQAAABgBAAQAAAAgBAAQAAABgBAAg");
	this.shape_13.setTransform(17.7,6.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgvBCQgPgTAAgeIAAheQAAAAAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAQABgBAAAAQABAAABAAIAKAAQAAAAABAAQAAAAABABQAAAAABAAQABAAAAABQABAAAAABQAAAAABABQAAAAAAABQAAABAAAAIAABfQAAAXALALQAKAMATAAQAUAAAKgMQALgLAAgXIAAhfQAAAAAAgBQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBABAAQABAAAAAAQABgBAAAAQABAAAAAAIAKAAQABAAAAAAQABAAAAABQABAAAAAAQABAAABABQAAAAAAABQABAAAAABQAAAAAAABQABABAAAAIAABeQgBAegQATQgPASggAAQggAAgPgSg");
	this.shape_14.setTransform(1.3,6.625);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AA+BTQgHAAgCgHIgMgfIhRAAIgMAfQgCAHgIAAIgIAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAgDIA6iUQADgIAIABIANAAQAIgBADAIIA5CUIABADQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAABgBAAgAAhAYIghhUIggBUIBBAAg");
	this.shape_15.setTransform(-20.675,6.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgEBTQAAAAgBgBQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAiIIgsAAQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAgBAAAAQgBgBAAgBQAAAAAAgBIAAgJQAAAAAAgBQAAAAABgBQAAAAAAgBQABgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAABAAIBtAAQABAAAAAAQABAAABAAQAAAAABAAQAAABABAAQAAAAABABQAAABAAAAQABABAAAAQAAABAAAAIAAAJQAAABAAAAQAAABgBABQAAAAAAABQgBAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAQAAABgBAAIgsAAIAACIQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBABQAAAAgBAAQAAABgBAAQAAAAgBAAQgBABAAAAg");
	this.shape_16.setTransform(-35.375,6.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgEBTQAAAAgBgBQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAiIIgsAAQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAgBAAAAQgBgBAAgBQAAAAAAgBIAAgJQAAAAAAgBQAAAAABgBQAAAAAAgBQABgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAABAAIBtAAQABAAAAAAQABAAABAAQAAAAABAAQAAABABAAQAAAAABABQAAABAAAAQABABAAAAQAAABAAAAIAAAJQAAABAAAAQAAABgBABQAAAAAAABQgBAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAQAAABgBAAIgsAAIAACIQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBABQAAAAgBAAQAAABgBAAQAAAAgBAAQgBABAAAAg");
	this.shape_17.setTransform(-48.775,6.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgvBCQgPgTAAgeIAAheQAAAAAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQABAAAAAAQABgBAAAAQABAAAAAAIAKAAQABAAABAAQAAAAABABQAAAAABAAQAAAAABABQAAAAABABQAAAAABABQAAAAAAABQAAABAAAAIAABfQAAAXAKALQAMAMASAAQAUAAAKgMQALgLAAgXIAAhfQAAAAAAgBQAAgBABAAQAAgBAAAAQABgBAAAAQAAgBABAAQABAAAAAAQABgBAAAAQABAAAAAAIAKAAQABAAAAAAQABAAAAABQABAAAAAAQABAAABABQAAAAAAABQABAAAAABQAAAAAAABQABABAAAAIAABeQgBAegQATQgPASggAAQgfAAgQgSg");
	this.shape_18.setTransform(-63.7,6.625);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgEBTQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAiIIgsAAQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBgBgBQAAAAAAgBIAAgJQAAAAAAgBQABAAAAgBQAAAAAAgBQABgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAABAAIBtAAQABAAAAAAQABAAABAAQAAAAABAAQAAABABAAQAAAAABABQAAABAAAAQABABAAAAQAAABAAAAIAAAJQAAABAAAAQAAABgBABQAAAAAAABQgBAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAQAAABgBAAIgsAAIAACIQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBABQAAAAgBAAQAAABgBAAQAAAAgBAAQgBABAAAAg");
	this.shape_19.setTransform(-78.625,6.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgvBpQgBAAAAAAQgBAAAAAAQgBgBAAAAQgBAAgBgBQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAgBAAAAIAAiYQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBAAgBQABAAABAAQAAAAABgBQAAAAABAAQAAAAABAAIBcAAQABAAABAAQAAAAABAAQAAABABAAQAAAAABAAQAAABABABQAAAAAAABQABAAAAABQAAAAAAABIAAAJQAAAAAAABQAAABgBAAQAAABAAAAQgBABAAAAQgBABAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAIhLAAIAAAxIBHAAQAAAAABAAQAAAAABAAQAAABABAAQABAAAAAAQABABAAABQAAAAABABQAAAAAAABQAAAAAAABIAAAJQAAAAAAABQAAABAAAAQgBABAAAAQAAABgBAAQAAABgBAAQgBAAAAABQgBAAAAAAQgBAAAAAAIhHAAIAAA0IBNAAQABAAABAAQAAAAABAAQAAABABAAQAAAAABAAQAAABABABQAAAAAAABQABAAAAABQAAAAAAABIAAAJQAAAAAAABQAAAAgBABQAAAAAAABQgBABAAAAQgBABAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAgAgBhHIgGgBIgEgDIgagVIgCgDQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAAAAAQAAAAABgBQAAAAABAAQAAAAAAAAIATAAIAFAAIAEAFIARAVIABADQAAAEgDAAg");
	this.shape_20.setTransform(-97.6,4.25);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AguBGQgBAAAAAAQgBAAgBAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAIAAiBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAABAAQAAAAAAgBQABAAABAAQAAAAABAAIBcAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAIAAAWQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAIg9AAIAAAWIA4AAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAIACAEIAAAUQAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAIg4AAIAAAXIA+AAQABAAAAAAQABAAABAAQAAABAAAAQABAAAAAAQABABAAAAQAAABAAAAQABABAAAAQAAABAAAAIAAAWQAAAAAAABQAAAAgBABQAAAAAAABQAAAAgBAAQAAABgBAAQAAAAAAABQgBAAgBAAQAAAAgBAAg");
	this.shape_21.setTransform(99.825,-20.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAhBGQgEAAgBgCIgDgCIgthEIAABDQAAAAgBABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgaAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQgBgBAAAAIAAiBQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABgBQAAAAABAAQAAAAABAAIAUAAQAEAAACABIADADIAsBEIAAhDQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAABgBQAAAAAAAAQABAAAAgBQABAAAAAAQAAAAABAAIAbAAQAAAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAIAACBQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAAAAAg");
	this.shape_22.setTransform(85.9,-20.6);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AggBBQgOgHgHgMQgIgNAAgPIgBgSIABgRQAAgPAIgMQAHgNAOgHQAOgHASAAQATAAAOAHQAOAHAHANQAIAMAAAPIABARIgBASQAAAPgIANQgHAMgOAHQgOAHgTAAQgSAAgOgHgAgRggQgGAFgBALIgBAQIABARQABALAGAFQAGAHALAAQAMAAAGgHQAGgFABgLIABgRIgBgQQgBgLgGgFQgGgHgMAAQgLAAgGAHg");
	this.shape_23.setTransform(71.475,-20.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgMBGQgBAAAAAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAIAAiBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABgBQAAAAABAAQAAAAABAAIAZAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQABABAAAAIAACBQAAAAgBABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_24.setTransform(61.05,-20.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("Ag1BGQgBAAAAAAQAAAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIAAgUIAAgFIADgCIA/hLIg7AAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIAAgWQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAIBnAAQAAAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQAAABABAAQAAABABAAQAAABAAAAQAAABAAAAIAAAVQAAAEgDACIg/BLIA/AAQAAAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAIAAAWQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAAAAAg");
	this.shape_25.setTransform(51.15,-20.6);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAoBGQgDAAgCgCQgBAAAAAAQgBgBAAAAQAAgBAAAAQgBgBAAAAIgFgRIg1AAIgFARQAAAAgBABQAAAAAAABQAAAAgBABQAAAAgBAAQgCACgDAAIgZAAIgDgCQgBAAAAAAQAAAAAAgBQgBAAAAgBQAAAAAAAAIABgDIAsh9QABgDACgCQACgCAEAAIAfAAQAEAAACACIADAFIAsB9IABADQAAAAAAAAQAAABgBAAQAAABAAAAQAAAAgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAgAAQASIgQgwIgPAwIAfAAg");
	this.shape_26.setTransform(37.275,-20.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgMBGIgEgCQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAIAAhmIgkAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIAAgWQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAIBrAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAIAAAWQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAIgkAAIAABmQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_27.setTransform(23.8,-20.6);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgfBBQgOgHgHgNQgIgNAAgSIAAhPQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABgBIAEgBIAaAAQAAAAABAAQABAAAAAAQABABAAAAQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAIAABOQAAANAGAGQAHAHAKAAQAMAAAGgHQAGgGAAgNIAAhOQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAABAAQAAAAAAgBQABAAAAAAQABAAAAAAIAbAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAAAQABABAAAAQAAABAAAAQABABAAAAQAAABAAAAIAABPQAAASgIANQgHANgOAHQgOAGgSAAQgRAAgOgGg");
	this.shape_28.setTransform(10.175,-20.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgtBGQgBAAAAAAQgBAAgBAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAIAAiBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAABAAQAAAAAAgBQABAAABAAQAAAAABAAIAaAAQAAAAABAAQABAAAAAAQABABAAAAQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAIAABmIA8AAIAEABQABABAAAAQAAABAAAAQABABAAAAQAAABAAAAIAAAWQAAAAAAABQAAAAgBABQAAAAAAABQAAAAgBAAIgEACg");
	this.shape_29.setTransform(-2.625,-20.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AAoBGQgDAAgCgCQgBAAAAAAQgBgBAAAAQAAgBAAAAQgBgBAAAAIgFgRIg1AAIgFARQAAAAgBABQAAAAAAABQAAAAgBABQAAAAgBAAQgCACgDAAIgZAAIgDgCQgBAAAAAAQAAAAAAgBQgBAAAAgBQAAAAAAAAIABgDIAsh9QABgDACgCQACgCAEAAIAfAAQAEAAACACIADAFIAsB9IABADQAAAAAAAAQAAABgBAAQAAABAAAAQAAAAgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAgAAQASIgQgwIgPAwIAfAAg");
	this.shape_30.setTransform(-16.375,-20.6);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgMBGQgIAAgDgIIgph8IAAgDIABgDQAAAAABAAQAAAAAAgBQABAAAAAAQABAAAAAAIAZAAQAEAAACABIACAEIAbBXIAchXQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAgBQACgBADAAIAaAAIADABQAAABAAAAQABAAAAABQAAAAAAABQAAAAAAAAIgBADIgoB8QgDAIgIAAg");
	this.shape_31.setTransform(-30.475,-20.6);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAbBGQgDAAgCgCIgDgDIgVgrIgTAAIAAArQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAIgaAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAIAAiBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAABAAQAAAAABgBQAAAAABAAQAAAAABAAIA1AAQAbAAAOALQAPAMAAAXQAAAcgYALIAZAwIABACIgBACQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAgAgVgIIAWAAQATAAAAgPQAAgPgTAAIgWAAg");
	this.shape_32.setTransform(-44.075,-20.6);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AguBGQgBAAAAAAQgBAAgBAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAIAAiBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAABAAQAAAAAAgBQABAAABAAQAAAAABAAIBcAAQAAAAABAAQABAAAAAAQABABAAAAQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAIAAAWQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQgBAAAAAAIg9AAIAAAWIA4AAQABAAAAAAQABAAABAAQAAAAAAAAQABABAAAAIACAEIAAAUQAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAgBAAQAAAAgBAAIg4AAIAAAXIA+AAQABAAAAAAQABAAABAAQAAABAAAAQABAAAAAAQABABAAAAQAAABAAAAQABABAAAAQAAABAAAAIAAAWQAAAAAAABQAAAAgBABQAAAAAAABQAAAAgBAAQAAABgBAAQAAAAAAABQgBAAgBAAQAAAAgBAAg");
	this.shape_33.setTransform(-57.525,-20.6);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("Ag1BGQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIAAiBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAIA4AAQAaAAAPAMQAPAMAAAXQAAAWgPAMQgPAMgaAAIgYAAIAAApQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAgAgVgGIAXAAQAKAAAFgFQAFgDAAgIQAAgIgFgEQgFgEgKAAIgXAAg");
	this.shape_34.setTransform(-70.6,-20.6);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgfBBQgOgHgHgNQgIgNAAgSIAAhPQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABgBIAEgBIAaAAQAAAAABAAQABAAAAAAQABABAAAAQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAIAABOQAAANAGAGQAHAHAKAAQAMAAAGgHQAGgGAAgNIAAhOQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAABAAQAAAAAAgBQABAAAAAAQABAAAAAAIAbAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAAAQABABAAAAQAAABAAAAQABABAAAAQAAABAAAAIAABPQAAASgIANQgHANgOAHQgOAGgSAAQgRAAgOgGg");
	this.shape_35.setTransform(-85.225,-20.5);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgeBCQgOgGgIgKQgIgJgBgLIABgCIADgCIAbAAQAEAAADADIADADQADADAFADQAGACAGAAQAZAAAAgKQAAgEgEgDIgKgDIgTgFIgJgCQgVgEgJgKQgKgJAAgSQAAgLAHgLQAHgJANgGQANgGARAAQAPAAANAGQAOAGAHAJQAIAJABAJIgCADIgDACIgaAAIgEgBIgEgDIgCgCQgDgDgEgBQgFgCgFAAQgJAAgFACQgGADAAAFQAAAEAEACQADADAHABIAYAGQAWAEALAKQALAJAAATQAAANgIAJQgIALgOAEQgOAGgSAAQgQAAgOgGg");
	this.shape_36.setTransform(-99.275,-20.6);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("ABqCMQgMAAgEgKIgUg2IiKAAIgVA2QgEAKgMAAIgPAAQgDAAgDgCQgCgDAAgEIABgFIBij8QAFgNANAAIAXAAQANAAAFANIBiD8IABAFQAAAEgCADQgDACgDAAgAA3ApIg3iOIg2COIBtAAg");
	this.shape_37.setTransform(93.775,-53.9);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("ABOCMQgLAAgHgLIg5hmIhEAAIAABmQAAAEgDAEQgDADgFAAIgRAAQgEAAgDgDQgDgEAAgEIAAkBQAAgFADgDQADgDAEAAIBhAAQAqAAAbAUQAbAVAAApQAAAggPAUQgQASgbAIIA8BqIACAEQAAAEgCADQgDACgEAAgAhBgIIBDAAQA8AAAAgxQAAgYgPgLQgPgLgeAAIhDAAg");
	this.shape_38.setTransform(68.05,-53.9);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgHCMQgFAAgDgDQgDgEAAgEIAAjoIhLAAQgEAAgDgDQgEgEAAgEIAAgOQAAgFAEgDQADgDAEAAIC7AAQAEAAADADQAEADAAAFIAAAOQAAAEgEAEQgDADgEAAIhLAAIAADoQAAAEgDAEQgDADgFAAg");
	this.shape_39.setTransform(42.825,-53.9);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("Ag1CFQgZgMgOgRQgOgRAAgSQAAgDADgCQACgEAEAAIAQAAIAHADIAFAGQAHAPAQAMQASAMAcAAQAdAAAUgNQAVgMgBgUQAAgOgKgJQgKgJgTgGIg1gPQgngKgRgTQgRgTAAgcQgBgUALgSQAMgRAVgLQAWgLAeAAQAdAAAXAMQAXALAMASQANARABAPQAAADgDACQgDAEgDAAIgQAAIgIgDIgFgGQgGgNgRgMQgPgMgZAAQgYAAgQALQgRALAAATQAAAOAIAJQAIAJARAFQAQAGAhAJQAtAMATARQAUARAAAfQAAAXgOATQgNASgZAKQgYALggAAQgcAAgZgLg");
	this.shape_40.setTransform(19,-53.9);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("Ag6CBQgZgOgMgYQgOgZgBgeIAAgkIAAgiQABgfAOgYQANgaAYgOQAZgOAhAAQAiAAAYAOQAZAOANAaQANAYABAfIABAiIgBAkQgBAegNAZQgNAYgZAOQgYAPgiAAQghAAgZgPgAgyhYQgUASgBAmIgBAgIABAhQABAmAUASQATATAfAAQAgAAATgTQAUgSACgmIAAghIAAggQgCgmgUgSQgTgTggAAQgfAAgTATg");
	this.shape_41.setTransform(-6.65,-53.9);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("ABQCMQgFAAgEgDIgHgJIiBjDIAADEQAAAEgEAEQgDADgEAAIgRAAQgEAAgDgDQgDgEAAgEIAAkBQAAgFADgDQADgDAEAAIAOAAQAGAAADADIAHAJICCDCIAAjDQAAgFADgDQADgDAEAAIARAAQAEAAADADQADADAAAFIAAEBQAAAEgDAEQgDADgEAAg");
	this.shape_42.setTransform(-33.975,-53.9);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("ABqCMQgMAAgEgKIgUg2IiKAAIgVA2QgEAKgMAAIgPAAQgDAAgDgCQgCgDAAgEIABgFIBij8QAFgNANAAIAXAAQANAAAFANIBiD8IABAFQAAAEgCADQgDACgDAAgAA3ApIg3iOIg2COIBtAAg");
	this.shape_43.setTransform(-71.225,-53.9);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AhRCMQgEAAgDgDQgDgEAAgEIAAkBQAAgFADgDQADgDAEAAIARAAQAEAAADADQAEADAAAFIAADoICGAAQAFAAADADQADAEAAAEIAAAOQAAAEgDAEQgDADgFAAg");
	this.shape_44.setTransform(-94.725,-53.9);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("rgba(0,57,70,0.8)").s().p("AwYQaQj7AAAAj9IAAyDIAAm2QAAj9D7AAMAgxAAAQD7AAAAD9IAAG2IAASDQAAD9j7AAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.tx1, new cjs.Rectangle(-130,-105,260,210), null);


(lib.txfine = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiMC7QgwgxgEhOIgChBIACg0QAEhPAwgyQAxgyBbAAQBcAAAxAyQAwAxAEBQIACA0IgCBBQgEBOgwAxQgxAyhcAAQhbAAgxgygAhJh/QgcAagDAuIgBA3IABA3QADAwAcAaQAcAZAtAAQAuAAAcgZQAcgaACgwIACg3IgCg3QgCgugcgaQgcgagugBQgtABgcAag");
	this.shape.setTransform(182.275,39.85);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgaDmQgHAAgFgFQgFgGAAgGIAAmoQAAgIAFgFQAFgFAHAAIA1AAQAHAAAFAFQAFAFAAAIIAAGoQAAAGgFAGQgFAFgHAAg");
	this.shape_1.setTransform(149.925,39.85);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AiRC8QgygwgDhTIgBg6IABg6QADhRAygwQA0gwBdAAQBGAAArAXQArAWASAeQASAeADAZQAAAJgFAEQgFAGgIgBIg2AAQgMABgFgMQgeg2hMgBQgwABgdAaQgfAbgCAtIAAA1IAAA1QACA0AdAaQAeAZAxAAQBvAAAAhlIAAgFIhQAAQgHAAgGgGQgFgEAAgIIAAguQAAgHAFgFQAGgFAHAAICXAAQAIAAAFAFQAFAFAAAHIAABHQAAA2gXApQgWAoguAYQgsAXhBAAQhfAAgygxg");
	this.shape_2.setTransform(117.25,39.85);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AiRC8QgygwgDhTIgBg6IABg6QADhRAygwQAzgwBeAAQBFAAArAXQArAWATAeQATAeABAZQABAJgFAEQgFAGgIgBIg2AAQgMABgFgMQgdg2hNgBQgvABgeAaQgfAbgCAtIAAA1IAAA1QACA0AeAaQAcAZAyAAQBvAAAAhlIAAgFIhQAAQgIAAgEgGQgGgEAAgIIAAguQAAgHAGgFQAEgFAIAAICXAAQAIAAAEAFQAGAFAAAHIAABHQAAA2gXApQgXAogsAYQguAXhAAAQhfAAgygxg");
	this.shape_3.setTransform(70.75,39.85);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("ACeDmQgUAAgGgQIgchJIjPAAIgcBJQgGAQgUAAIgvAAQgHAAgFgFQgGgGAAgGIABgGIChmeQAEgMAFgFQAGgFAKAAIBHAAQAKAAAGAFQAFAFAEAMIChGeIABAGQAAAGgFAGQgGAFgHAAgABIA7IhIi7IhHC7ICPAAg");
	this.shape_4.setTransform(24.225,39.85);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("ACRDmQgIAAgFgFQgFgGAAgGIAAkBIhWCTQgKAQgOABIghAAQgOgBgLgQIhViTIAAEBQAAAGgFAGQgGAFgGAAIg2AAQgHAAgGgFQgEgGAAgGIAAmoQAAgIAEgFQAGgFAHAAIAtAAQALAAAFAFIAMANIB8DYIB9jYIALgNQAGgFALAAIAtAAQAHAAAFAFQAGAFAAAIIAAGoQAAAGgGAGQgFAFgHAAg");
	this.shape_5.setTransform(-25.55,39.85);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhdDYQgngRgUgeQgTgdgCgkQgBgIAFgFQAGgFAIAAIA1AAQAHAAAFAEQAFAFACAHQAIAcAWAKQAWALAhAAQAlAAAXgVQAYgUAAgjQAAgegYgTQgXgUglgBQgTAAgMAEIgXAJIgLAFIgMACIg9AAQgHAAgFgFQgFgFAAgIIATjeQAAgHAGgFQAFgFAHAAID2AAQAIAAAFAFQAFAFAAAHIAAAvQAAAHgFAGQgFAFgIAAIi3AAIgIBUQAagKAlAAQAyAAAnASQAnARAWAjQAWAhAAAwQAABQgwAnQgwAnhMAAQg5AAgmgRg");
	this.shape_6.setTransform(-87.3273,40.175);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AiFDmQgHAAgFgFQgGgGAAgGIAAmoQAAgIAGgFQAFgFAHAAIAbAAQAHAAAGAFQAFAFAAAIIAAF+IDeAAQAHAAAGAFQAEAFAAAHIAAAZQAAAGgEAGQgGAFgHAAg");
	this.shape_7.setTransform(-139.7,39.85);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("ACuDmQgUAAgGgQIgihYIjjAAIgiBYQgGAQgUAAIgYAAQgGAAgEgEQgFgEAAgHIADgJIChmeQAIgVAWAAIAmAAQAVAAAJAVICgGeIADAJQAAAHgFAEQgEAEgGAAgABbBDIhbjpIhaDpIC1AAg");
	this.shape_8.setTransform(-182.825,39.85);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AhgDVQgogYgVgoQgWgpgCgxIAAg7IAAg5QACgzAVgoQAVgoApgYQApgYA3ABQA3gBApAYQApAYAVAoQAWAoABAzIABA5IgBA7QgCAxgVApQgWAogoAYQgpAXg3AAQg3AAgpgXgAhUiSQggAggDA7IAAA3IAAA3QADA8AgAfQAgAgA0AAQA0AAAgggQAhgfACg8IABg3IgBg3QgCg7ghggQgggfg0AAQg0AAggAfg");
	this.shape_9.setTransform(141.525,-40.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("ACDDmQgIAAgHgFIgMgOIjUlBIAAFDQAAAGgFAGQgGAFgHAAIgbAAQgHAAgFgFQgGgGAAgGIAAmoQAAgIAGgFQAFgFAHAAIAXAAQAJAAAFAFIANAPIDVFAIAAlCQAAgIAEgFQAFgFAIAAIAbAAQAHAAAGAFQAEAFAAAIIAAGoQAAAGgEAGQgGAFgHAAg");
	this.shape_10.setTransform(96.65,-40.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgNDmQgHAAgFgFQgFgGAAgGIAAmoQAAgIAFgFQAFgFAHAAIAaAAQAIAAAFAFQAFAFAAAIIAAGoQAAAGgFAGQgFAFgIAAg");
	this.shape_11.setTransform(65.125,-40.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AiCDmQgHAAgFgFQgFgGAAgGIAAmoQAAgIAFgFQAFgFAHAAIEEAAQAIAAAFAFQAFAFAAAIIAAAXQAAAHgFAGQgFAFgIAAIjXAAIAACYIDKAAQAIAAAFAFQAFAGAAAGIAAAYQAAAGgFAGQgFAFgIAAIjKAAIAACtQAAAGgFAGQgFAFgIAAg");
	this.shape_12.setTransform(38.925,-40.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AhgDVQgogYgVgoQgWgpgCgxIAAg7IAAg5QACgzAVgoQAVgoApgYQApgYA3ABQA3gBApAYQApAYAVAoQAWAoABAzIABA5IgBA7QgCAxgVApQgWAogoAYQgpAXg3AAQg3AAgpgXgAhUiSQggAggDA7IAAA3IAAA3QADA8AgAfQAgAgA0AAQA0AAAgggQAhgfACg8IABg3IgBg3QgCg7ghggQgggfg0AAQg0AAggAfg");
	this.shape_13.setTransform(-19.575,-40.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AiFDmQgHAAgFgFQgFgGgBgGIAAmoQABgIAFgFQAFgFAHAAIAbAAQAHAAAFAFQAGAFAAAIIAAF+IDeAAQAHAAAFAFQAGAFAAAHIAAAZQAAAGgGAGQgFAFgHAAg");
	this.shape_14.setTransform(-58.1,-40.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhgDVQgogYgVgoQgWgpgCgxIAAg7IAAg5QACgzAVgoQAVgoApgYQApgYA3ABQA3gBApAYQApAYAVAoQAWAoABAzIABA5IgBA7QgCAxgVApQgWAogoAYQgpAXg3AAQg3AAgpgXgAhUiSQggAggDA7IAAA3IAAA3QADA8AgAfQAgAgA0AAQA0AAAgggQAhgfACg8IABg3IgBg3QgCg7ghggQgggfg0AAQg0AAggAfg");
	this.shape_15.setTransform(-100.875,-40.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AhYDaQgpgSgWgdQgXgdgBgbQAAgGADgFQAFgEAGgBIAbAAIAMAEIAIAMQALAXAcAUQAcAUAvAAQAwAAAhgVQAhgVAAghQAAgWgRgPQgSgPgegKIhXgZQhBgQgcgfQgcgfAAguQAAgiARgdQATgdAjgSQAkgRAxAAQAxAAAmASQAlAUAVAcQAUAcABAYQABAGgFAEQgEAFgGAAIgbAAIgMgEIgJgLQgKgUgagTQgagVgqAAQgnAAgbASQgcASAAAhQAAAWAOAOQANAOAbALQAbAKA3AOQBLAUAfAcQAfAcABAyQAAAngXAeQgVAegpASQgoAQg0AAQgwAAgogSg");
	this.shape_16.setTransform(-143.4,-40.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.txfine, new cjs.Rectangle(-208.1,-82.1,416.2,164.2), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag/BfQgZgXAAggQAAgZAPgUQAMgQAPgJQgBAAgDgGQgEgGAAgHQAAgMAOgJQAMgJAOAAQAHAAALAGIAAgIIAIAAIAAA4IgIAAIAAgaQgBgHgFgHQgEgGgJgBQgHAAgHAFQgHAFgBAIQAAAGAFAFIAIAHIgBAHQgKABgJAHQgKAGgGALQgHAIgCAJQgEAJAAALQABAgAXAVQAWAVAbAAQAVAAATgPQAWgSAAgbQAAgUgKgQQgMgTgWgBQgPAAgMANQgLAOgBAPQAAAPAJAKQAJAKAHAAQAHgBgBgHIAHAAQABAIgEAFQgGAFgIAAQgNAAgJgIQgMgLAAgSQAAgdAggXQASgNAlgQQAZgKAHgGIADgEQACgEgEgCIAAgGQAGgBAFAEQAFADgCAIQgEAJgKAJQgKAHgSAIIgXAHQATAHALAMQAMANAAAWQAAAlgdAXQgbAVgcAAQggAAgYgWgAJ0BOIAAh4IAbAAIAAB4gAJEBOIgyhQIgBAAIAABQIgYAAIAAh4IAaAAIAyBRIABAAIAAhRIAZAAIAAB4gAHUBOIgJgbIgtAAIgKAbIgbAAIAvh4IAbAAIAtB4gAGkAfIAgAAIgPgrIgBAAgAE/BOIgnh4IAcAAIAbBUIAbhUIAcAAIgpB4gAD1BOIAAh4IAbAAIAAB4gAB5BOIAAh4IA0AAQALAAAKAEQALADAHAIQAIAIAEAKQAEALAAAPQAAAMgEAMQgDAMgHAHQgHAJgKAFQgLAEgNAAgACUA4IAXAAQAGAAAGgCQAFgCAEgEQAEgFADgGQADgIAAgJQAAgJgCgIQgCgGgEgGQgEgFgHgCQgHgEgKAAIgSAAgAiSBOIAAh4IAaAAIAAB4gAjCBOIgzhQIAAAAIAABQIgZAAIAAh4IAaAAIAzBRIAAAAIAAhRIAaAAIAAB4gAkzBOIgJgbIgtAAIgJAbIgbAAIAth4IAcAAIAtB4gAliAfIAgAAIgQgrgAnHBOIgoh4IAcAAIAbBUIAchUIAbAAIgpB4gAoSBOIAAh4IAaAAIAAB4gAqOBOIAAh4IA1AAQAKAAALAEQAKADAIAIQAHAIAEAKQAFALAAAPQAAANgEALQgDAMgIAHQgGAJgLAFQgKAEgNAAgApzA4IAXAAQAHAAAFgCQAGgCAEgEQAEgFACgGQADgIAAgJQAAgJgCgIQgCgGgEgGQgEgFgGgCQgIgEgJAAIgTAAgAFIg7IAAgHQACACAFgBQAKABABgIQgEAEgHAAQgGAAgEgEQgFgDAAgGIAAgVIAHAAIAAAVQAAAHAIAAQALAAAAgLIAAgRIAGAAIAAAdQAAAIgFADQgFADgHABIgHgBgAIMhJQgFgEAAgIIAAgcQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAAAAAIAFAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAAAcQABAFACADQADACAEAAQAEAAAEgCQACgDAAgFIAAgcQAAAAABgBQAAAAAAAAQAAAAAAAAQABAAAAAAIAFAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAcQAAAIgGAEQgEAGgIAAQgGAAgGgGgAKJhFQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgqQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIAEAAQABAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAqQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAgAJehFQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgDIACgCIAXghIgWAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAABAAIAeAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAAACIgBADIgYAgIAYAAQAAAAABABQAAAAAAAAQAAAAAAABQAAAAAAAAIAAADQAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAAAgAI0hFQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIAAgDIAAgCIAZghIgXAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBgBAAAAIAAgDQAAAAABgBQAAAAAAAAQAAAAAAAAQABAAAAAAIAeAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABABAAAAIAAACIgBADIgZAgIAYAAQAAAAABABQAAAAAAAAQAAAAAAABQABAAAAAAIAAADQAAAAgBABQAAAAAAAAQAAABAAAAQgBAAAAAAgAHqhFQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgmIgNAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAAAAAIAhAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAABIAAADQAAAAAAABQAAAAAAAAQAAAAAAAAQgBAAAAAAIgMAAIAAAmQAAAAgBABQAAAAAAAAQAAABAAAAQgBAAAAAAgAHPhFQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAAgPIgUAAIAAAPQAAAAgBAAQAAAAAAABQAAAAAAAAQgBAAAAAAIgEAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAAAIAAgeQAAgGAFgFQAFgFAIAAQAGAAAGAFQAFAFAAAGIAAAeQAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAgAG9hqQgDADAAADIAAAIIAUAAIAAgIQAAgDgEgDQgDgEgDAAQgFAAgCAEgAGjhFQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAAAIgYggIAAAgQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAAAAAIgFAAQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgqQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAAAAAIAEAAQAAAAABAAQAAAAABAAQAAAAAAAAQABABAAAAIAYAgIAAggQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAAAAAIAFAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABABAAAAIAAAqQAAAAgBABQAAAAAAAAQAAABAAAAQgBAAAAAAgAEehKIAAAEIgGAAIAAgsIAGAAIAAAOQAEgEAIAAQAIAAAFAFQAFAFAAAIQAAAHgFAEQgFAFgIABQgIAAgEgFgAEehWQAAAEADAEQADACAGAAQAGAAADgCQACgEAAgEQAAgFgCgEQgDgDgGAAQgMAAAAAMg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-65.5,-11.7,131,23.4), null);


(lib._img = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.instance = new lib.immagine();
	this.instance.parent = this;
	this.instance.setTransform(-250,-274.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib._img, new cjs.Rectangle(-250,-274.5,499,600), null);


(lib.icofurgone = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHhExQAEgXgEgYQgJg3guggQguggg3AKQg3AKggAuQggAtAKA3Im2AAQAFgXgFgYQgJg3guggQguggg3AKQg3AKggAuQggAuAKA2IgRAAQgVAAgPgPQgQgPAAgWIAAheIAvAAQAPAAAKgKQAKgKAAgPQAAgOgKgLQgKgKgPAAIgvAAIAAhGIAvAAQAPAAAKgKQAKgJAAgPQAAgOgKgLQgKgKgPAAIgvAAIAAhGIAuAAQAOAAALgKQAKgKAAgPQAAgOgKgLQgLgKgOAAIguAAIAAg+QAAgWAQgPQAPgPAVAAIKfAAQAOAAAKAGQALAHALAPICTDAIACACICNBDQAUAJASAqQAQAogBAbIAACWQAAAWgPAPQgPAPgWAAgAhwBlIAAAAQAAAGAEAFQAFAEAGAAIAJAAIAAACQAEgBABgFQABgGgGgBIgJAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAgCQAAgGgGgBQgHAAAAAHgAgnB2IACgBQAGgEgEgFQAAgCgDgCQgCgBgDAAIgWAAQgFAAgBAGQAAAGAGABIAWAAQABAAAAABQABAAAAAAQAAAAABAAQAAgBAAAAgAmZBuQgBAGAHABIAZAAQAFAAABgFQABgHgHgBIgXAAIgCAAQgFAAgBAGgAloBtQgBAHAHABIAIAAQAHAAAEgFQAFgEAAgHIAAgBQABgGgIgBQgGAAAAAHIAAABQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAIgIAAQgFABgBAFgAmfBCIAAAYQgBAHAHAAQAHAAAAgHIAAgYQAAgGgHAAQgGAAAAAGgAgoBCIAAAYQAAAGAGAAQAHAAAAgGIAAgWQAAgHgGAAIgBAAQgEAAgCAFgAkeBMQgBACACADQACACADAAIAYAAQAFgBABgFQABgGgHgBIgYAAQgGABAAAFgAlJBTIAYAAQAFAAABgFQABgHgHgBIgZAAIAAgSQAAgGgGAAQgHAAAAAGIAAAYQAAAHAGAAIAEgCQAAAAABAAQABABAAAAQABAAAAAAQABABAAAAgAiOBMIABACQABAFAFAAIAZAAIADgBIACAAQAGAAAAgHIAAgXQAAgHgGAAQgHAAAAAHIAAARIgXAAQgHAAAAAHgAi9BLQgBAHAHABIAYAAQAFgBABgFQAAgDgBgCQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIgYAAQgFAAgBAFgAjuBLQgBAHAHABIAYAAQAFAAABgGQAAgGgGgBIgYAAQgGAAAAAFgAmfATIAAAYQAAAGAGAAQAHAAAAgGIAAgYIABgBQgBgGgGAAQgHAAAAAHgAgoASIAAAYQAAAHAGAAQAHAAAAgHIAAgXQAAgHgHAAQgGAAAAAGgAlXAFIAAAYQAAAGAHAAQAGAAAAgGIAAgYQAAgGgGAAQgHAAAAAGgAhpgBQgHAAAAAFIAAAYQAAAHAHAAQAGAAAAgHIAAgYIABACIAAgCQAAgBAAAAQAAgBgBgBQAAAAAAgBQgBAAAAAAIgEgBIgBAAgAmfgcIAAAYQAAAGAHAAIAAgBQAFgBABgEIAAgYQAAgGgGgBQgHAAAAAHgAgogcIAAAYQAAAFAGAAQAHAAAAgFIAAgYQAAgHgHAAQgGAAAAAHgAiNgUQgBAGAHABIAaAAIAEABIAAACIACAAQAGgDgBgGIAAgXQAAgHgHAAQgHAAAAAHIAAAQIgXAAQgFAAgBAGgAlXgqIAAAZQAAAGAHAAQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAgBIADABIAYAAQAGgBAAgFQAAgCgCgDQAAAAAAgBQgBAAAAAAQgBAAgBgBQAAAAgBAAIgZAAIAAgQQABgHgIAAQgGAAAAAGgAi9gUQgBADACACQACACADABIAYAAQAFgBABgFQABgHgHgBIgYAAQgFABgBAFgAjugUQgBAHAHABIAYAAQAGgBAAgFQAAgHgGAAIgYAAQgGAAAAAFgAkegUQgBAHAHABIAYAAQAFAAABgGQABgGgHgBIgYAAQgFAAgBAFgAmmg9IAHADIAAAIQAAAHAHAAQAHAAAAgHIAAgFQgBgLgJgEIgFgCQgGgEgDAGIABAAQgEAFAGAEgAgZhJIgKAEQgFABAAAFIAAAMQAAAHAHAAQAGAAAAgHIAAgHIAIgDQAFgDgDgGQAAAAAAgBQAAAAgBgBQAAAAgBgBQAAAAgBAAIgCgBIgDABgAhpg5QAHAAAAgHIAAgYQAAgGgHgBQgHAAAAAHIAAAPIgXAAIAAACQgFABgBAFQgBACACADQACACADAAIAYAAIADAAgAlJg7IAYAAQAFgBABgFQABgGgHgBIgYAAIAAgRQAAgGgHgBQgHAAAAAHIAAAXQAAAHAHAAIADgBIAEABgAjuhDQgBAHAHABIAYAAQAFgBABgFQABgHgHgBIgYAAQgGABAAAFgAkehDQgBAHAGABIAZAAQAFgBABgFQAAgHgGgBIgZAAQgFABAAAFgAi9hDQgBAGAHABIAYAAQAEAAABgFQABgHgGgBIgZAAQgEABgBAFgAnChqIAAACQAAAOAIAKQADAGAGgEQAFgDgDgGQgFgHAAgKIAAgBQAAgHgHgBQgGAAgBAHgAAAhxQAAAAAAAAQAAABgBAAQAAAAgBAAQgBABAAAAQgCACAAADIAAACQgBAKgEAHIgBABQgDAFAGAEIAFAAQADgBAAgCIAAABQAIgLgBgPIAAgCQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBgBAAIgEgCIgBAAgAAsj7QgJAJAAAOIAABxQAAAOAJAKQAKAJAOAAIDAAAQAWAAAGgKIAAACQAGgKgNgSIhUhxQgNgQgJgGQgLgIgMAAIhUAAQgOAAgKAKgAhfiIQgLAJgDAOQgCAHAHABIABAAQAFgBACgEQACgKAIgHQAEgFgEgEQgCgDgDAAQgCAAgCADgAliiKQgEAFAEAFQAIAIACAJQACAFAFAAIACAAQAGgCgCgHQgDgNgKgKQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgDAAgDACgAmiiUQgNAGgIAKQgBABAAAAQAAAAgBAAQAAABAAAAQAAAAAAABQgEAGAHADQAGACADgGIAAAAQAGgHAKgFIACAAQAFgEgDgGQgCgDgDAAIgEABgAggiRQgCAGAGADIABABQAIADAHAIQAEAEAEgDQADgBABgDQAAgDgBgCQgJgLgMgGIgBAAIgDAAQgEAAgCAEgAmGiNQAKAAAIADQABAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAFAAACgFQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAgBgBAAQAAAAgBgBQgLgDgMAAIgDAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBAAgBABQgCACAAADIAAAAQABAHAGgBgAg/isIAAATIgKACQgHACADAGIAAACQACADAEAAIACAAQAJgEAMABIABAAQAFAAABgGQAAgHgGAAIgDAAIAAgRQAAgHgHAAQgGAAAAAGgAmHjAIAAAYQAAAHAGAAQAHAAAAgHIAAgYQAAgGgGAAQgHAAAAAGgAg/jZIAAAXQAAAHAHAAQAGAAAAgHIAAgXIABAAQAAgHgHAAQgHAAAAAHgAmEjxQgDAFAAAIIAAANQAAAHAGAAQAHAAAAgHIAAgNQAAgEACgDIABgBQACgGgGgDIgDgBQgDAAgDAFgAhYj6QgBAGAHABIAEAAQAHAAAFAGIACADQACACADgBQADAAACgDQADgFgFgEQgIgLgOAAIgEAAQgFAAgBAGgAiGj5QgBAGAGABIAYAAQAFAAABgFQABgHgHgBIgYAAQgFAAAAAGgAlyj5IABAAIAAAAQAAABAAAAQAAABAAABQABAAAAABQAAAAABABQAAAAABABQABAAAAAAQABAAAAAAQABAAAAAAIAXAAQAFAAABgFQABgHgHgBIgYAAQgGAAAAAHgAi2j6QAAAGAGABIAYAAQAFgBABgFQABgGgHgBIgYAAQgFABgBAFgAjkj6QgBACACADQACACADAAIAXAAQAFgBABgFQAAgGgGgBIgXAAQgFABgBAFgAkTj6QgBAGAHABIAXAAQAFgBABgFQABgGgHgBIgXAAQgFAAgBAGgAlCj6QgBAGAHABIAYAAQAFgBAAgFQABgCgCgDQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAIgYAAQgFAAgBAGg");
	this.shape.setTransform(11.7076,-1.9438,0.6996,0.6996);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AizAPQgHAAgEgEQgEgFAAgGQAAgFAEgFQAEgEAHAAIFnAAQAGAAAEAEQAFAFAAAFQAAAGgFAFQgEAEgGAAg");
	this.shape_1.setTransform(-37.0572,-12.8405,0.6996,0.6996);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ah8APQgGAAgFgFQgEgEAAgGQAAgGAEgEQAFgEAGAAID5AAQAGAAAEAEQAFAEAAAGQAAAGgFAEQgEAFgGAAg");
	this.shape_2.setTransform(-33.2092,-3.0457,0.6996,0.6996);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhZAPQgHAAgEgEQgEgFAAgGQAAgFAEgEQAEgFAHAAICzAAQAGAAAEAFQAFAEAAAFQAAAGgFAFQgEAEgGAAg");
	this.shape_3.setTransform(-30.7605,6.7491,0.6996,0.6996);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgLAQIALgbQABgFAGACIAAAAQAGACgCAGIgJAWg");
	this.shape_4.setTransform(27.1351,-9.5184,0.6996,0.6996);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgrAsQgSgSAAgaQAAgZASgSQASgSAZAAQAaAAASASQASASAAAZQAAAagSASQgSASgaAAQgZAAgSgSg");
	this.shape_5.setTransform(20.1551,-12.928,0.6996,0.6996);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag3A4QgXgXAAghQAAggAXgXQAXgXAgAAQAhAAAXAXQAXAXAAAgQAAAhgXAXQgXAXghAAQggAAgXgXg");
	this.shape_6.setTransform(-13.1123,17.7508,0.6996,0.6996);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag3A4QgXgXAAghQAAggAXgXQAXgXAgAAQAhAAAXAXQAXAXAAAgQAAAhgXAXQgXAXghAAQggAAgXgXg");
	this.shape_7.setTransform(36.0367,17.7508,0.6996,0.6996);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAAAIIAAgHIgHgDQgGgDAEgGQADgEAFACIADACQAKAFAAAKIAAAEQAAAHgGAAQgGAAAAgHg");
	this.shape_8.setTransform(38.7093,6.42,0.6996,0.6996);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.icofurgone, new cjs.Rectangle(-50.7,-23.3,101.4,46.6), null);


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#003946").s().p("AghguIBDAuIhDAvg");
	this.shape.setTransform(73.525,-2.475);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Livello_2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#003946").s().p("AgiAjQgOgOAAgVQAAgUAOgOQAOgOAUAAQAVAAAOAOQAOAOAAAUQAAAVgOAOQgOAOgVAAQgUAAgOgOgAgUgVQgIAJAAAMQAAANAIAJQAIAJAMAAQANAAAIgJQAIgJAAgNQAAgMgIgJQgIgJgNAAQgMAAgIAJg");
	this.shape_1.setTransform(57.275,-1.975);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#003946").s().p("AgJAvIAAhMIgcAAIAAgRIBLAAIAAARIgcAAIAABMg");
	this.shape_2.setTransform(47.975,-1.975);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#003946").s().p("AgJAvIAAhdIATAAIAABdg");
	this.shape_3.setTransform(42.15,-1.975);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#003946").s().p("AgmAvIAAhdIAwAAQANAAAIAHQAHAHAAAKQAAAIgFAGQgFAGgHABQAIABAFAGQAFAHAAAJQAAALgHAHQgHAHgNAAgAgSAeIAZAAQAFAAAEgDQADgDAAgFQAAgFgDgDQgEgDgFAAIgZAAgAgSgIIAYAAQAFAAADgDQADgDAAgFQAAgEgDgDQgDgDgFAAIgYAAg");
	this.shape_4.setTransform(35.875,-1.975);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#003946").s().p("AgfAlQgKgKAAgSIAAg4IAUAAIAAA3QAAALAFAFQAGAGAKABQALgBAFgGQAGgGAAgKIAAg3IAUAAIAAA3QAAATgKAKQgLALgVAAQgUAAgLgLg");
	this.shape_5.setTransform(26.125,-1.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#003946").s().p("AgmAiIALgPQAMAMARAAQAIAAAEgDQAFgDAAgEQgBgFgFgDQgEgCgJgCQgRgEgGgEQgMgGAAgOQAAgMAKgIQAKgJAPAAQAXAAAOANIgLAPQgLgKgPAAQgOAAAAAJQAAAFAFACQADACAJACQARAEAHAEQAMAHAAAOQAAANgKAIQgJAJgTAAQgYAAgPgPg");
	this.shape_6.setTransform(16.85,-1.975);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#003946").s().p("AAbAvIgGgQIgpAAIgGAQIgWAAIAlhdIAYAAIAkBdgAAQAOIgQgrIgPArIAfAAg");
	this.shape_7.setTransform(4.65,-1.975);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#003946").s().p("AgJAvIAAhMIgcAAIAAgRIBLAAIAAARIgcAAIAABMg");
	this.shape_8.setTransform(-4.075,-1.975);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#003946").s().p("AgJAvIAAhMIgcAAIAAgRIBLAAIAAARIgcAAIAABMg");
	this.shape_9.setTransform(-12.075,-1.975);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#003946").s().p("AgJAvIAAhdIATAAIAABdg");
	this.shape_10.setTransform(-17.95,-1.975);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#003946").s().p("AghAvIAAhdIBDAAIAAARIgvAAIAAAVIAuAAIAAAQIguAAIAAAng");
	this.shape_11.setTransform(-23.45,-1.975);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#003946").s().p("AgiAjQgOgOAAgVQAAgUAOgOQAOgOAUAAQAVAAAOAOQAOAOAAAUQAAAVgOAOQgOAOgVAAQgUAAgOgOgAgUgVQgIAJAAAMQAAANAIAJQAIAJAMAAQANAAAIgJQAIgJAAgNQAAgMgIgJQgIgJgNAAQgMAAgIAJg");
	this.shape_12.setTransform(-32.875,-1.975);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#003946").s().p("AAPAvIgRgiIgPAAIAAAiIgUAAIAAhdIArAAQAOAAAJAIQAJAJAAANQAAAMgHAHQgFAGgJACIAVAkgAgRgDIAUAAQAGAAAEgEQAEgDAAgGQAAgGgEgEQgEgDgGAAIgUAAg");
	this.shape_13.setTransform(-42.425,-1.975);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#003946").s().p("AglAvIAAhdIArAAQAPAAAIAJQAJAIAAANQAAANgJAHQgIAJgPAAIgXAAIAAAigAgRgDIAUAAQAHAAADgEQAFgDAAgGQAAgGgFgDQgDgEgHAAIgUAAg");
	this.shape_14.setTransform(-51.1,-1.975);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#003946").s().p("AglAvIAAhdIArAAQAPAAAIAJQAJAIAAANQAAANgJAHQgIAJgPAAIgXAAIAAAigAgRgDIAVAAQAFAAAFgEQADgDAAgGQAAgGgDgDQgFgEgFAAIgVAAg");
	this.shape_15.setTransform(-59.7,-1.975);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#003946").s().p("AAbAvIgGgQIgpAAIgGAQIgWAAIAlhdIAYAAIAkBdgAAPAOIgPgrIgOArIAdAAg");
	this.shape_16.setTransform(-69.05,-1.975);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]}).wait(1));

	// Layer_2
	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("As4CTQg5AAAAg5IAAizQAAg5A5AAIZxAAQA5AAAAA5IAACzQAAA5g5AAg");
	this.shape_17.setTransform(-0.775,-1.925);

	this.timeline.addTween(cjs.Tween.get(this.shape_17).wait(1));

}).prototype = getMCSymbolPrototype(lib.CTA, new cjs.Rectangle(-89,-16.6,176.5,29.400000000000002), null);


(lib.baselogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#063C4A").s().p("AwPGhIAAp2QAAhVA+g6QA/g8BXAAIZ3AAQBYAAA+A8QA+A6AABVIAAJ2g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.baselogo, new cjs.Rectangle(-104,-41.7,208,83.4), null);


(lib.tx3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.instance = new lib.icofurgone();
	this.instance.parent = this;
	this.instance.setTransform(-5,-55.3);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgoBbQgRgKgJgRQgKgSAAgVIgBgZIABgYQAAgVAJgRQAJgRASgKQARgLAXAAQAYAAARALQARAKAJARQAKARAAAVIABAYIgBAZQgBAVgJASQgJARgRAKQgRAKgYAAQgXAAgRgKgAgjg9QgOANgBAaIAAAWIAAAYQABAaAOANQANANAWAAQAWAAAOgNQAOgNABgaIAAgYIAAgWQgBgagOgNQgOgNgWAAQgWAAgNANg");
	this.shape.setTransform(93.925,15.325);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgFBiQgDAAgCgCQgCgDAAgDIAAiiIg1AAQgDAAgCgCQgCgDAAgDIAAgKQAAgCACgDQACgCADAAICDAAQADAAACACQACADAAACIAAAKQAAADgCADQgCACgDAAIg1AAIAACiQAAADgCADQgCACgDAAg");
	this.shape_1.setTransform(76.575,15.35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABKBiQgIAAgDgHIgOgmIhgAAIgPAmQgDAHgIAAIgKAAQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQgBAAAAgBIABgEIBFiwQAEgJAJAAIAPAAQAKAAADAJIBECwIABAEQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBABQgBAAAAAAQgBABAAAAQgBAAAAAAgAAnAcIgnhjIglBjIBMAAg");
	this.shape_2.setTransform(59.1,15.35);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AglBdQgRgIgKgMQgKgMAAgMQAAAAAAgBQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBABAAQAAAAABgBQAAAAABAAQABAAAAAAIAMAAIAFABIADAFQAFAKAMAIQALAJAUAAQAUAAAPgJQAOgJAAgOQAAgJgIgHQgHgGgNgEIglgLQgbgHgMgMQgMgOAAgTQAAgPAHgMQAIgMAPgIQAPgIAVAAQAVAAAQAJQAQAIAIAMQAJAMABAKQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAAAQgBABAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAIgMAAIgFgBIgEgFQgEgJgLgIQgLgIgSAAQgQAAgMAHQgLAIAAAOQAAAJAFAGQAGAGAMAFIAiAKQAgAJANALQANAMAAAVQAAARgJANQgKAMgRAIQgRAHgWAAQgUAAgRgIg");
	this.shape_3.setTransform(40.875,15.325);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ag4BOQgSgVAAglIAAhvQAAgDACgCQACgCADAAIAMAAQADAAACACQACACAAADIAABxQAAAbANANQANAOAWAAQAXAAANgOQANgNAAgbIAAhxQAAgDACgCQACgCADAAIAMAAQADAAACACQACACAAADIAABvQAAAlgSAVQgTAVgmAAQgmAAgSgVg");
	this.shape_4.setTransform(22.575,15.475);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgoBbQgRgKgJgRQgKgSAAgVIgBgZIABgYQAAgVAJgRQAJgRASgKQARgLAXAAQAYAAARALQARAKAJARQAKARAAAVIABAYIgBAZQgBAVgJASQgJARgRAKQgRAKgYAAQgXAAgRgKgAgjg9QgOANgBAaIAAAWIAAAYQABAaAOANQANANAWAAQAWAAAOgNQAOgNABgaIAAgYIAAgWQgBgagOgNQgOgNgWAAQgWAAgNANg");
	this.shape_5.setTransform(-3.375,15.325);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AA3BiQgIAAgEgIIgphHIgvAAIAABHQAAADgCADQgDACgDAAIgLAAQgDAAgCgCQgDgDAAgDIAAi0QAAgCADgDQACgCADAAIBDAAQAdAAATAPQATAOAAAdQAAAWgLAOQgLANgSAFIAqBKIABADQAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAABgBAAQgBAAAAAAgAgtgFIAuAAQArAAAAgiQAAgRgLgIQgLgIgVAAIguAAg");
	this.shape_6.setTransform(-21.325,15.35);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgFBiQgDAAgCgCQgCgDAAgDIAAi0QAAgCACgDQACgCADAAIALAAQADAAACACQACADAAACIAAC0QAAADgCADQgCACgDAAg");
	this.shape_7.setTransform(-34.725,15.35);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgFBiQgDAAgCgCQgCgDAAgDIAAiiIg1AAQgDAAgCgCQgCgDAAgDIAAgKQAAgCACgDQACgCADAAICDAAQADAAACACQACADAAACIAAAKQAAADgCADQgCACgDAAIg1AAIAACiQAAADgCADQgCACgDAAg");
	this.shape_8.setTransform(-46.375,15.35);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgFBiQgDAAgCgCQgCgDAAgDIAAi0QAAgCACgDQACgCADAAIALAAQADAAACACQACADAAACIAAC0QAAADgCADQgCACgDAAg");
	this.shape_9.setTransform(-58.075,15.35);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AA3BiQgIAAgEgIIgphHIgvAAIAABHQAAADgCADQgDACgDAAIgLAAQgDAAgCgCQgDgDAAgDIAAi0QAAgCADgDQACgCADAAIBDAAQAdAAATAPQATAOAAAdQAAAWgLAOQgLANgSAFIAqBKIABADQAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAABgBAAQgBAAAAAAgAgtgFIAuAAQArAAAAgiQAAgRgLgIQgLgIgVAAIguAAg");
	this.shape_10.setTransform(-70.325,15.35);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag4BiQgDAAgCgCQgCgDAAgDIAAi0QAAgCACgDQACgCADAAIBuAAQADAAADACQACADAAACIAAAKQAAADgCADQgDACgDAAIhbAAIAAA8IBVAAQADAAACACQADACAAADIAAAJQAAADgDACQgCACgDAAIhVAAIAAA+IBeAAQADAAACACQACACAAADIAAAKQAAADgCADQgCACgDAAg");
	this.shape_11.setTransform(-94.525,15.35);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AghBLQgOgJgHgOQgIgOAAgRIgBgVIABgTQAAgSAIgOQAHgOAOgIQAOgJATAAQAUAAAOAJQAOAIAIAOQAHAOAAASIABATIgBAVQAAARgIAOQgHAOgOAJQgOAIgUAAQgTAAgOgIgAgdgyQgLALgBAVIAAASIAAAUQABAVALALQAMAKARAAQASAAAMgKQALgLABgVIAAgUIAAgSQgBgVgLgLQgMgLgSAAQgRAAgMALg");
	this.shape_12.setTransform(97.625,-12.875);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgEBRQgIgBgEgIIgxiQIgBgDQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAIAJAAQAHAAACAFIArCDIAsiDQACgFAHAAIAJAAQAAAAABAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAAAIgBADIgxCQQgCAEgDACQgDADgEAAg");
	this.shape_13.setTransform(82.475,-12.85);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AghBLQgOgJgHgOQgIgOAAgRIgBgVIABgTQAAgSAIgOQAHgOAOgIQAOgJATAAQAUAAAOAJQAOAIAIAOQAHAOAAASIABATIgBAVQAAARgIAOQgHAOgOAJQgOAIgUAAQgTAAgOgIgAgdgyQgLALgBAVIAAASIAAAUQABAVALALQAMAKARAAQASAAAMgKQALgLABgVIAAgUIAAgSQgBgVgLgLQgMgLgSAAQgRAAgMALg");
	this.shape_14.setTransform(67.325,-12.875);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AguBAQgPgSAAgdIAAhcQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAABAAQABAAAAAAIAKAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQAAABAAAAQABABAAAAQAAABAAAAIAABdQAAAWALALQAKALASAAQATAAALgLQAKgLAAgWIAAhdQAAAAAAgBQABAAAAgBQAAAAAAgBQABAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAQABAAAAAAIAKAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQAAABAAAAQABABAAAAQAAABAAAAIAABcQAAAdgPASQgQASgfAAQgfAAgPgSg");
	this.shape_15.setTransform(51.575,-12.75);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAtBRQgCAAgCgDIgFgEIhJhwIAABwQAAABgBABQAAAAAAABQAAAAAAABQgBAAAAAAQgBABAAAAQgBABAAAAQgBAAAAAAQgBABgBAAIgJAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAiUQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAIAIAAQADAAACABIAEAGIBKBvIAAhxQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAIAKAAQAAAAABAAQAAAAABAAQAAAAABABQABAAAAAAQAAABABAAQAAABAAAAQABABAAAAQAAABAAAAIAACUQAAABAAABQAAAAgBABQAAAAAAABQgBAAAAAAQAAABgBAAQgBABAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_16.setTransform(35.6,-12.85);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AA9BRQgHAAgCgGIgMgfIhPAAIgMAfQgCAGgHAAIgIAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIABgDIA4iQQADgHAHAAIANAAQAIAAACAHIA4CQIABADQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAABAAAAgAAgAXIgghRIgeBRIA+AAg");
	this.shape_17.setTransform(8.6,-12.85);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAtBRQgCAAgCgDIgFgEIhJhwIAABwQAAABgBABQAAAAAAABQAAAAAAABQgBAAAAAAQgBABAAAAQgBABAAAAQgBAAAAAAQgBABgBAAIgJAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAiUQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAIAIAAQADAAACABIAEAGIBKBvIAAhxQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAIAJAAQABAAABAAQAAAAABAAQAAAAABABQABAAAAAAQAAABABAAQAAABAAAAQABABAAAAQAAABAAAAIAACUQAAABAAABQAAAAgBABQAAAAAAABQgBAAAAAAQAAABgBAAQgBABAAAAQgBAAAAAAQgBABgBAAg");
	this.shape_18.setTransform(-7.15,-12.85);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgvBBQgRgRAAgcIgBgUIABgUQAAgRAIgOQAGgOAPgIQAPgJAUAAQATAAAPAIQAOAHAHAKQAIALAAAJQABAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAAAAAIgKAAQgFAAgBgDQgIgNgJgGQgJgHgRAAQgSAAgMALQgMALgBAUIAAATIAAATQABAVAMALQALALATAAQAUAAAMgKQAMgLAAgWIAAgHIghAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAgBQAAAAAAgBIAAgHQAAgBAAAAQAAgBAAgBQAAAAABAAQAAgBABAAQAAgBABAAQAAAAABgBQAAAAABAAQAAAAABAAIAxAAQAAAAABAAQAAAAABAAQAAABABAAQABAAAAABQABAAAAABQAAAAABAAQAAABAAABQAAAAAAABIAAAVQAAASgIAPQgIAOgPAIQgPAIgUAAQgfAAgQgSg");
	this.shape_19.setTransform(-22.9,-12.875);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AguBRQAAAAgBgBQAAAAgBAAQAAAAgBgBQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQgBgBAAgBIAAiUQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQABgBAAAAQABAAAAAAQABAAAAAAIBaAAQABAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAABABAAQAAABAAAAQABABAAAAQAAABAAAAIAAAJQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAABQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAIhKAAIAAAwIBGAAQAAAAABABQAAAAABAAQAAAAABABQABAAAAABQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABIAAAHQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBABQAAAAgBAAQgBABAAAAQgBAAAAAAQgBABAAAAIhGAAIAAAyIBMAAQABAAABAAQAAAAABAAQAAABABAAQAAAAABABQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABIAAAIQAAABAAABQAAAAAAABQAAAAAAABQgBAAAAAAQgBABAAAAQgBABAAAAQgBAAAAAAQgBABgBAAg");
	this.shape_20.setTransform(-37.2,-12.85);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgeBNQgOgHgIgKQgJgKAAgKIABgDQABgBAAAAQABAAAAAAQABgBAAAAQABAAAAAAIAJAAIAFABIADAEQADAJAKAGQAKAHAQAAQAQAAAMgHQAMgHAAgMQAAgHgGgGQgGgFgLgDIgegJQgWgGgKgKQgKgLAAgQQAAgMAGgKQAGgKANgGQAMgHARAAQARAAANAHQANAHAHAKQAHAKABAIQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgKAAIgEgBIgDgEQgDgHgKgHQgJgHgOAAQgNAAgKAGQgJAHAAALQAAAIAEAFQAFAFAKADIAbAJQAbAHALAJQALAKAAARQAAAOgIALQgIAKgOAGQgOAGgSAAQgQAAgOgGg");
	this.shape_21.setTransform(-51.575,-12.875);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAuBRQgEAAgCgDIgDgEIhLhwIAABwQAAABAAABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAQgBABAAAAQgBAAAAAAQgBABAAAAIgKAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAgBgBQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAiUQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBQABAAABAAQAAgBABAAQAAAAABAAQAAAAABAAIAIAAQADAAACABIAEAGIBKBvIAAhxQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAIAJAAQABAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAABABAAQAAABABAAQAAABAAAAQAAABAAAAIAACUQAAABAAABQAAAAAAABQgBAAAAABQgBAAAAAAQgBABAAAAQgBABAAAAQgBAAAAAAQgBABgBAAg");
	this.shape_22.setTransform(-66.6,-12.85);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AghBLQgOgJgHgOQgIgOAAgRIgBgVIABgTQAAgSAIgOQAHgOAOgIQAOgJATAAQAUAAAOAJQAOAIAIAOQAHAOAAASIABATIgBAVQAAARgIAOQgHAOgOAJQgOAIgUAAQgTAAgOgIgAgdgyQgLALgBAVIAAASIAAAUQABAVALALQAMAKARAAQASAAAMgKQALgLABgVIAAgUIAAgSQgBgVgLgLQgMgLgSAAQgRAAgMALg");
	this.shape_23.setTransform(-82.325,-12.875);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AggBLQgPgIgIgOQgIgOAAgSIgBgVIABgTQAAgSAIgOQAIgOAPgIQAOgJASAAQAWAAAOAJQAPAIAGAMQAHAMABALIgCAEQAAABgBAAQAAAAAAAAQgBABAAAAQgBAAAAAAIgLAAIgEgCIgCgEQgDgNgKgJQgJgJgVAAQgTAAgLAMQgLALgBAUIAAASIAAAUQABATALAMQALALATAAQAVAAAJgIQAKgJADgOIACgEIAEgBIALAAQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQgBALgHAMQgGAMgPAJQgOAIgWAAQgSAAgOgIg");
	this.shape_24.setTransform(-97.525,-12.875);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AhYC8QgogRgXgcQgXgbgBgdQAAgFAEgEQAEgDAEAAIBLAAQAMAAAJAIIAKAKQAHAIAPAGQAPAHAUAAQBGAAAAgeQAAgKgKgGQgKgHgSgEIg5gOIgagFQg6gNgbgbQgcgeAAgxQAAghAVgdQAUgbAkgSQAlgQAwAAQAtAAAmARQAmARAWAbQAWAaABAZQAAAFgDAEQgEADgFAAIhKAAIgNgCIgKgHIgHgHQgHgHgNgFQgOgFgQAAQgZAAgPAGQgQAHAAAQQAAAMAKAGQAJAGAUAGIBGAPQBAANAfAbQAeAcAAA0QAAAmgXAcQgWAcgoAPQgpAPgyAAQgwAAgogRg");
	this.shape_25.setTransform(87.625,54.8);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgkDIQgHAAgEgFQgFgFAAgGIAAlvQAAgGAFgFQAEgEAHgBIBJAAQAGABAFAEQAFAFAAAGIAAFvQAAAGgFAFQgFAFgGAAg");
	this.shape_26.setTransform(59.275,54.8);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgkDIQgHAAgEgFQgFgFAAgGIAAkkIhkAAQgGABgFgFQgEgFAAgFIAAg9QAAgGAEgFQAFgEAGgBIExAAQAHABAEAEQAEAFAAAGIAAA9QAAAFgEAFQgEAFgHgBIhkAAIAAEkQAAAGgFAFQgEAFgHAAg");
	this.shape_27.setTransform(32.025,54.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AByDIQgKgBgFgEQgGgEgBgGIgQgvIiXAAIgQAvQgCAGgFAEQgGAEgJABIhIAAQgFAAgEgEQgDgEAAgFIACgJIB8lmQADgIAGgFQAGgFALgBIBbAAQAKABAHAFQAGAFADAIIB8FmIACAJQAAAFgDAEQgEAEgFAAgAAuAyIguiIIgtCIIBbAAg");
	this.shape_28.setTransform(-6.375,54.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("ABNDIQgKgBgFgEIgIgLIg+h6Ig1AAIAAB6QAAAGgFAFQgEAFgHAAIhKAAQgHAAgEgFQgEgFgBgGIAAlvQABgGAEgFQAEgEAHgBICZAAQBNABAqAgQAqAhAABBQAABShEAfIBGCHIACAHQABAFgEAEQgEAEgFAAgAg9gaIA/AAQA3AAAAgqQAAgqg3AAIg/AAg");
	this.shape_29.setTransform(-45.7,54.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AhbC5QgngWgWgiQgVgkgDgrIgBgsIABg3QACgrAWgkQAWgiAngVQAogVA0AAQAyAAAoATQAnASAWAdQAWAdABAaQABAFgEAEQgEADgFAAIhMAAQgIAAgEgDIgLgLQgKgNgOgHQgOgIgZAAQhAAAgHBCIgCAsIACAzQACAdARASQARATAjAAQAgAAAUgPQAUgQAAggIgwAAQgGAAgFgEQgFgFAAgGIAAg7QAAgHAFgFQAFgEAGAAICKAAQAGAAAFAEQAEAFAAAHIAABIQAAAugXAkQgYAkgoATQgoATgyAAQg0AAgogUg");
	this.shape_30.setTransform(-86.675,54.8);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("rgba(0,57,70,0.8)").s().p("AwYQaQj7AAAAj9IAA45QAAj9D7AAMAgxAAAQD7AAAAD9IAAY5QAAD9j7AAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.tx3, new cjs.Rectangle(-130,-105,260,210), null);


(lib.tx2anim = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{apritestodue:1,chiuditestodue:14});

	// timeline functions:
	this.frame_0 = function() {
		this.visible=false;
		this.stop();
	}
	this.frame_1 = function() {
		this.visible=true;
	}
	this.frame_14 = function() {
		this.stop();
	}
	this.frame_26 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(13).call(this.frame_14).wait(12).call(this.frame_26).wait(1));

	// Livello_1
	this.instance = new lib.tx2();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({scaleX:0.64,scaleY:0.64},0).to({scaleX:1,scaleY:1},13,cjs.Ease.backOut).to({scaleX:0.64,scaleY:0.64},11,cjs.Ease.backIn).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-134.6,-108.7,269.2,217.4);


(lib.tx1anim = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{apritestouno:1,chiuditestouno:14});

	// timeline functions:
	this.frame_0 = function() {
		this.visible=false;
		this.stop();
	}
	this.frame_1 = function() {
		this.visible=true;
	}
	this.frame_14 = function() {
		this.stop();
	}
	this.frame_26 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(13).call(this.frame_14).wait(12).call(this.frame_26).wait(1));

	// Livello_1
	this.instance = new lib.tx1();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({scaleX:0.64,scaleY:0.64},0).to({scaleX:1,scaleY:1},13,cjs.Ease.backOut).to({scaleX:0.64,scaleY:0.64},11,cjs.Ease.backIn).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-134.6,-108.7,269.2,217.4);


(lib.logoanim = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.visible=false;
	}
	this.frame_1 = function() {
		this.visible=true;
	}
	this.frame_34 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(33).call(this.frame_34).wait(1));

	// logo
	this.instance = new lib.logo();
	this.instance.parent = this;
	this.instance.setTransform(0.3,-19.9,0.9896,0.9822,0,0,0,0.2,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},1).wait(15).to({_off:false,regX:0.3,scaleX:0.8564,scaleY:0.85,x:0.35,y:-19.85,alpha:0},0).to({regX:0.2,scaleX:0.9896,scaleY:0.9822,x:0.3,y:-19.9,alpha:1},18,cjs.Ease.backOut).wait(1));

	// Livello_3
	this.instance_1 = new lib.baselogo();
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({y:50},0).to({y:0},18,cjs.Ease.backOut).wait(16));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-104,-46.6,208,138.3);


(lib.imganim = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{aperto:29,chiuso:79,"aperto":95,"chiuso":145,"aperto":161});

	// timeline functions:
	this.frame_0 = function() {
		this.visible=false;
	}
	this.frame_1 = function() {
		this.visible=true;
	}
	this.frame_29 = function() {
		this.parent.testouno.gotoAndPlay("apritestouno");
	}
	this.frame_79 = function() {
		this.parent.testouno.gotoAndPlay("chiuditestouno");
	}
	this.frame_95 = function() {
		this.parent.testodue.gotoAndPlay("apritestodue");
	}
	this.frame_145 = function() {
		this.parent.testodue.gotoAndPlay("chiuditestodue");
	}
	this.frame_161 = function() {
		this.parent.testotre.gotoAndPlay("apritestotre");
	}
	this.frame_211 = function() {
		this.parent.fine.gotoAndPlay("aprifine");
	}
	this.frame_212 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(28).call(this.frame_29).wait(50).call(this.frame_79).wait(16).call(this.frame_95).wait(50).call(this.frame_145).wait(16).call(this.frame_161).wait(50).call(this.frame_211).wait(1).call(this.frame_212).wait(1));

	// Livello_1
	this.instance = new lib._img();
	this.instance.parent = this;
	this.instance.setTransform(-59.5,-25.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({x:91.5},0).to({x:-85.5},211).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-335.5,-300,676,600);


(lib.fine = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{aprifine:1});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
		this.visible=false;
	}
	this.frame_1 = function() {
		this.visible=true;
	}
	this.frame_21 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(20).call(this.frame_21).wait(1));

	// testo
	this.instance = new lib.txfine();
	this.instance.parent = this;
	this.instance.setTransform(0.2,-79.5,0.4979,0.4979,0,0,0,0.4,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},1).wait(10).to({_off:false,x:160.2,alpha:0},0).to({x:0.2,alpha:1},10,cjs.Ease.quadOut).wait(1));

	// CTA
	this.instance_1 = new lib.CTA();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0.9,4.5,1.1361,1.1353);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({_off:true},1).wait(10).to({_off:false,x:-264.7},0).to({x:0.9},10,cjs.Ease.backOut).wait(1));

	// fondo
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#063C4A").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#063C4A").s().p("EgJXAu4MAAAhdvISvAAMAAABdvg");
	this.shape_1.setTransform(-320,0,2.5,1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).wait(11));
	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},1).wait(1).to({_off:false,x:-288},0).wait(1).to({x:-256},0).wait(1).to({x:-224},0).wait(1).to({x:-192},0).wait(1).to({x:-160},0).wait(1).to({x:-128},0).wait(1).to({x:-96},0).wait(1).to({x:-64},0).wait(1).to({x:-32},0).wait(1).to({x:0},0).wait(11));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-470,-300,733.6,600);


(lib.tx3anim = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{"apritestodue":1});

	// timeline functions:
	this.frame_0 = function() {
		this.visible=false;
		this.stop();
	}
	this.frame_1 = function() {
		this.visible=true;
	}
	this.frame_14 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(13).call(this.frame_14).wait(1));

	// Livello_1
	this.instance = new lib.tx3();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({scaleX:0.64,scaleY:0.64},0).to({scaleX:1,scaleY:1},13,cjs.Ease.backOut).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-134.6,-108.7,269.2,217.4);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// logo
	this.logo = new lib.logoanim();
	this.logo.name = "logo";
	this.logo.parent = this;
	this.logo.setTransform(150,596.25,1.3,1.3,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.logo).wait(1));

	// fine
	this.fine = new lib.fine();
	this.fine.name = "fine";
	this.fine.parent = this;
	this.fine.setTransform(150,299.95);

	this.timeline.addTween(cjs.Tween.get(this.fine).wait(1));

	// testouno
	this.testouno = new lib.tx1anim();
	this.testouno.name = "testouno";
	this.testouno.parent = this;
	this.testouno.setTransform(150.05,120,0.9177,0.9177,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.testouno).wait(1));

	// testodue
	this.testodue = new lib.tx2anim();
	this.testodue.name = "testodue";
	this.testodue.parent = this;
	this.testodue.setTransform(150.05,120,0.9177,0.9177,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.testodue).wait(1));

	// testotre
	this.testotre = new lib.tx3anim();
	this.testotre.name = "testotre";
	this.testotre.parent = this;
	this.testotre.setTransform(150.05,120,0.9177,0.9177,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.testotre).wait(1));

	// img
	this.instance = new lib.imganim();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-9.5,300,349,350.29999999999995);
// library properties:
lib.properties = {
	id: '6659AD9ACDFA482E838F4699736A04DB',
	width: 300,
	height: 600,
	fps: 24,
	color: "#CCCCCC",
	opacity: 1.00,
	manifest: [
		{src:"immagine.jpg", id:"immagine"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['6659AD9ACDFA482E838F4699736A04DB'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;