(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.alabludx = function() {
	this.initialize(img.alabludx);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,122,100);


(lib.alablusx = function() {
	this.initialize(img.alablusx);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,83,154);


(lib.alagialladx = function() {
	this.initialize(img.alagialladx);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,115,204);


(lib.alagiallasx = function() {
	this.initialize(img.alagiallasx);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,165,145);


(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.corpofarfallablu = function() {
	this.initialize(img.corpofarfallablu);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,38,49);


(lib.corpofarfallagiallo = function() {
	this.initialize(img.corpofarfallagiallo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,77,117);


(lib.tovaglia = function() {
	this.initialize(img.tovaglia);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,22,25);


(lib.volantino = function() {
	this.initialize(img.volantino);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,269,266);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.volantino_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.instance = new lib.volantino();
	this.instance.parent = this;
	this.instance.setTransform(-128,-118);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.volantino_1, new cjs.Rectangle(-128,-118,269,266), null);


(lib.specialetx = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnVG2IgagHQgMgFgBgDQgBgGADgTQACgRAHgdIBFkTQAShEAEgIQAEgFAQAAQAPABgEAIQgEAJgHAdIgNA2QgBAFADAAQACABADgFQAWggAXgYQAXgXASgHQANgEAWAKQAVALAFAFQAPAPADAaQACAXgJAdQgCAGAHgBQALgCAJABIAIAAIAAgBQgEgfAOglQAOglATgdQAvhJA1gJQApgHADAkQgCAXgGARQgQArgiAkQgfAhgiALQgHACABAFQADAUAMAKQAYAUAjgaQAYgWAVgbIANgRIAAgCQACgeAMghQAQgkAPgWQA2hMA4gGQAqgFABAkQAAANgHAaQgHAcACAJQACANgUgKQgUgLACgPQABgHAFgPQAFgOAEgTQAEgYgcASQgUAOgUAeQgrBFgBAyQgCA0AYARQAhAZA9hRQAOgRAagqIAZhKQAFgMANALQANAMgGAWIgHAnQgGAhgBAVQgCAVACAQQACAOAHgKIAshHQABgWAGgTQANgqAUghQAthKAwgKQAygKACBSQgBAGAIADQAIAEACADQAFAGgFAMQgFATgEAnQgEAvAEAfIABAIQAAAEAGgJQAKgPARgdQAJgQALgUIAEgiQANhXAVhWQAWhWALgiQAahIASgdQAKgNARASQAQAQAEAOQAIAcgHA3QgHA5gQA5QgPAxgQAbQgQAbgTAQQgJAIAAAIQgNA8gDAjQgCAlABARQABAbAQgOQAIgIANgTQANgSAUglIANgXIAIggQASg0ATggQAzhWA3AGQAqAFACAzQgDAfgIAWQgRA4glApQgiAkgiAEQgHABABAHQACAfAMARQAYAmAkgbQAcgbATgcQATgaAPgcQAPgaAOgfQAFgJAEAIIABADIAAABIAAAJQgCAKgEAHQgMAcgSAjQgSAigcAsQgzBHg4gNQgagGgSgcQgTgcgDg2IAAgGIgTAoQgLAYgNAUQgMAUgKAIQgHAHgagZQgdgggDgnIAAgYIgTAlQgMAZgKAQQgLARgJAIQgIAJgQgTQgQgTgGgbQgDgNgBgXQgBgPgGAJQgHAKgHASIgPAjQgIAQgJANQgJALgIgFQgegOgRgYQgNgTgDgVIAAgBIgJAUQgLAWgKAQQgLASgJAIQgIAJgQgQQgRgQgHgYQgEgSABgVQgPAagPASQgfAogdALQgdALgZgIQgjgQgMgZQgFgKgDgPIgXAhQgvA7g4ADQgZACgTgPQgOgMgGgaIgmAIQgHACgEAHQgWAoghATQgMAHgTAFQgSAEgQgDQghgIAIggQACgKAYgLQAWgKAfgKQAIgCADgFQAOgcAGgaQAHgdgEgSQgFgTgWAPQgdATgjA6QgQAagNAeQgOAhgGAaIgJAmQgMA5gBAwQgDAsAHAQQADAHgKAAQgKAAgOgDgAlJCtQgfAKgHAJQgGAJAHAFQAIAGAEgCQAHgBAIgKQAIgKAIgMQAEgEgFAAIgFAAgAGDhxQgSAcgLArQgKAogDAlQgDAjAGAUQAGATANgQQAMgPAKgQQAJgPAMgXQAVgoALgfQAbhOgXgWQgGgFgHAAQgUAAgaAngAg2hGQgLABgRAQQgPAQgRAbQgRAagHAbQgGAVgCASQAAANANgLQAYgVAfgrQAQgYAHgPQAJgTACgPQABgRgJAAIgCAAgAMbipQgQAQgTAhQgSAfgJAmQgHAcgCAZQgBARAOgLQAagVAggyQAPgZALgXQALgaACgSQACgbgMgCIgCAAQgLAAgQAPgAKjmKQgSAmgTBUQgRBLgKA+QAAANAPgZQAQgaAWhOQAMgsAEglQAGglgEgXQgCgGgBAAQgCAAgCAEgAuWGTIgBgBIAAgBIAHgEQAVgLAYgGQAZgHAbACIAsACQAtADAwgVQAygUAdgZQAdgagFgNQgFgOgXgCQgPgBgjACQgrADguAIQhJAOgZgIQgagIAQgkQANgaAggsQAcgmAqgwQAkgpAngiQAqglAngVQAxgaAZAEQAZAEAEAdQAEAYgSAtIgZBJQgJAYgFAjQgBAQgcgEQgdgCgEgRQgCgRAZgzQAYg1AOgyQAIgYgRgEQgRAAggAUQgqAbhDBVQggArgVAiQgYAmgHAYQgIAZAfACQATgBBHgLQA2gHAoACQAkACASAIQAiARgeArQgsAzhTAbQhRAag0gDQgggDgbgEQgegDgfAGQgPAFgGAAIgBAAgADrh2QAGghAXAAQANACACAKQACAJgEAMQgOAegQACIgCAAQgOAAAEggg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.specialetx, new cjs.Rectangle(-92,-44.1,184.1,88.3), null);


(lib.piegha = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#54070C","rgba(255,255,255,0)"],[0,1],-1,-63.8,0,-1,-63.8,102.6).s().p("AyCLDIAA2GMAkFAAAIAAWGg");
	this.shape.setTransform(0,-2.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.piegha, new cjs.Rectangle(-115.5,-72.9,231,141.5), null);


(lib.luce = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.514,1],-92,0,91.8,0).s().p("AuWfEMAAAg+HIctAAMAAAA+Hg");
	this.shape.setTransform(0.1,-180.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.luce, new cjs.Rectangle(-91.8,-379.1,183.8,397.6), null);


(lib.logospecialissimi = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAtDRQgVgJgJgUQgIgVAIgVQAJgVAVgJQAUgIAWAIQAVAJAIAVQAJAUgJAWQgJAVgUAIQgKAEgKAAQgLAAgLgEgAh4i0IBOggIB0EXIhNAgg");
	this.shape.setTransform(80.7,20.9,0.485,0.485);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ah2i5IBQgfICcGSIhPAfg");
	this.shape_1.setTransform(75.3,23.2,0.485,0.485);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AjpijIBrgjIB3DlIACgBIgwj8IBsgkICzGMIhUAcIh0khIgBAAIATBqIAeDNIg/AVIhni4IgshWIgDgIIgBAAIBVEsIhXAcg");
	this.shape_2.setTransform(64.3,27.8,0.485,0.485);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhgjFIBTgWIBuGhIhTAWg");
	this.shape_3.setTransform(51.4,31,0.485,0.485);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgGDgQgVgBgQgHIgShQQAmAPAdgHQAVgEALgQQALgQgFgUQgFgVgTgMIgmgSQgugSgWgUQgcgagKgrQgMg1AVgpQAWgsA0gLQAmgJAnANIATBRQglgUgdAHQgTAEgJAOQgJANAEAUQAFAWAZAQQAHAFArAUQBKAhAOA+QANA6gXArQgYAtg6ANQgNADgPAAIgKAAg");
	this.shape_4.setTransform(43.3,33.1,0.485,0.485);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgRDfQgWgCgQgIIgNhRQAkARAggFQAUgDALgPQAMgPgEgVQgDgWgTgNIglgTQgtgUgVgWQgagbgIgsQgJg1AXgoQAZgrA0gIQAmgHAnAPIAOBSQgkgWgdAFQgUAEgJANQgKANAEATQAEAXAXARQAHAFAqAWQBIAlALA/QAKA7gaAqQgbArg6AKQgLACgLAAIgPgBg");
	this.shape_5.setTransform(32.9,35.1,0.485,0.485);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhEjQIBUgLIA1GtIhUAKg");
	this.shape_6.setTransform(24.6,36.2,0.485,0.485);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhojTIBVgHIAcFeIBZgHIAHBQIitAOg");
	this.shape_7.setTransform(17.7,37.2,0.485,0.485);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag3jXIBZgCIBxGtIhbACIgRhIIhWACIgOBJIhVABgAgjBLIA7gBIgiizIgBAAg");
	this.shape_8.setTransform(5.9,37.7,0.485,0.485);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgwDXIAMmwIBVADIgMGwg");
	this.shape_9.setTransform(-4.2,37.6,0.485,0.485);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AA0DdQhXgGgxhKQgthDAHhaQAGhWA3g7QA7hBBSAGQAWACAVAKIgGBOQgRgGgOgBQg1gEggApQgcAjgEA3QgEA1AXArQAZAyA0AEQAOABATgFIgGBRQgPAEgRAAIgIAAg");
	this.shape_10.setTransform(-12.3,37.4,0.485,0.485);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhvDMIA1mtICqAWIgKBQIhWgLIgLBdIBLAKIgKBPIhKgKIgNBhIBXALIgKBPg");
	this.shape_11.setTransform(-22.8,36.2,0.485,0.485);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AiQDOIBMmqIBXAQQAzAJAaARQA9AngQBXQgKA6gqAbQgoAbg7gLIgSgEIgfCwgAgQgWQAfAGARgKQATgLAGgfQAKg4gwgIIgQgDg");
	this.shape_12.setTransform(-33.8,33.9,0.485,0.485);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag+DXQgTgFgRgJQgUgLgLgNIAThQQAbAeAfAHQAUAFAQgJQAQgKAGgUQAEgVgLgTIgbghQgigjgLgdQgOgkAKgrQAMg0AlgcQAlgeA0AMQAmAJAfAdIgTBRQgZgigdgHQgUgFgNAJQgOAIgEAUQgGAWAPAZQAFAHAfAlQA0A+gOA/QgOA6gnAcQgeAVgjAAQgQAAgRgEg");
	this.shape_13.setTransform(-45.2,32.1,0.485,0.485);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AhmDDIB7mdIBSAYIh7Geg");
	this.shape_14.setTransform(-59.7,28.3,0.485,0.485);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhsCyICImaIBRAbIhuFNIBTAdIgZBMg");
	this.shape_15.setTransform(-68.4,26.1,0.485,0.485);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AhMDRQhKgcgMhUQgKhFAfhPQAhhWAygsQA/g4BOAeQAtARAVAnQAUAkgEAyIhZAAQAFgYgCgOQgEgWgUgIQgigPgjAwQgWAfgTAwQgzCGA9AXQAbALAXgaQAQgSAMgfIgygUIAchKICDAxIgMAgQggBSgrApQgnAkgsAAQgXAAgZgJg");
	this.shape_16.setTransform(-77.9,22.1,0.485,0.485);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgEKoQvogNu8nEIg8gdIE/thIBIAhQMkF5M/ALQM9AKMwlmIBIggIErNpIg+AcQnhDVnuBpQnTBjnWAAIg0AAgA+JCVQOuG+PXAMQPWAMO5mnIj7rfQs8FstPgKQtNgLs0mAg");
	this.shape_17.setTransform(-0.9,28.7,0.485,0.485);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#D91422").s().p("AgFJ9QnsgGnoh0Qnnh0nZjgIgegOIEmsdIAkARQMtF8NFALQNGAKM2lpIAkgQIETMkIgeAOQunGevDAAIg1AAg");
	this.shape_18.setTransform(-0.9,28.9,0.485,0.485);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Livello_2
	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFEC00").s().p("ADIGVQAUgfAJgkQAJglgDgnQgIhfhJg+QhJg+heAIQhgAIg9BKQg+BJAIBfQAFA2AbAuIlmgFQAxg+BVgRQgbgBgWgFQgUgFgYgLQhXgpgghaQghhaAphWQAohXBaghQBaggBXApQAbAMATAQQAVARATAaQgRgbgIgaQgIgXgDgfQgIhgA+hJQA9hJBggIQBegIBJA+QBJA+AIBfQACAegDAYQgEAagMAdQAPgcARgTQAQgTAZgRQBOg2BeARQBeARA3BOQA2BPgRBeQgQBehPA3QgXAQgVAIQgXAKgcAEQAdAAAYAGQAWAGAaAMQAtAVAgAlQAfAlAOAug");
	this.shape_19.setTransform(4.5,-15.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#EC8721").s().p("A0cN1QAshNA3g4QhxhQhEh4QhDh3gMiHQgOilBGiVQA1hxBbhTQBahTB1gqQBbggBggEQBegDBcAaQATjgCfigQCgijDjgTQDigTC5CFQC2CDA5DZQCyhTC/AiQB6AWBoBCQBnBCBHBnQBfCIAOCkQALCIgvCCQgwCDhjBiQBPA3A6BLQA8BMAhBcQAMAiAJAmg");
	this.shape_20.setTransform(4.6,-19.1,0.485,0.485);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFEC00").s().p("AAyDcQgggKgPgeQgIgSAAgVQgCAhgYAWQgYAWghgCQgigBgXgZQgWgYACgiQABgpAigXQgPAGgSgBQgigBgWgZQgXgYACghQABghAZgXQAYgWAiABQATABASAKQgQgLgKgSQgPgdAKggQAKggAdgQQAegPAgAKQAgAKAPAeQAIASAAATQACgUALgQQARgcAggHQAhgHAcASQAcARAIAhQAGAhgRAcQgLAQgOAJQARgHASABQAiABAWAZQAXAZgCAgQgBAhgZAXQgYAWgigBQgTgBgSgKQARALAJASQAPAdgKAgQgKAggdAQQgSAJgTAAQgMAAgNgEgAgkhHQgdAQgKAgQgLAfAQAdQAPAeAgAKQAfAKAdgQQAdgPAKggQALgfgQgdQgPgegggKQgNgEgLAAQgSAAgSAJg");
	this.shape_21.setTransform(-44.1,-54,0.485,0.485);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#EC8721").s().p("AAzD1QglgIgWgfQgPARgVAKQgWAJgYgBQgcgCgYgPQgYgQgMgYQgNgYABgdQABgUAGgQQgWgFgSgPQgTgOgLgUQgNgYABgcQADgrAggeQAWgVAjgFQgMgkAOgkQAPgjAigSQAjgSAlAJQAlAJAWAeQAVgYAhgIQArgJAkAXQAYAPANAZQALAUABAYQABAXgJAWQAhAHAWAYQAKAMAGALQANAYgBAcQgDArggAeQgYAWghAEQAMAkgOAkQgPAjgiASQgXAMgYAAQgMAAgNgDg");
	this.shape_22.setTransform(-44.1,-54,0.485,0.485);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFEC00").s().p("AhEFOQgtgJgagnQgagoAJguQAGgeATgVQgfAigvADQguACgjgfQgjgfgCgvQgDgvAfgiQAngtA5AFQgWgGgTgRQgjgfgDgvQgCgvAfgjQAfgkAvgCQAvgEAjAgQAUASALAcQgIgcAGgcQAJguAngaQAngaAuAKQAuAJAaAnQAaAngKAvQgGAagRAWQATgTAagJQAtgPAqAVQAqAVAPAtQAPAtgVAqQgWApgsAPQgYAIgbgEQAaAIATASQAjAfADAvQADAwggAiQgfAkgvACQguADgkgfQgVgTgKgbQAIAbgGAcQgJAvgnAaQgcATghAAQgMAAgMgDgAg9heQgnAagKAuQgKAtAaAoQAaAnAuAJQAtAKAogaQAngaAJgvQAKgtgagnQgagngugJQgNgDgLAAQggAAgcATg");
	this.shape_23.setTransform(38.6,-51.6,0.485,0.485);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#EC8721").s().p("AhKFwQg2gLghgrQghgqACg2QggAFgfgJQghgJgYgWQgfgbgMgmQgMglAIgnQAIgnAagcQATgUAWgNQgVgagHggQgIggAHggQAIgmAageQApguA9gEQAugDAoAZQAUgyAvgaQAugaA2ALQA1ALAhArQAhAqgCA2QAvgHApAUQA3AcATA6QANAlgIAnQgHAggTAaQgUAbgdAQQAdAkADAvQABAXgEAQQgHAngbAdQgoAug+AEQgvADgngZQgUAygvAaQggASglAAQgPAAgPgDg");
	this.shape_24.setTransform(38.5,-51.6,0.485,0.485);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#7C1A1C").s().p("Ajrh+QAzBCDWAOQBsAHBigHQgQAxjiBEIjfA4g");
	this.shape_25.setTransform(71.2,-0.1,0.485,0.485);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#7C1A1C").s().p("AACA+QjohLgOgzIBBAFQBOAEBHgBQDfgGA0hAIgND9Qhxgch1glg");
	this.shape_26.setTransform(-71.6,-1.2,0.485,0.485);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("ArYjKIBCgKQDMgdCThHQCThHCWiOIBXhTIAgB1QAaBhAKBrQAHBUgDBvQBCAHA8ABQBlABCcgQIDJgUIiOCPQj9EAkjCOQkiCMlmAnIhMAIgAkXj3QieBNjWAeIAnKcQFaglEWiHQEXiHD0j3QhPAIg3ADQhHAFg8gCQhngBhggRQAFiHgGhXQgHh2gchmQidCVidBMg");
	this.shape_27.setTransform(92,1.6,0.485,0.485);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.lf(["#BC1A28","#DA1421"],[0,1],-58.3,32.7,36.4,-59.2).s().p("AqUi4IAhgGQDSgeCXhKQCYhICZiTIAsgpIAQA6QAcBlAIByQAGBVgDB6QBKALBYABQBnABCegPIBkgLIhHBIQj3D7keCLQkdCKlfAlIgmAFg");
	this.shape_28.setTransform(90.5,2.3,0.485,0.485);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AJKJgQlkgvkfiUQkfiUj3kHIiKiSIDIAZQCkAUBdABQBDABA7gGQAAhwAJhTQAMhrAdhgIAjh0IBVBVQCSCRCRBLQCSBKDLAjIBBALIhCMqgAgYFcQETCOFZAuIA3qbQjVglichPQichQiYiZQgfBlgKB1QgIBVACCKQhdAPhrgBQhlgCikgUQDvD9ETCOg");
	this.shape_29.setTransform(-91.9,-0.2,0.485,0.485);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.lf(["#BC1A28","#DA1421"],[0,1],59.3,29.3,-59.2,-29.3).s().p("AIzIuQlegukZiRQkbiSjxkAIhFhKIBkAMQChAVBjABQBVABBOgKQgBh6AJhVQALhxAehkIARg6IArArQCWCVCVBNQCVBNDSAkIAhAFIg9Lig");
	this.shape_30.setTransform(-90.6,0.5,0.485,0.485);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("ABIFZQg0gMgggrQgfAjgtAKQg7AOg0giQgigVgSgjQgPgdgBghQgCghANgeQgugKgggjQgMgNgKgSQgSgjACgnQACg9AtgpQAigfAvgHQgQgyAUgyQAUgyAwgZQAwgZA1AMQA0AMAfArQAWgYAegNQAegNAhACQAoABAiAWQAhAWASAiQASAjgCAoQAAAcgKAWQAgAIAaAUQAaAUAPAcQASAjgCAnQgDA9gtApQgiAgguAFQAQAzgUAyQgUAygwAZQghARgiAAQgRAAgRgEg");
	this.shape_31.setTransform(-44.1,-54,0.485,0.485);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("A30QmIBiiuQAVglAQgXQhchdg3h2Qg3h3gLiCQgRjFBUixQA/iHBshiQBshjCLgyQCag4CjAQQA8jhCxiWQCziXDrgUQAmgDAhAAQC9ADCmBeQAPgeAXgaQAkgoAvgXQAwgXA1gEQAYAAAXACQAmgkAwgTQAxgUA0ABQAYAAAaAFQBCAOAzAqQAyApAZA8QAYAHATAKQAwAYAiAoQAjAoARAzQAWBCgOBHQgMA6gkAwQAEARADAUQCbBTBnCTQBxCiARDEQALCDgjB/QgiB+hMBrQB2BzA4CcQARAvAJAoIAhCTgAwMilQhfAhhJBEQhJBCgrBbQg5B7ALCEQAKBuA3BhQA3BgBaBBIBxBQIghAiMAk2AAdQg3hbhZg9Ih1hRIBlhlQBRhPAmhpQAnhpgKhwQgKiEhNhuQhZiAiOg3IhqgoIAkhuIABgIQAAgJgHgIIhZhvIB9hDQANgIADgNQABgIgCgHQgEgMgLgFQgIgEgJABIiNAWIAFiPQAAgKgGgIQgGgJgLgCQgLgCgJAFQgJAFgEAKIg0CFIh5hMQgJgEgIAAQgMABgIAJQgGAGgBAIQgDAOAJAKIBVBtIh4BDIheBRIhOhXQhGhPhggsQhggthngBQgQAAghACQi3AQiBCBQiBCBgQC4IgMCOIiJgmQhCgSg/gBIgGAAQhXAAhPAeg");
	this.shape_32.setTransform(5.4,-22,0.485,0.485);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("A0cOyQAshNA3g4QhxhQhEh4QhDh3gMiHQgOilBGiWQA1hwBbhTQBahTB1gqQBbggBggEQBegDBcAaQATjgCfigQCgijDjgTQCTgNCKA5QCEA2BgBsQAOgMALgGQgVgagHggQgIgfAHggQAIgmAageQApguA9gEQAugDAoAZQAUgyAvgaQAvgbA2ALQA1ALAhArQAhArgCA1QAvgHApAVQA3AbATA7QANAlgIAnQgHAggTAaQgUAbgdAQQAdAlADAvQABAWgEARIgEAQQBXAhBIA5QBJA5A2BOQBfCIAOCkQALCIgvCCQgwCDhjBiQBPA3A6BLQA8BMAhBcQAMAiAJAmg");
	this.shape_33.setTransform(4.6,-22.1,0.485,0.485);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.logospecialissimi, new cjs.Rectangle(-127.3,-75.4,254.7,137.1), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1D1D1B").s().p("EAguADVQgWgLgOgUQgOgVgGgaQgGgaABggQABgeAKgZQAJgYARgSQARgTAVgJQAWgJAaAAQARAAAMAGQALAFAKALQAKALAGALQAGANAEAMQAKAfAEAoIitAAIAAAJQAAAMADAVQADASAIATQAIASAQANQAQAMAZABQAaACAPgIQAPgHAJgKQAKgLAFgOIAJgBQgEATgKAPQgJAMgTALQgTAKgfAAQggAAgXgLgEAhLgARQgNAHgKANQgKANgFAPQgFANgDARIAaABQAOAAATgBIAjgEQATgDALgFQABgMgBgNQAAgNgFgLQgFgLgJgHQgKgHgQAAQgUAAgNAIgAVvDVQgWgMgPgTQgOgUgGgbQgGgaABggQADg9AigkQAjglA0AAQAcAAAQAIQAQAIAKANQAJAMAEANIAGAUQAAAXgHAIQgHAIgHABQgKABgKgHQgMgKACgJQACgKAHgIQAHgIANgIQgFgJgMgKQgMgLgcgBQgYgBgQAOQgQAOgKAUQgKAXgEAUIgFAkQAAAMADATQADASAIARQAIAPARANQARAMAYABQAXABANgGQAMgGAJgJQAIgJAFgNIAKgBQgEATgKAPQgKANgSAKQgTAKgfAAQggAAgXgLgAPMDVQgXgMgNgTQgOgTgGgcQgHgaACggQABgeAKgZQAJgYARgSQARgTAVgJQAWgJAaAAQARAAAMAGQALAFAKALQAKALAGALQAGANAEAMQAKAfAEAoIitAAIAAAJQAAAMADAVQADASAIATQAIASAQANQAQAMAZABQAZACAQgIQAPgHAJgKQALgLADgOIAKgBQgEATgKAPQgKANgSAKQgTAKgfAAQggAAgXgLgAPpgRQgPAJgIALQgIALgHARQgFAOgDAQIAaABQAOAAATgBIAjgEQATgDALgFQABgMgBgNQAAgNgFgLQgFgLgJgHQgKgHgQAAQgTAAgOAIgAMUDgIAAgNQAIgBAHgFQAFgDAGgIQAFgHACgMIABgLIAAk8QgCgLgFgGQgFgGgEgBQgGgDgHACIgGgIIBEgmIAAF9IABARQABAMAFAHQAGAIAGADQAHAFAIABIAAANgAG0DVQgXgMgNgTQgOgVgGgaQgHgaACggQABgeAKgZQAJgYARgSQARgTAVgJQAWgJAaAAQARAAAMAGQALAFAKALQAJAJAHANQAGANAEAMQAKAfAEAoIitAAIAAAJQAAAMADAVQADASAIATQAIASAQANQAQAMAZABQAZACAQgIQAPgHAJgKQAKgLAFgOIAJgBQgEATgKAPQgKANgSAKQgTAKgfAAQggAAgXgLgAHRgRQgPAJgIALQgIALgHARQgFAOgDAQIAaABQAOAAATgBIAjgEQATgDALgFQABgMgBgNQAAgNgFgLQgFgLgJgHQgKgHgQAAQgTAAgOAIgACxDgIAAgNQAGAAAGgEQAEgCAGgGQAFgFADgJIAAjCQgBgLgFgIQgGgHgFgEQgHgEgIgCIAAgMIBBAAIAAAxQALgSAZgPQAXgQAkgBQAHABAIAEQAGADAEAHQAGAHgCAMQgBAHgDAEQgCAEgGAEQgFAEgIgBQgLAAgGgFQgEgEgDgHQgCgIAAgHQgOgFgMAEQgMADgLAKQgNALgLAWIAACsQADAKAFAFQAGAGAEACQAGAEAIAAIAAANgABTDXQgMgIgEgLQgGgNACgPIAAjSIgrAAIAAgOQAXgCAOgLQAOgJAIgNQAIgLADgTIAGAAIAABCIBBAAIAAANIhBAAIAADSIABAKIAEANQADAHAFADQAGAFAJAAQANAAAIgEQAIgEAHgFQAHgGAFgIQABAMgFALQgFAJgLAGQgLAHgXAAQgYAAgLgJgAhkDgIAAgNQAIgBAHgFQAHgFAEgGQAFgGACgNIABlHQgCgMgFgFQgFgGgEgBQgFgDgIACIgGgIIBEgmIABGOQABAMAFAHQAGAHAGAEQAHAFAHABIAAANgAriDVQgXgMgOgTQgNgTgHgcQgGgbACgfQABgeAJgZQALgZAPgRQAQgSAXgKQAVgJAbAAQAQAAAMAGQAMAGAJAKQAJAIAHAOQAHANAEAMQAKAfADAoIisAAIAAAJQgBAOADATQAEAWAIAPQAIASAQANQAQAMAYABQAaACAPgIQAPgHAKgKQAJgKAFgPIAKgBQgEAUgLAOQgJAMgTALQgSAKgfAAQghAAgWgLgArGgRQgOAJgJALQgJANgGAPQgEAOgEAQIAbABQAOAAATgBIAjgEQASgDALgFQACgMgCgNQgBgOgEgKQgEgLgKgHQgJgHgQAAQgUAAgOAIgAuQDgIAAgNQAIgBAHgFQAHgFAEgGQAFgGACgNIAAiQQgBgSgFgMQgFgLgKgJQgKgKgSAAQgyAAgcAuIABCeQABAMAFAHQAGAHAGAEQAHAFAIABIAAANIhlAAIAAgNQAJgBAGgFQAGgDAGgIQAFgIABgLIABgPIAAiSIgBgNQgBgLgFgJQgGgKgGgFQgGgHgJgFIAAgMIBDAAIAAAwQAEgGAIgIIATgQQANgIALgEQANgFAQAAQAoABASAZQASAbAAAjIAACQQABAMAFAHQAGAHAGAEQAHAFAIABIAAANgA7WDgIAAgNQAGAAAGgEQAEgCAGgGQAGgGACgIIAAjCQgBgMgFgHQgFgHgGgEQgGgEgJgCIAAgMIBBAAIAAAxQAMgTAYgOQAYgQAjgBQAIABAHAEQAFADAGAHQAEAHAAAMQgCAIgDADQgCAEgFAEQgGAEgHgBQgMAAgFgFQgGgFgCgGQgCgIAAgHQgOgFgMAEQgMADgLAKQgMAKgMAXIAACsQADAKAFAFQAFAGAFACQAGAEAIAAIAAANgA+ADVQgXgMgOgTQgOgTgGgcQgGgaACggQABgeAJgZQAKgYAQgSQAQgSAXgKQAWgJAaAAQAQAAAMAGQAMAGAJAKQAJAIAHAOQAHANAEAMQAKAfADAoIisAAIAAAJQgBAPADASQADAVAJAQQAIASAQANQAQAMAYABQAaACAQgIQAOgHAKgKQAJgKAFgPIAKgBQgEAUgLAOQgKANgSAKQgSAKgfAAQghAAgWgLgA9kgRQgOAJgJALQgIALgHARQgEAOgEAQIAbABQAOAAATgBIAjgEQASgDAMgFQABgMgBgNQgCgPgEgJQgEgLgKgHQgJgHgQAAQgUAAgOAIgEgiRADgIAAgBIgDAAIAAABIgxAAIAAgNQAGAAAHgEQAFgCAFgGQAFgFACgKIAAk1QgCgKgFgFIgKgJIgNgFIAAgMIAxAAIAAAAIBrAAIAQAEQAOADAQAMQAQALAOAXQAOAWAAAkQAAAlgSAUQgSAVgUAKQgXAMggAEIhAAAIAACHQABAJAGAGQAGAGAFACQAGAEAGAAIAAANgEgh+AAgIA6AAQAVgBARgKQAOgIAMgQQANgSAAghQAAgfgNgTQgMgSgOgLQgSgMgUgEIg6AAgAcuDWIAAhBIAJABIAEALIAFAKQADAGAEADQAIAFARAEQASAFATgCQATgBAPgJQAOgJAAgVQAAgVgJgLQgLgNgOgGQgQgIgRgFQgQgEgRgIQgPgJgKgNQgKgOAAgXQAAgbAWgXQAWgXAmgBQAlgCAXAEIAXAGIgIA7IgHgBIgMgUQgHgJgGgGQgIgHgKgCQgVgDgNAEQgMAEgJAGQgJAIgDAJQgJAVAJAMQAIANAQAJQAQAIAVAIQAUAHATAMQATAMALARQALARgDAdQgBATgJAMQgIAMgNAIQgPAHgOADQgNADgTABIgMAAQghAAgpgJgA4SDWIAAhBIAIABQABAGADAFIAFAKQADAGAFADQAGAFATAEQASAFASgCQATgBAPgJQAPgJAAgVQAAgUgKgMQgKgMgPgHQgOgHgTgGQgOgDgTgJQgOgIgLgOQgJgNAAgYQAAgcAWgWQAWgXAlgBQAlgCAXAEIAXAGIgIA7IgHgBIgMgUQgFgHgIgIQgIgHgKgCQgVgDgNAEQgNAEgIAGQgJAIgDAJQgIAVAIAMQAIANARAJQARAJAUAHQAUAIASALQASALAMASQALARgDAdQgBASgJANQgJAMgMAIQgOAHgPADQgNADgTABIgMAAQghAAgogJgAaBDdQgagCgVgLQgWgLgQgSQgRgSgJgXQgJgXAAgbQAAggALgcQALgbAUgSQATgTAagJQAZgKAcAAQALAAAPADQANADALAEQApAPAaAfQAcAiAAAuQAAAggQAfQgPAegYATIgMAIQgKAGgLADIgaAJQgOAEgRAAgAZwgWQgRAMgOARQgNASgIAXQgHAYAAASQABAcAKAWQAJAUAPAQQAPAOATAHQASAHARgBQAUgBASgMQASgLAOgSQAOgRAHgVQAIgUgCgUQgDgdgKgVQgKgXgPgOQgQgPgRgIQgRgHgRAAQgUAAgRAMgAkHDeIgKgBQgbgCgUgLQgXgLgQgSQgQgSgKgXQgJgXAAgbQAAggALgcQAMgbAUgSQATgTAZgJQAZgKAcAAQALAAAPADQAOADAKAEQApAPAbAfQAbAiAAAuQAAAigPAdQgPAegYATIgMAIQgMAGgJADIgbAJQgNAEgSAAIgJgBgAkjgWQgRAMgOARQgNAUgHAVQgHAYAAASQABAcAJAWQALAWAOAOQAOAOATAHQASAHARgBQAUgBASgMQASgLAPgSQANgRAIgVQAHgSgBgWQgDgdgKgVQgLgXgPgOQgPgPgRgIQgRgHgSAAQgTAAgSAMgAzhDdQgagCgVgLQgWgLgQgSQgRgSgJgXQgJgXAAgbQAAggALgcQALgbAUgSQATgTAagJQAZgKAcAAQALAAAPADQANADALAEQApAPAaAfQAcAiAAAuQAAAggQAfQgPAegYATIgMAIQgKAGgLADIgaAJQgOAEgRAAgAzygWQgRAMgOARQgNASgIAXQgHAYAAASQABAcAKAWQAJAUAQAQQAOAOATAHQASAHARgBQAUgBASgMQASgLAOgSQAOgRAHgVQAIgUgCgUQgDgdgKgVQgKgXgPgOQgQgPgRgIQgRgHgRAAQgUAAgRAMg");
	this.shape.setTransform(8.7,11.2,0.174,0.174);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FEEB34").s().p("AiRIwQg9g8AAhWQAAgcAGgXQAGgXAOgaQgrBJhSAVQhSAVhJgrQhKgqgWhTQgWhUArhJQA1hdBogLQgsgEgmgXQhKgqgWhUQgWhTArhJQArhLBSgWQBTgWBKAqQAsAbAcAsQgOgZgFgYQgGgWAAgcQAAhVA9g8QA8g+BVAAQBVAAA9A+QA8A8AABVQAAAbgFAVQgFAXgNAZQAcgqArgaQBKgqBSAWQBTAWArBLQAqBJgWBTQgWBUhKAqQgWANgTAGQgVAGgaACQAaABAVAIQATAGAXANQBKArAWBSQAWBTgrBLQgrBKhSAWQhTAWhKgrQgXgNgQgPQgSgRgPgYQANAaAGAXQAFAVAAAbQAABWg8A8Qg9A+hVgBQhVABg8g+gAiRiRQg9A8AABVQAABWA9A8QA8A9BVAAQBVAAA9g9QA8g8AAhWQAAhVg8g8Qg9g9hVAAQhVAAg8A9g");
	this.shape_1.setTransform(-41.2,-3.2,0.174,0.174);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#EF8623").s().p("AiuJsQhKhAgRhgQg3AVg7gFQg8gEg1gfQg/glgkhAQgig+AAhHQAAhIAjg/QAZgrAjgdQgugngZg2QgYg3AAg7QAAhHAjg/QAbguAqghQAqghA0gOQBTgWBPAeQARhgBKhAQBMhABiAAQBiAABMBAQBKBAAQBgQBRgeBRAWQA0APAqAfQArAiAaAuQAkA+AABIQAAA8gZA2QgZA3gvAmQBDA3AWBSQAJAlAAAhQAABIgkA/QgbAvgqAhQgrAfg0APQhSAWhQgeQgQBghLBAQhLBAhiAAQhiAAhMhAg");
	this.shape_2.setTransform(-41.2,-3.2,0.174,0.174);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#E01021").s().p("AklFQQiHiHABjOQgBjBCHiHQCFiHC+AAQAkAAAhAJQAuALAZAaIAAgdIC5AAIARAEQARAJAAAUIADEXIjeAAQgGg9hEgYQgVgIgZgDIgUgCQhigBhABGQg8BCgBBhQAABlA4BAQA/BGB1AAQBDAAAvgpQAlgfAhhBIDJCBQg+BuhtBEQhvBFh0AAQjAAAiDiFg");
	this.shape_3.setTransform(-21.1,-3.2,0.174,0.174);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#E01021").s().p("Am2HUIAAitQAAgXAngLQAUgFATAAIAAoGIhOAAIAAioQAAgZAngIQAUgEATAAIF8AAQC5ABB3CJQByCEAADFQAADGhyCFQh3CJi6AAgAiDDkICVAAQBZgBAyhEQAvg+gBhkQAAhlgug/QgyhEhZAAIiVAAg");
	this.shape_4.setTransform(44.6,-3.2,0.174,0.174);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E01021").s().p("AByHVIAAitIAIgUQAQgTAnAAIgVguIk5AAIgWAuQAoAAAQATQAIAKAAAKIAACtImBAAIAAitIAJgUQAPgTAnAAIDpoGIhBAAIAAioIAKgTQATgUAxAAIE/AAIEzLVIAhAFQAhAJgBAZIAACtgAhlAPIDKAAIhlj5g");
	this.shape_5.setTransform(27.1,-3.3,0.174,0.174);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E01021").s().p("AChHVIlAnUIAAEAQAxAAAUAUQAKAJAAAKIAACtImFAAIAAitQAAgYAogKQAUgFATAAIAAoGIhPAAIAAioIAMgTQAVgUAuAAIDnAAIFAHjIAAkUIhMAAIAAioIAJgTQATgUAwAAIDnAAIAmAEQAmAKABAZQABApgBB/IhNAAIAALag");
	this.shape_6.setTransform(10.3,-3.3,0.174,0.174);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E01021").s().p("AlDFLQiGiJAAjCQAAjBCGiJQCHiJC8AAQC+AACGCJQCGCJAADBQAADCiGCJQiGCJi+AAQi8AAiHiJgAiQinQgzBAAABkQAABjAzBAQA3BEBaAAQBaAAAyhEQAug/AAhkQAAhlgug/QgyhDhaAAQhbAAg2BDg");
	this.shape_7.setTransform(-5.8,-3.3,0.174,0.174);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-52.1,-15,104.3,30.2), null);


(lib.grigliatetx = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1D1D1C").s().p("A3tJdQgGgBgHgDQgGgEgCgFQgEgKABgQIAjl6QABgKADgJQAFgKAGgEQAIgGALgCIATgCIATAAQAJAAAJAEQAIACAFAHQAGAJADANIApC7IARBOQAHAlALArIAGAdQADAOgDAKQgDAJgHADQgIAEgJABQgIABgKgDQgJgDgFgGQgDgEgCgGIgIgcQgEgJgCgDQgHgLgMgEQgLgEgMACQgKABgMAHQgKAGgEAIQgFAJAAAHIgHAgQgDAIgHAEQgEAEgJABIgJABIgFAAgA2nEaQgHABgEAHQgEAJgBAGQgBAJAAAJIgDA1QgCASABAPQACASALAOQAKAMATgHQANgFADgNQAFgNgCgRQAAgQgEgSIgKgwQgBgIgEgKQgDgJgFgEQgDgEgFAAIgFABgAztJLQgKgBgGgLQgEgGgCgQIgWl9QAAgLACgIQACgHAHgGQAFgFAMgBQAIgCAIACQAIABAGAHQAEAFADAKIAEAuQAAANABAKQAEApADA0IAGB/QAAALADASQADAOAHAJQAGAKANAEQAJAEALgBIATAAQAIAAAJADQAHACAGAIQAIALgDAPQgBAPgJAHQgLAIgTAAIgpACIgmACIgGAAIgUgBgAwuI/QgKgBgGgLQgFgIgBgOIgWl9QAAgKACgJQADgIAFgFQAGgFAMgBQAGgBAKABQAJACAFAGQAFAGABAJQADAKAAALIADAxQAFA+ABAeIAHB/QABARACAMQADAOAGAJQAHAKAMAEQAJADALAAIAUAAIARADQAIADAEAHQAIALgCAPQgCAQgJAGQgKAIgUAAIhOAEIgLABQgJAAgGgCgAsmIxQgHgBgFgEQgGgDgCgFQgFgKACgQIAil6QACgLADgIQADgJAHgFQAGgGANgCIATgCIATAAQALABAHADQAIADAFAGQAGAJADANIApC6IARBPIAYBtQADANgCALQgEAJgHADQgIAEgJABQgIABgKgDQgJgDgEgGQgEgDgCgHIgIgcIgGgMQgHgLgMgEQgKgEgNACQgLABgKAHQgKAGgFAIQgFAIAAAIIgDARIgEAPQgCAIgHAEQgGAEgIABIgIABIgGAAgArgDuQgGABgEAHQgEAIgCAHQgBAJAAAJIgDA1QgCASABAPQADATAKANQALAMASgHQANgFAEgNQAEgNgBgRIgFgiIgJgwQgDgMgDgGQgDgJgFgEQgDgEgFAAIgFABgAohIgQgIgDgFgEQgGgEgEgHQgEgJAAgOIgIiOQgCgUAAgYQAAgfgDgZIgEg0QgCgNABgMIgCgdIgCghQgBgOAJgIQAEgGAIgBIARgDQAVgDAWgCQAagBASABQATAAATAGQASAGALALQAJAJAHARQAGAQADATQADARgBAVQgCAUgFAQIgMAYQgEAJgBAGQgCAGABAKQABAJAEAIIATAcQAFAJACAJQAHAZAAAiIADA/IACAVQABAKgEAIQgEAGgGADQgIAEgHAAQgIABgJgDQgHgCgGgGQgFgFgDgKQgDgJgBgLQgCgLAAgNIgBgaIgFgwQgCgWgJgNQgFgHgKgHQgKgFgOAEQgLADgEAIQgFAIgCALQgBAIAAASIAFBTQACATgBAPQgBAQgLAIQgHAFgIAAIgGABIgJgBgAnrCWQgFAAgGACIgHAEQgJAJgCANQgBARABAQQAAAQAEAPQAEAOAJAHQAPALASgIQAQgHAGgUQAFgUgDgUQgDgVgMgPQgKgOgQAAIgEABgAktIOQgIgCgFgHQgGgHgBgPQgCgNABgOIgCgcIgDgZIgCgdIgMjXIgCgeQgDgbACgRQADgSAVgFQAKgBAIACQAJABAFAGQAGAGADANIAEAbIAUFqQABAMgEALQgDAGgIAEQgJAEgGABIgGAAQgGAAgFgCgAjJILQgGAAgHgEQgFgDgDgGQgEgJABgQIALhtIAHhTIARi6QABgLADgJQADgIAHgGQAIgGAMgBIATgDIATAAQAJABAJADQAIADAFAHQAGAIADAOIAoC6IASBPQAHAlALArIAFAcQADAPgDAJQgDAJgHAEQgHAEgJABQgJAAgJgDQgJgDgFgFQgEgEgBgGIgJgcIgFgNQgIgLgLgDQgKgEgNABQgKACgMAGQgJAGgFAJQgEAGgCAKIgCAQQgCAIgDAIQgCAHgHAFQgFADgIACIgJABIgFgBgAiDDIQgHACgEAHQgDAGgCAJIgEBHQgCAVABAMQACATAKAMQALANATgIQANgEADgOQAEgNgBgQQAAgRgEgSIgPhCQgEgJgEgEQgEgDgFAAIgEAAgACqH0QgHAAgGgEQgFgDgDgGQgFgJACgQIALhtIAHhTIARi6QABgLADgJQADgIAHgGQAHgFANgDIASgCIAUAAQALABAHADQAIADAFAHQAGAIADAOIAoC6IASBPIARBQIAHAcQADAOgDAKQgDAJgIAEQgHAEgJABQgJAAgJgDQgJgDgFgFQgDgEgDgHIgIgbIgFgNQgIgKgLgEQgLgEgMABQgLACgLAGQgJAGgFAJQgEAGgCAKIgCAQIgFAQQgCAHgHAFQgFADgIACIgIABIgGgBgADwCxQgHACgEAHQgDAFgCAKQgCAIAAAJIgCA2QgCAVABAMQACATAKAMQALANATgIQANgEADgOQAEgNgBgQIgEgjIgKgwQgCgMgDgGQgDgJgFgEQgEgEgFAAIgEABgAGrHhQgIgDgGgIQgFgIgBgMIgDg6QABgNgCgNQgDgagCg1IgOjdQgBgOAGgKQAGgIAGgCIARgDQAagEAYAAQAfgBASACQAYADAPAIQAQAJAKAOQALARAFATQAGAXACAZQADAcgCAUQgCAXgHASQgGAUgNANQgOAMgUAGIgnAJQgKACgGAEQgIAEgEAHQgIANAAAVQAAAVACAVIADArIABAVQABAKgEAHQgDAIgIADQgHAEgKABIgDAAQgHAAgIgCgAHoBcIgMAEQgFACgEAEQgGAHgCAPQgCAPAAARQABARAEAQQAEAQAFAHQAIAIAKACQALADAJgFQALgEAHgMQAHgMACgOQADgPgDgQQgBgPgHgOQgFgMgLgIQgIgGgKAAIgGAAgAKbHSQgKgDgEgIQgFgHgCgPIgXl+QAAgKACgJQADgIAHgEQAHgFAOgCQAKgCATgBIBPgEQASgCAJAKQAFAEADAJQADAJgBAHQAAAIgDAHQgDAHgHAFQgHAEgKABIgTACQghADgNAOQgNAOADAjQADAVAHANQAHAOASADQAKADAIgBIASABIAQADQAIADADAIQAGAKgCANQAAANgIAIQgEAEgHACQgHADgGAAIgOACQgGAAgIADQgTAHgGAPQgHAQACAaQACAWAGAPQAGAQAQAGQAKAEAMAAIAqgBQALABAGAGQAFAEACAIQADAGAAAKQAAAIgDAHQgDAHgGAEQgGAFgJABIhXAGIgaABQgMAAgKgDgAN3HHQgFgBgIgFQgGgEgDgHQgEgKAAgOIgJiOQgCgbAAgRQAAgcgCgcIgFg0QgBgMAAgNIgEg+QAAgOAIgIQAEgFAIgCIA8gGQATgCAZABQAWABARAEQARAFALAMQAJAJAHARQAGAQADATQADAWgBAQQgCAVgFAPIgFAMIgHANQgDAFgCAJQgCAJABAHQABAKAFAHQADAHAGAHIAKAOQAEAHACALQAHAbAAAgQABAlADAbIABAUQABALgEAHQgDAFgHAEQgIAEgHAAQgKAAgGgCQgJgCgEgGQgGgGgDgJIgEgUIgDgyQgBgZgDgWQgDgWgJgOQgHgJgIgEQgJgGgPAEQgKADgFAIQgFAKgCAKQgBAMAAANIAFBTQADATgCAPQAAAPgMAJQgHAEgHACIgGAAQgGAAgEgBgAOtA9QgIABgDABIgHAEQgJAJgCAOQgBAMABAUQABASAEANQADAPAJAHQAPAKASgIQARgHAFgTQAFgTgDgWQgDgVgMgPQgKgNgQAAIgEAAgASfG1QgIgDgFgIQgEgGgDgKIgTkwQgBgJgFgOQgEgLgIgGIghgQQgGgFgCgDQgHgOADgOQADgOAJgFQAJgHAQAAQAQAAANgCIAXgCIAfgCIAbAAQAOgBAHAEQAKAFAFANQAEAPgGANQgEAIgGAEIgaAPQgGAFgDAHQgEAGgBALQgBAKABALIACAXIABAXQABA1ADAlQAFA5ABAfIAFBFQAAALgDAIQgDAIgHAEQgIAFgIABIgDAAQgHAAgIgBgAU3GsQgHAAgGgEQgGgEgCgFQgEgKABgQIALhsIAHhTIARi6QABgLADgIQAEgJAGgFQAHgFANgDIATgCQAIgBALABQAIAAAKAEQAJAEAEAGQAGAHADAOIA6EIQAHAmALAqIAGAdQADAPgDAJQgDAIgIAFQgHAEgJABQgKAAgIgDQgIgCgGgGQgDgEgCgHIgEgNQgCgIgDgGQgCgHgDgGQgHgKgMgFQgMgEgLACQgLACgLAGQgKAGgEAIQgFAKgBAGIgGAhQgDAHgHAEQgHAFgGABIgIABIgGgBgAV9BpQgHACgEAGQgDAGgCAJQgBAJAAAJIgDA2QgCAVABALQACATALANQAKANATgIQAMgEAEgOQAFgNgCgRQAAgRgEgRIgKgwQgBgHgEgLQgDgIgFgFQgDgDgFAAIgFAAgAuFEOQgHgBgHgGQgFgGgDgKQgEgJABgLQAAgJADgMIAGgLIAOgZQACgHAGgBQAIAAAFANQAEANACAPIACAYQABALgCALQgCAKgGAGQgFAFgIAAIgFAAgAtYgkQgKgCgJgEQgJgFgHgGQgGgGgFgJQgOgXgEgfQgGgggCghIgIiIQgCgmAAgcQABghAKgYQAKgYAUgQQAUgQAegEQAsgGAeATQAdATAKAoQAEAOAAAOQACAQgGAKQgHALgPACQgPADgKgJQgEgDgDgHIgKgdQgCgHgEgFQgFgHgIgFQgIgGgPADIgLAFQgFAEgGAIQgGALgCAQQgCAQABAVIALB+IABAnIABAeQACARAEAKQAEAOAHAHQAIAIAMABQARADAKgLQAKgJAEgQQADgPgCgRQgBgQgGgLQgEgJgGgGQgEgEgHgLIgHgNIgDgOQAAgJADgFQACgHAHgEQAEgEAMgCIAWgDIAWACQAKABAEAEQAHAHADAOIALCVQABAVgBAQQgBAQgPAHQgIADgHgBIgPgCIgQgEQgJgCgHABQgOADgKAHQgLAHgKACQgIACgIAAIgHAAgAqMg7QgIgCgFgEQgFgDgEgIQgEgJAAgOIgJiPQgBgTAAgZQgBgegCgaIgFg0QgBgMAAgNIgBgcIgDghQAAgOAIgJQAEgEAIgDIA9gHQAUgCAXABQAUABATAGQARAFALAMQAKAKAGAQQAGAPADATQADASgBAVQgBAUgFAQIgNAYQgEAIgBAGQgCAGABALQACAKAEAGIATAdQAFAIABAJQAHAaABAiIADA/IACAUQAAALgEAHQgDAGgHADQgIAEgHAAQgIABgIgCQgIgDgFgFQgFgGgDgJQgDgKgCgLQgBgLAAgNIgCgZQgBgZgDgXQgCgWgKgOQgFgHgKgGQgJgGgPAFQgKADgFAIQgFAHgBAMQgCAIAAASIAFBSQADAUgBAPQgCAPgLAIQgGAFgIABIgGABQgGAAgEgCgApWnFIgKADIgIAEQgJAIgBAOQgCARABAPQABARAEAOQADAOAKAIQAPALASgIQAPgHAGgUQAGgVgEgUQgDgUgLgQQgKgNgRAAIgEAAgAkJhJQgKgBgJgFQgIgEgIgHQgIgJgDgGQgOgXgEgfQgGghgBggIgJiHQgCgfAAgkQAAggALgZQALgYATgQQAUgQAegEQAtgGAdATQAeATAJAoQADANACAQQABAQgGAJQgGALgQACQgPADgKgIQgEgEgDgHIgFgOIgFgOQgCgIgEgEQgEgHgJgFQgIgGgPACQgEABgHAFQgFADgGAIQgGALgCAQQgCASABATIALB+QABAVAAASIACAfQAAANAFAOQAEANAHAHQAIAIAMACQASACAJgKQAKgKAEgQQADgRgCgOQgBgQgGgMQgEgIgGgHQgFgEgGgLIgHgMQgCgIgBgHQAAgJADgFQACgHAHgEQAGgEAKgCQAMgCAKAAQAMgBAKACQAJACAFAEQAIAHACAOIADAdIAIB3QABAVgBARQgBAQgPAGQgGADgJAAIgfgHQgJgCgHACQgMACgMAHQgLAHgKACQgKADgHAAIgGgBgAmXhMQgIgDgGgGQgFgIgCgOQgBgNABgOIgCgcIgEgaIgBgdIgMjXIgDgdQgDgcADgQQACgSAWgFQAJgCAJACQAIACAGAFQAFAGADANIAEAcIAUFpQABAPgEAIQgDAHgHADQgJAFgHAAIgGABQgFAAgFgCgAhBhgQgKgBgGgLQgFgHgBgPIgUlIQgCgOAAgPIAAgYQAAgKACgJQADgJAFgEQAHgFALgCQAIgBAIACQAIABAGAHQAFAFABAKQADAKAAALIADAwIAHBdIAFBeIABAhQAAAQADANQADANAGAKQAHAKALAEQAKAEAKgBIAUAAQAIAAAJADQAHACAFAIQAIALgCAPQgCAPgJAHQgLAIgTAAIgnACIgmACIgHAAIgTgBgAB7htQgIgDgFgGQgGgHgBgPQgCgNABgOIgCgcIgDgaIgCgdIgMjXQAAgNgDgQQgDgaADgSQACgSAWgFQAKgCAIACQAJADAFAFQAGAGADAMQACAMABAQIACAeIATFLQABAPgFAIQgCAGgIAEQgGAEgKACIgEAAQgGAAgGgCgADfhwQgJgCgEgCQgGgEgCgFQgFgKACgQIAjl6QABgLADgIQADgIAHgGQAHgFANgDIASgCQAJgBALABQAJAAAJAEQAJAEAEAGQAGAHADAPIAoC6IARBOIAZBtQADAOgDAKQgDAIgIAFQgKAEgGAAQgKABgIgDQgIgDgGgGQgDgDgDgHIgIgcIgFgMQgHgKgMgFQgNgEgKACQgMACgKAGQgJAFgFAJQgFAJgBAHIgDARQgCALgCAEQgCAIgHAEQgGAEgHACIgIABIgGgBgAElmzQgHACgEAGQgEAIgBAHQgCAJAAAJIgDA1QgBASABAPQACATAKANQALANATgIQANgFADgNQAEgNgBgRIgOhSQgCgMgDgGQgDgIgFgFQgEgEgFAAIgEABgAIRiEQgIgDgFgHQgEgGgDgLIgCgVIgPkAIgCgbQgCgOgEgJQgFgKgHgGIghgQQgEgDgEgGQgHgOADgNQADgPAIgGQAKgHAQAAQAQAAAMgBIAYgDIAfgBIAbgBQAOAAAHADQALAHADANQAFAOgGANQgEAIgGAEIgaAQQgGAEgEAHQgEAKAAAIIgBAVIACAXIACAWQAAArAEAvIAKCdQABAMgDAHQgDAIgHAFQgIAFgJABIgEAAQgGAAgHgCgAKqiQQgKgDgEgHQgGgJgBgOIgXl+QAAgKACgJQAEgIAGgEQAHgFAOgCQAKgCATgBIAngCIAogCQATgBAIAJQAFAFADAIQADAJgBAHQAAAJgDAGQgDAHgHAFQgHAEgKABIgTACQghAEgNANQgNAOADAkQADAVAHAMQAHANASAFQALACAHgBIASABQAKABAGADQAHACAEAIQAGAKgCANQgBAPgHAGQgEAEgHACIgNAEIgOABQgHAAgHADQgTAHgGAPQgHAQACAaQABAUAHASQAGAPAQAGQAKAEAMAAIAWgBIAUAAQALABAGAGQAFAFACAHQADAHAAAJQAAAIgDAHQgDAHgGAEQgGAFgJABIhXAGIgaABQgMAAgKgDg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AglEdQgSgCgSgJQgQgIgNgNQgKgKgIgOQgSgdgHgrQgFghgCgkIgJiHQgCgoAAgeQABgqAOgiQAPgkAegXQAegZAsgGIAcgCQAsAAAjAWQAuAeAPA7IAAACQAEAUABAPQADAggPAXQgKARgNAHQAKAFAHAGQAWAUAEAfIADAiIAJB3QABAYgBATQgCAWgMARQgMASgUAIIgBABQgPAGgRAAIgGAAQgKgBgOgDIgNgDIgDABQgTANgRADQgOAEgOAAgAAFg5IAIgCIgCgDIgBgBIgGgFg");
	this.shape_1.setTransform(-82.5,-27.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhREWQgQgFgOgKQgQgLgJgTQgIgRgBgbIgIiLQgCgVAAgaIgHhmQgCgQABgPIgCgXIgCglQgCgiAXgYIABgBQAPgPAUgFIAXgEIAugFIAfgBIASAAQAbACAYAHQAfAKATAUQAQAQAKAaQAIAVAEAZQAEAXgCAaQgBAagHAVIgBADIgKAUIgFALIAEAHIANASQAJAOAEASQAHAdABApQAAAfADAcIACAWQACAbgMATQgKASgVALQgQAJgSAAIgHABQgMAAgOgEQgXgGgOgRIgIgKQgIATgPAMIgCABQgRALgSACIgOABQgKAAgMgCg");
	this.shape_2.setTransform(-58.3,-28.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgPERQgWgGgPgTQgPgTgDgeQgBgTAAgNIgFgvQgCgQAAgTIgOjsIAAgCQgEggAEgZQADgYARgSQARgRAagFQAIgCALAAQALAAAJACQAXAGAPAPIABABQAPARAGAZQAEAQAAATQACAPAAASIATFIQABAcgKAUQgJAUgWAMQgQAIgQACIgNABQgMAAgNgEg");
	this.shape_3.setTransform(-40.7,-30.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgmEdQgSgCgSgJQgQgJgMgMQgKgKgIgOQgSgegHgqQgFghgDgkIgIiHQgCggAAgmQAAgqAPgjQAOgiAegYQAggaArgFQAMgCAPAAQAuAAAhAXQAvAdAOA8IABABQADAOACAVQADAggPAXQgJAQgPAIQALAFAHAHQAWATAEAfIALCYQACAYgCAUQgBAWgMASQgMAQgUAJIgBAAQgPAHgRAAIgGgBQgOgBgKgCIgNgEIgDADQgRAKgUAFQgOAEgNAAgAAFg4QAEgDAEgBIgDgCIgBAAIgFgHg");
	this.shape_4.setTransform(-23.3,-30.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag6EUQghgGgSgeQgLgTgBgaIgVlFQgBgPAAgSIgBgZQAAgSAFgOQAGgWARgPQAQgPAcgEIANAAIATABQAYAFARASIABABQAMAPAFAXIAEAcIACAvQAEAqADA1IAHB/QAAAMACAIIAAAAIAVAAQAPACANADQAZAIAPAWQASAagEAiQgEAlgaATQgXASglABIglABIgzACQgMABgMgCg");
	this.shape_5.setTransform(-1.5,-32.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgPERQgWgHgPgSQgPgTgDgeQgCgQABgQIgFgvIgCgjIgMjVQAAgNgCgKIAAgCQgEggAEgZQADgYARgSQAQgRAagFQAJgCAKAAQAMAAAJACQAXAGAOAPIACACQAPAQAFAZQAFATAAAQIACA5IAJCLIAKClQABAbgKAVQgKAVgVALQgPAIgSADIgMAAQgOAAgLgEg");
	this.shape_6.setTransform(12.4,-33.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhhEYQgRgDgPgIQgTgMgIgUQgLgWADgeIALhsIAHhQIARi7QACgRAFgQQAJgWARgNQAQgOAagEIACAAIAVgDIAcAAQAPAAAQAHQAWAJANASQANASAEAXIApC6IARBOIAZBsQAFAbgGAWIAAABIgBABQgJAbgZAOQgTAJgSABIgGABQgOAAgRgGQgUgHgPgPQgKgLgGgRIgCgLIAAACQgDANgEAKQgHAXgUANIgCABQgMAIgSAFIgTABg");
	this.shape_7.setTransform(31.4,-34.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgDETQgagIgPgXQgKgOgEgUQgCgLgBgRIgPkAQAAgLgBgLIgCgHIgagNQgPgJgKgRIgBgBQgPgdAGggQAHgjAZgRQAVgQAgAAIABAAIAWgBIAZgDQAOgBAPAAIAkgBQAXAAAQAIIACABIACABQAbAPAKAhQAKAggOAfQgJAVgRALIgUAMIAAAKIACAUIACAcQAAAqAEArIAKCeQACAWgHASQgIAXgWAOQgTAMgTABIgKABQgPAAgLgEg");
	this.shape_8.setTransform(51.9,-36);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AglEaQgSAAgRgFQgdgJgOgYQgMgSgBgbIgYl/QAAgUAFgQQAIgYAVgOQARgMAYgDQALgCAYgBIAmgCIAugDQAjAAAXAWIABABQAOAPAGASQAFAQgBAQQAAASgIASQgJATgSAMIgBACQgSALgXABIgQACIgBAAIgMACIABAJIABAJIAGAAIATABQAPABANAFQAZAJANAZQAMAXgCAbQgDAigVATQgNAMgQAFQgJAEgMABIgQACIgBAOIADAQIAuAAQAbACATARIABABIABABQAOANAGASQAFAPAAASQgBATgGAPQgIASgRAOQgQAMgVADIhZAGQgOACgOAAg");
	this.shape_9.setTransform(74.1,-37.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhhEXQgSgCgOgIQgSgLgKgUQgKgWADgeIAjl4QACgVAFgMQAIgVARgOQARgNAagFIACgBIAUgBIAQgBIANAAQAOABAQAGQAXAJANATQAMAPAFAZIApC6IARBPIASBNIAHAfQAFAbgGAVIAAABIgBABQgKAbgYAOQgRAJgVACIgGAAQgPAAgPgGQgVgGgOgQQgLgLgFgRIgCgKIgBABIgGAXQgIAXgUANIgBACQgOAIgRAEQgIABgKAAg");
	this.shape_10.setTransform(-142.6,37.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag6EUQghgGgSgeQgLgSgBgbIgXl/QAAgQAEgQQAGgWARgPQASgPAbgEIANAAIASABQAaAFAPASIABACQANAOAFAXQADASAAALIADAtIAAABQAEApADA2IAFBcIABAjQAAAJACALIAAAAIAVAAQAQACANADQAZAIAPAXQASAagEAhQgEAlgaATQgYATgkAAIgmABIgyACQgNABgLgCg");
	this.shape_11.setTransform(-121.1,36.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ag6EUQgggGgTgeQgLgRgBgcIgVlGQgBgOAAgSIgBgZQAAgRAFgPQAGgWARgPQASgQAagDIANgBIATACQAYAEAQATIACACQAMAOAFAXQACAMABAQIACAaQAAALABAIIAAACQAEArADA0IAICTIABAAIAVAAQAQABAMAEQAZAHAPAXQASAagEAiQgEAkgaAUQgYASgkAAIhYAFQgOAAgKgCg");
	this.shape_12.setTransform(-102,34.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgGBnQgagCgTgVQgMgNgHgTQgGgTABgUQABgSAFgRQAFgMAIgMIAEgGIADgHQAHgRAOgLQANgLARgBIADAAQATAAAPALQATANAHAYQAGASADARIAAACIACAaQACARgEATQgFAZgSAQQgSATgeAAIgJgBg");
	this.shape_13.setTransform(-90.1,21.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AhhEXQgSgCgOgIQgTgMgIgTQgLgXADgdIALhsQAFgrACglIARi8QACgSAGgPQAHgVASgOQARgOAZgEIACgBIAVgBIAPgBIANAAQAPACAQAFQAXAJAMATQANARAEAXIApC6QAMAxAFAeIAZBsQAFAbgGAVIAAABIgBABQgJAbgZAOQgRAJgUABIgGAAQgQAAgPgEQgVgIgOgPQgLgMgFgQIgCgKIAAABQgDANgEALQgHAWgUAOIgCABQgPAIgPADQgIACgLAAg");
	this.shape_14.setTransform(-71.5,33.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhREVQgPgEgPgKQgRgNgIgRQgIgSgBgaIgIiLQgCgVAAgaIgHhnQgCgOABgQIgCgYIgCgkQgCgjAXgXIABgCQAPgOAUgGIAXgDIBfgGQAbACAYAGQAfAKATAVQAQAQAKAaQAIAUAEAZQAEAXgCAaQgBAbgHAVIgBADIgKAUIgFALIAFAHIAMASQAJANAEATQAHAcABApQAAAgADAbIACAXQACAZgMAVQgLASgUALQgSAIgQABIgGAAQgPAAgMgDQgWgGgPgSIgIgJQgIASgPAMIgCABQgQAMgTACIgOABQgLAAgLgDg");
	this.shape_15.setTransform(-47.7,31.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgPERQgXgHgOgSQgPgSgDgfQgBgTAAgNIgBgVIgEgaQgCgQAAgTIgOjsIAAgCQgEggAEgZQADgYARgRQAQgSAbgGIATgBQAJgBALADQAXAGAPAPIABACQAPAQAGAZQAEARAAASQACAQAAARIATFIQABAcgKAVQgJATgWAMQgPAIgRACIgNACQgMgBgNgEg");
	this.shape_16.setTransform(-30.1,30.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AhhEXQgRgCgPgJQgSgKgJgUQgLgXAEgdIAil4QACgSAGgPQAHgVASgOQARgOAagEIABAAIAVgDIAPgBIANABQAPABAQAGQAXAJAMASQAMAQAGAaIA6EHQAHAlAKAqIAHAeQAFAZgGAXIAAABIgBACQgJAagZAOQgRAJgUABIgGAAQgQAAgPgEQgUgHgPgQQgKgMgGgQIgCgKIAAABIgGAYQgJAWgTAOIgCAAQgNAKgRACQgIACgLABg");
	this.shape_17.setTransform(-11.1,29.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AhhEYQgSgDgOgIQgTgMgIgTQgLgXADgdIALhsIAHhRIARi7QACgSAGgPQAHgUASgPQAQgNAbgFIABgBIAVgBIAPgBIANAAQAPACAQAFQAXAJAMATQANAQAFAYIA6EJQAHAjAKAqIAHAfQAGAagHAWIAAABIgBABQgJAbgZAOQgRAJgUACIgGAAQgQAAgPgGQgUgGgPgQQgKgLgGgRIgCgKIAAABQgDAOgEAJQgHAXgUANIgCABQgNAKgRADQgIABgLAAg");
	this.shape_18.setTransform(26.1,27.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("Ag1EYQgSAAgOgGQgagJgOgYQgKgPgDgYIgDhAIAAgUQgDgbgDg4IgOjbQgCgfAPgXQAQgYAYgGQAIgDAQgDIA3gEIATgBQAUABAQACQAiADAYANQAaAOARAZQAQAYAHAcQAGAVAEAhQADAegDAdQgDAegIAWQgKAegVAWQgXAWghAIQgPAFgKABIgNACIAAADQAAAUACAVIAEA9QACAYgJATQgKAXgXAMQgRAJgUACg");
	this.shape_19.setTransform(49.6,25.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AglEaQgVgBgOgEQgdgJgOgYQgMgTgBgaIgYl/QgBgUAGgQQAIgYAVgOQARgMAYgDQALgCAYgBIAmgCIAugDQAjAAAXAWIABABQAOAOAGATQAFAQgBAQQAAASgIASQgJATgSAMIgBACQgSALgXABIgQACIgBAAIgMACIABAJIABAJIAGAAIATABQAPABANAFQAZAJANAZQAMAXgCAbQgDAhgVAUQgMAMgRAFQgNAEgIABIgQACIAAANIACARIAuAAQAbACATARIACACQAOANAGASQAFARAAAQQAAARgHARQgIATgRAMQgQANgUADIgZADIhBADQgOACgOAAg");
	this.shape_20.setTransform(72.6,23.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AhREVQgQgFgNgIQgQgMgKgTQgIgUAAgYIgJiKQgCgeAAgSQAAgZgCgaIgFg0QgBgOAAgQIgEg8QgBgiAXgYIABgBQAOgPAUgFQALgDANgBQAWgDAYgCIAfgCIASABQAbABAXAIQAfAJATAVQAPAPALAbQAJAYAEAVQADAbgBAXQgCAZgHAWIgBADQgDAKgGAKIgGALIAFAHQAIALAEAHQAKAOADASQAIAhAAAkIADA8IACAWQACAbgMATQgLATgUAKQgPAJgTAAIgGAAQgNAAgOgEQgWgFgPgSQgFgFgCgEQgJASgPANIgBABQgQALgUACIgNACQgMgBgLgDg");
	this.shape_21.setTransform(95.6,22.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgDETQgagIgPgXQgJgMgFgWQgDgQAAgMIgNjjQgBgOAAgPIgCgWIgCgHIgagNQgPgJgKgRIgBgCQgPgcAGggQAHgjAZgRQAVgQAhAAIABAAIAVgBIAZgDIAdgBIAkgBQAXAAARAIIABABIACABQAcAPAJAhQAKAggOAfQgIAUgSAMIgUAMIAAAKIACAUIACAcQABAzADAiIALCeQABAXgHARQgJAXgVAOQgTAMgTABIgKABQgPAAgLgEg");
	this.shape_22.setTransform(117.3,21);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AhhEXQgQgCgQgJQgSgLgJgTQgLgXAEgeIAil3QACgTAGgPQAIgVARgNQARgOAagFIABAAIAVgCIAcAAQARABAOAGQAWAIANATQAMAQAGAZIAoC6IASBOIARBOIAHAfQAFAagGAVIAAACIAAABQgKAcgZAMQgSAKgTABIgGAAQgOAAgQgFQgVgGgPgQQgLgNgFgQIgCgKIAAACQgCALgEAMQgJAXgTANIgCABQgMAIgSAEIgTACg");
	this.shape_23.setTransform(142.6,19.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.grigliatetx, new cjs.Rectangle(-159.1,-65.5,318.4,131.1), null);


(lib.fiore = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.498)").s().p("AiRIwQg9g8AAhWQAAgcAGgXQAGgXAOgaQgrBJhSAVQhSAVhJgrQhKgqgWhTQgWhUArhJQA1hdBogLQgsgEgmgXQhKgqgWhUQgWhTArhJQArhLBSgWQBTgWBKAqQAsAbAcAsQgOgZgFgYQgGgWAAgcQAAhVA9g8QA8g+BVAAQBVAAA9A+QA8A8AABVQAAAbgFAVQgFAXgNAZQAcgqArgaQBKgqBSAWQBTAWArBLQAqBJgWBTQgWBUhKAqQgWANgTAGQgVAGgaACQAaABAVAIQATAGAXANQBKArAWBSQAWBTgrBLQgrBKhSAWQhTAWhKgrQgXgNgQgPQgSgRgPgYQANAaAGAXQAFAVAAAbQAABWg8A8Qg9A+hVgBQhVABg8g+gAiRiRQg9A8AABVQAABWA9A8QA8A9BVAAQBVAAA9g9QA8g8AAhWQAAhVg8g8Qg9g9hVAAQhVAAg8A9g");
	this.shape.setTransform(-3.1,-3.1,0.545,0.545,0,0,0,-5.8,-5.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.fiore, new cjs.Rectangle(-30.8,-33.9,61.6,67.8), null);


(lib.data = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgRAtQgDgEgBgEIgBgOQAAgNABgEQACgFAFgDQgFgEgCgFIgBgOQAAgIACgEQABgEADgEQAGgIAKAAQALAAAGAIQAEAEABAEIABAMIgBAOQgBAFgGAEQAGADABAFQABAEAAANIgBAOQgBAEgCAEQgGAJgNAAQgLAAgGgJgAgEAFQgCACAAADIAAAVQAAADACADQACACACAAQADAAACgCQADgDAAgDIAAgVQAAgDgDgCQgCgCgDAAQgCAAgCACgAgEgkQgCACAAADIAAAQQAAADACACQACACACAAQADAAACgCQADgCAAgDIAAgQQAAgDgDgCQgCgCgDAAQgCAAgCACg");
	this.shape.setTransform(64.5,7.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAAA2IAAhaIgOALIAAgQIAOgMIAPAAIAABrg");
	this.shape_1.setTransform(58.5,7.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgPAwQgHgGAAgLIAAg9QAAgLAHgGQAHgGAIAAQAKAAAGAGQAHAGAAALIAAA9QAAALgHAGQgGAGgKAAQgIAAgHgGgAgEgkQgCACAAAEIAAA9QAAAEACACQACACACAAQADAAADgCQACgCAAgEIAAg9QAAgEgCgCQgDgCgDAAQgCAAgCACg");
	this.shape_2.setTransform(53.4,7.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgWA2IAAgPIAbgzQADgFAAgJIgBgIQgCgEgFAAQgGAAAAAIIAAAJIgQAAIAAgJQAAgJAHgHQAHgHAIAAQAMAAAGAIQAFAHAAAMIgBALIgEALIgWAqIAbAAIAAAQg");
	this.shape_3.setTransform(47.8,7.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgQAwQgIgIAAgMIAAg3QAAgNAIgHQAHgGAJAAQAKAAAHAGQAIAHAAANIAAA3QAAAMgIAIQgHAGgKAAQgJAAgHgGgAgGgjQgEACAAAGIAAA3QAAAFAEADQADADADAAQAFAAACgDQAEgDAAgFIAAg3QAAgGgEgCQgCgDgFAAQgDAAgDADg");
	this.shape_4.setTransform(39.2,7.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgHA2IAAhrIAPAAIAABrg");
	this.shape_5.setTransform(34.4,7.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgRAwQgHgIgBgMIAAg3QABgNAHgHQAIgGAJAAQAKAAAIAGQAIAHAAANIAAAFIgQAAIAAgFQABgGgEgCQgDgDgEAAQgEAAgDADQgCACAAAGIAAA3QAAAFACADQADADAEAAQAEAAADgDQAEgDgBgFIAAgUIgLAAIAAgNIAbAAIAAAhQAAAMgIAIQgIAGgKAAQgJAAgIgGg");
	this.shape_6.setTransform(29.8,7.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgQAwQgIgIAAgMIAAg3QAAgNAIgHQAHgGAJAAQAKAAAHAGQAIAHAAANIAAAFIgOAAIAAgFQAAgGgEgCQgCgDgFAAQgDAAgDADQgEACAAAGIAAA3QAAAFAEADQADADADAAQAFAAACgDQAEgDAAgFIAAgUIgMAAIAAgNIAaAAIAAAhQAAAMgIAIQgHAGgKAAQgJAAgHgGg");
	this.shape_7.setTransform(23.4,7.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AAPA2IgFgYIgTAAIgFAYIgPAAIAXhrIANAAIAXBrgAAIAQIgIglIgHAlIAPAAg");
	this.shape_8.setTransform(17.2,7.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AATA2IAAhAIAAAAIgPAtIgGAAIgQgtIAAAAIAABAIgQAAIAAhrIAQAAIASA4IAAAAIAUg4IAPAAIAABrg");
	this.shape_9.setTransform(10,7.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgWA2IAAgPIAbgzQADgFAAgJIgBgIQgCgEgFAAQgGAAAAAIIAAAJIgQAAIAAgJQAAgJAHgHQAHgHAIAAQAMAAAGAIQAFAHAAAMIgBALIgEALIgWAqIAbAAIAAAQg");
	this.shape_10.setTransform(0.3,7.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgCBCIAAhqIAPAAIAABqgAAFgsIgTgVIAPAAIAOAVg");
	this.shape_11.setTransform(-7.3,6.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgYA2IAAhrIAXAAQAMABAHAHQAHAHAAANIAAAyQAAAcgbABgAgIAnIAHAAQALAAAAgNIAAgzQAAgNgLAAIgHAAg");
	this.shape_12.setTransform(-11.5,7.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgWA2IAAhrIAtAAIAAAPIgdAAIAAAfIAZAAIAAAOIgZAAIAAAfIAdAAIAAAQg");
	this.shape_13.setTransform(-17.2,7.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgWA2IAAhrIAQAAIAABbIAdAAIAAAQg");
	this.shape_14.setTransform(-22.7,7.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgRAwQgHgIAAgMIAAg3QAAgNAHgHQAIgGAJAAQAKAAAHAGQAJAHgBANIAAA3QABAMgJAIQgHAGgKAAQgJAAgIgGgAgGgjQgEACAAAGIAAA3QAAAFAEADQADADADAAQAEAAADgDQAEgDAAgFIAAg3QAAgGgEgCQgDgDgEAAQgDAAgDADg");
	this.shape_15.setTransform(-28.9,7.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgQAxQgIgHAAgNIAAg6QAAgKAHgHQAHgHAKAAQALAAAHAHQAHAHAAALIAAAGIgQAAIAAgFQAAgFgCgDQgDgDgEAAQgJAAAAAMIAAA2QAAALAJAAQAJAAAAgLIAAgFIAQAAIAAAGQAAAKgHAIQgIAHgKAAQgJAAgHgFg");
	this.shape_16.setTransform(-35.1,7.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AALA2IgNguIgJAAIAAAuIgPAAIAAhrIAZAAQAaABAAAfQAAAUgOAGIARAxgAgLgFIAIAAQAHABADgFQACgDAAgJQAAgJgCgEQgDgEgHAAIgIAAg");
	this.shape_17.setTransform(-41.1,7.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AgWA2IAAhrIAtAAIAAAPIgeAAIAAAfIAaAAIAAAOIgaAAIAAAfIAeAAIAAAQg");
	this.shape_18.setTransform(-47.1,7.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AAUA2IAAhAIgBAAIgPAtIgHAAIgOgtIgBAAIAABAIgPAAIAAhrIAPAAIASA4IABAAIATg4IAPAAIAABrg");
	this.shape_19.setTransform(-54.2,7.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AAPA2IgFgYIgUAAIgEAYIgPAAIAXhrIANAAIAXBrgAAHAQIgHglIgHAlIAOAAg");
	this.shape_20.setTransform(-64.2,7.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgWA1IAAhqIAtAAIAAAPIgeAAIAAAfIAaAAIAAAOIgaAAIAAAfIAeAAIAAAPg");
	this.shape_21.setTransform(50,-9.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgWA1IAAhqIAQAAIAABbIAdAAIAAAPg");
	this.shape_22.setTransform(44.5,-9.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgHA1IAAhqIAPAAIAABqg");
	this.shape_23.setTransform(39.9,-9.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AALA1IgNgtIgJAAIAAAtIgPAAIAAhqIAZAAQAaABAAAfQAAAUgOAGIARAwgAgLgEIAJAAQAGAAADgFQACgEAAgIQAAgJgCgEQgDgEgHAAIgIAAg");
	this.shape_24.setTransform(35.5,-9.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgYA1IAAhqIAXAAQAMAAAHAIQAHAHAAASQAAAPgEAFQgHAMgPAAIgIAAIAAApgAgJgBIAIAAQAHAAADgGQACgDAAgJQAAgKgCgEQgCgFgIAAIgIAAg");
	this.shape_25.setTransform(29.2,-9.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AAPA1IgFgWIgTAAIgFAWIgPAAIAXhqIANAAIAXBqgAAIAQIgIglIgHAlIAPAAg");
	this.shape_26.setTransform(22.9,-9.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AAEA1IAAgQIgeAAIAAgOIAWhMIAPAAIgVBMIAOAAIAAgdIAPAAIAAAdIAIAAIAAAOIgIAAIAAAQg");
	this.shape_27.setTransform(14.4,-9.3);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgWA2IAAgPIAbgzQADgFAAgJIgBgIQgCgEgFAAQgGAAAAAIIAAAJIgQAAIAAgJQAAgJAHgHQAHgHAIAAQAMAAAGAIQAFAHAAAMIgBALIgEALIgWAqIAbAAIAAAQg");
	this.shape_28.setTransform(8.8,-9.3);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgCBCIAAhqIAPAAIAABqgAAFgsIgTgVIAPAAIAOAVg");
	this.shape_29.setTransform(1.2,-10.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgYA1IAAhqIAXAAQAMAAAHAIQAHAHAAANIAAAyQAAAcgbAAgAgIAnIAHAAQALAAAAgOIAAgyQAAgNgLAAIgHAAg");
	this.shape_30.setTransform(-3,-9.3);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgWA1IAAhqIAtAAIAAAPIgeAAIAAAfIAaAAIAAAOIgaAAIAAAfIAeAAIAAAPg");
	this.shape_31.setTransform(-8.7,-9.3);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgGA1IAAhbIgSAAIAAgPIAxAAIAAAPIgRAAIAABbg");
	this.shape_32.setTransform(-14.2,-9.3);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AAMA1IgOgtIgJAAIAAAtIgQAAIAAhqIAZAAQAaABAAAfQAAAUgNAGIAQAwgAgLgEIAJAAQAGAAADgFQACgEAAgIQAAgJgDgEQgCgEgHAAIgIAAg");
	this.shape_33.setTransform(-19.5,-9.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AAPA1IgFgWIgTAAIgFAWIgPAAIAXhqIANAAIAXBqgAAIAQIgIglIgHAlIAPAAg");
	this.shape_34.setTransform(-26,-9.3);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AATA1IAAg/IAAAAIgPAsIgGAAIgQgsIAAAAIAAA/IgQAAIAAhqIAQAAIASA5IAAAAIAUg5IAPAAIAABqg");
	this.shape_35.setTransform(-33.2,-9.3);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AAPA1IgEgWIgVAAIgEAWIgPAAIAYhqIALAAIAYBqgAAHAQIgHglIgGAlIANAAg");
	this.shape_36.setTransform(-43.2,-9.3);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgYA1IAAhqIAXAAQAMAAAHAIQAHAHAAANIAAAyQAAAcgbAAgAgIAnIAHAAQALAAAAgOIAAgyQAAgNgLAAIgHAAg");
	this.shape_37.setTransform(-49.4,-9.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.data, new cjs.Rectangle(-69.3,-16.6,138.7,36), null);


(lib.corpofarfallagiallo_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.instance = new lib.corpofarfallagiallo();
	this.instance.parent = this;
	this.instance.setTransform(-39,-80);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.corpofarfallagiallo_1, new cjs.Rectangle(-39,-80,77,117), null);


(lib.corpofarfallablu_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.instance = new lib.corpofarfallablu();
	this.instance.parent = this;
	this.instance.setTransform(-7,-35);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.corpofarfallablu_1, new cjs.Rectangle(-7,-35,38,49), null);


(lib.alagiallasx_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.instance = new lib.alagiallasx();
	this.instance.parent = this;
	this.instance.setTransform(-146,-84);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.alagiallasx_1, new cjs.Rectangle(-146,-84,165,145), null);


(lib.alagialladx_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.instance = new lib.alagialladx();
	this.instance.parent = this;
	this.instance.setTransform(-17,-169);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.alagialladx_1, new cjs.Rectangle(-17,-169,115,204), null);


(lib.alablusx_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.instance = new lib.alablusx();
	this.instance.parent = this;
	this.instance.setTransform(-79,-99);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.alablusx_1, new cjs.Rectangle(-79,-99,83,154), null);


(lib.alabludx_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_1
	this.instance = new lib.alabludx();
	this.instance.parent = this;
	this.instance.setTransform(-14,-33);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.alabludx_1, new cjs.Rectangle(-14,-33,122,100), null);


(lib.pieghe = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Livello_2
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0.82)","rgba(255,255,255,0)"],[0,0.992],-62.2,0,62.4,0).s().p("ApwRGMAAAgiLIThAAMAAAAiLg");
	this.shape.setTransform(-25.2,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Livello_1
	this.instance = new lib.piegha();
	this.instance.parent = this;
	this.instance.setTransform(67.2,39.8,0.305,2.047,0,0,0,-0.1,0);

	this.instance_1 = new lib.piegha();
	this.instance_1.parent = this;
	this.instance_1.setTransform(6.4,39.8,0.305,2.047,0,0,0,-0.1,0);

	this.instance_2 = new lib.piegha();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-54.4,39.8,0.305,2.047,0,0,0,-0.1,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.pieghe, new cjs.Rectangle(-89.6,-109.4,192.1,289.6), null);


(lib.nastro = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{luce:1});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_44 = function() {
		this.stop();
		this.parent.gotoAndPlay("esci");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(44).call(this.frame_44).wait(1));

	// Livello_4 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A0kgPQCihhEjhzQE6h8FghiQNxj2J4AoQhpC/g1DlQhFEoAqEgQiQgekxAFQk0AFlfAnQl7Aqk6BHQlhBPjLBmg");
	mask.setTransform(13.7,-11.8);

	// luce
	this.instance = new lib.luce();
	this.instance.parent = this;
	this.instance.setTransform(0,181.4,1,1,-75.5,0,0,-0.1,0);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:0,rotation:69.4,y:181.5},44).wait(1));

	// Livello_8
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E11021").s().p("EghbAVkMAAAgrHMBC3AAAMAAAArHg");
	this.shape.setTransform(33,4.1);

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(45));

	// Livello_6
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#7A3B2D").s().p("AjPCcIFdl7IBBG/g");
	this.shape_1.setTransform(-88.2,38.7);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(45));

	// Livello_7
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#AD1C25").s().p("Ai2AtIjOiiIBUgLQFRgvEwhkIA0F/QkxBvlOAuIhcALg");
	this.shape_2.setTransform(-106.4,50.3);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(45));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-145.3,-77.9,290.7,155.9);


(lib.gialla = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// alagialla-sx
	this.instance = new lib.alagiallasx_1();
	this.instance.parent = this;
	this.instance.setTransform(-2.7,1.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:-0.8,regY:-0.2,scaleX:0.18,scaleY:1.06,rotation:-33.9,x:-11.8,y:-7.6},2,cjs.Ease.get(-1)).to({regX:0,regY:0,scaleX:1,scaleY:1,rotation:0,x:-2.7,y:1.5},2).wait(1));

	// alagialla-dx
	this.instance_1 = new lib.alagialladx_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(1.8,-5.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regX:0.4,regY:-0.1,scaleX:0.17,scaleY:0.65,rotation:-33.2,x:1.7,y:-5.6},2,cjs.Ease.get(-1)).to({regX:0,regY:0,scaleX:1,scaleY:1,rotation:0,x:1.8,y:-5.5},2).wait(1));

	// corpofarfalla-giallo
	this.instance_2 = new lib.corpofarfallagiallo_1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(0.5,-0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(5));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-148.7,-174.5,248.5,237);


(lib.cta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{lamp:1});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_1 = function() {
		var tl = this;
		tl.stop();
		var delay = 500;
		var startTime = createjs.Ticker.getTime();
		createjs.Ticker.addEventListener('tick', f);
		function f(e) {
			if (createjs.Ticker.getTime() - startTime > delay) {
				tl.play();
				createjs.Ticker.removeEventListener('tick', f);
			}
		}
	}
	this.frame_53 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(52).call(this.frame_53).wait(1));

	// Livello 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag1BlQgQgUAAgmIAAhWQAAgmAQgUQAQgSAlgBQAlABAQASQAQAUABAmIAABWQgBAmgQAUQgQATglABQglgBgQgTgAgQhNQgDAHAAAPIAABuQAAAOADAJQAFAIALAAQAMAAAEgJQAEgHAAgPIAAhuQAAgPgEgHQgEgJgMABQgLgBgFAJg");
	this.shape.setTransform(122.6,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAeB1IgziAIAACAIgpAAIAAjpIAiAAIAzB4IAAh4IAoAAIAADpg");
	this.shape_1.setTransform(106.2,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgXB1IAAjpIAvAAIAADpg");
	this.shape_2.setTransform(94,0);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgWB1IAAjGIgmAAIAAgjIB5AAIAAAjIglAAIAADGg");
	this.shape_3.setTransform(83.5,0);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAeB1IgziAIAACAIgpAAIAAjpIAiAAIAzB4IAAh4IAoAAIAADpg");
	this.shape_4.setTransform(69.1,0);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAcB1IgJgzIgkAAIgJAzIgtAAIAujpIA0AAIAtDpgAAOAkIgNhdIgOBdIAbAAg");
	this.shape_5.setTransform(53.3,0);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgyB1IAAjpIAwAAIAADJIA1AAIAAAgg");
	this.shape_6.setTransform(39.9,0);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag0BlQgQgUgBgmIAAhWQABgmAQgUQAQgSAkgBQAlABARASQAQAUAAAmIAABWQAAAmgQAUQgRATglABQgkgBgQgTgAgQhNQgDAHAAAPIAABuQAAAOADAJQAEAIAMAAQAMAAAFgJQADgHAAgPIAAhuQAAgPgDgHQgFgJgMABQgLgBgFAJg");
	this.shape_7.setTransform(24.6,0);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgYB1IgsjpIApAAIAbChIAaihIArAAIgsDpg");
	this.shape_8.setTransform(8.7,0);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgzB1IAAjpIAxAAIAADJIA2AAIAAAgg");
	this.shape_9.setTransform(-11.7,0);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgXB1IAAjpIAvAAIAADpg");
	this.shape_10.setTransform(-22.8,0);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAcB1IgJgzIgkAAIgJAzIgtAAIAtjpIA0AAIAuDpgAAPAkIgPhdIgMBdIAbAAg");
	this.shape_11.setTransform(-42,0);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgXB1IAAjpIAvAAIAADpg");
	this.shape_12.setTransform(-54,0);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgzB1IAAjpIAxAAIAADJIA2AAIAAAgg");
	this.shape_13.setTransform(-63.8,0);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("Ag1BkQgOgVAAgnIAAhPQAAgoAPgUQAPgVAlAAQAlAAAPASQAQASAAAhIAAANIgvAAIAAgQQAAgQgEgIQgDgHgNAAQgMAAgEAIQgDAJgBARIAABmQABARAEAJQAEAJAMAAQANAAAFgJQAFgKAAgRIAAgZIgXAAIAAgcIBDAAIAAB4IggAAIgDgVQgLAYgbABQgigBgPgUg");
	this.shape_14.setTransform(-79,0);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("Ag0BlQgQgUgBgmIAAhWQABgmAQgUQAPgSAlgBQAlABARASQAPAUAAAmIAABWQAAAmgPAUQgRATglABQglgBgPgTgAgPhNQgEAHgBAPIAABuQABAOAEAJQADAIAMAAQAMAAAFgJQADgHAAgPIAAhuQAAgPgDgHQgFgJgMABQgLgBgEAJg");
	this.shape_15.setTransform(-95.6,0);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgxB1IAAjpIBjAAIAAAhIgzAAIAAA/IArAAIAAAgIgrAAIAABpg");
	this.shape_16.setTransform(-109.6,0);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgtBnQgQgSgBgmIAogHQABAWAGALQAFALALAAQAIAAAEgGQADgFABgIQAAgPgHgJQgGgKgMgLIgZgVQgOgNgIgNQgHgNAAgUQAAgdARgPQARgPAdgBQAgABAMARQAMATACAcIgpAGQgBgSgEgJQgDgJgKAAQgIAAgEAGQgEAGgBAIQAAAMAGAIQAFAIAJAJIAYAVQASAPAJAQQAJAQAAAWQAAARgHANQgIANgNAIQgOAIgSAAQgfgBgRgRg");
	this.shape_17.setTransform(-123.3,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(54));

	// Livello_5 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A0vFBQhGAAgygxQgvgwgChDIAAk0QAAhGAxgyQAygxBGAAMApfAAAQBGAAAxAxQAyAyAABGIAAE0QgBBDgxAwQgwAxhHAAg");

	// Livello_7
	this.instance = new lib.fiore();
	this.instance.parent = this;
	this.instance.setTransform(-205.7,-14.2,0.74,0.74);
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).to({rotation:-720,x:175},52).wait(1));

	// Livello_6
	this.instance_1 = new lib.fiore();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-177.4,28.3,0.74,0.74);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({_off:false},0).to({rotation:720,x:203.3},52).wait(1));

	// Livello_3
	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#D91422").s().p("A7fInIAAxNMA2/AAAIAARNg");

	var maskedShapeInstanceList = [this.shape_18];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_18).wait(54));

	// Livello 1
	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("rgba(0,0,0,0.4)").s().p("A0vFBQhGAAgygxQgvgwgChDIAAk0QAAhGAxgyQAygxBGAAMApfAAAQBGAAAxAxQAyAyAABGIAAE0QgBBDgxAwQgwAxhHAAg");
	this.shape_19.setTransform(0,4);

	this.timeline.addTween(cjs.Tween.get(this.shape_19).wait(54));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-149.7,-32.1,299.4,68.3);


(lib.blu = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// alablu-sx
	this.instance = new lib.alablusx_1();
	this.instance.parent = this;
	this.instance.setTransform(-6.7,3.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:-0.2,regY:0.1,scaleX:0.15,rotation:17.2,x:-4.3},3,cjs.Ease.get(-1)).to({regX:0,regY:0,scaleX:1,rotation:0,x:-6.7},3,cjs.Ease.get(-1)).wait(1));

	// alablu-dx
	this.instance_1 = new lib.alabludx_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(2.7,10,1,1,0,0,0,0.6,0.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:0.6,scaleY:1.03,skewX:14.7,skewY:-58.5,x:3.4,y:2.9},3,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,skewX:0,skewY:0,x:2.7,y:10},3,cjs.Ease.get(-1)).wait(1));

	// corpofarfalla-blu
	this.instance_2 = new lib.corpofarfallablu_1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-0.2,-0.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(7));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-85.7,-95.8,195.8,172.5);


(lib.tovagliaanim = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var tl = this;
		tl.stop();
		var delay = 500;
		var startTime = createjs.Ticker.getTime();
		createjs.Ticker.addEventListener('tick', f);
		function f(e) {
			if (createjs.Ticker.getTime() - startTime > delay) {
				tl.play();
				createjs.Ticker.removeEventListener('tick', f);
			}
		}
	}
	this.frame_26 = function() {
		this.stop();
		this.parent.gotoAndPlay("ini");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(26).call(this.frame_26).wait(1));

	// Livello_3
	this.instance = new lib.pieghe();
	this.instance.parent = this;
	this.instance.setTransform(84,128.1,0.937,1.17);
	this.instance.alpha = 0.602;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:-0.3,regY:0.1,scaleX:0.66,x:-76.1,y:123.2,alpha:1},26,cjs.Ease.get(-1)).wait(1));

	// Livello_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.694,0,0,0.545,-15.6,-30.5)).s().p("ArwTiMAAAgnDIXgAAMAAAAnDg");
	this.shape.setTransform(75.3,125);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.694,0,0,0.546,-15.6,-30.5)).s().p("ArvTiMAAAgnDIXfAAMAABAnDg");
	this.shape_1.setTransform(75.1,125);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.693,-0.001,0,0.546,-15.5,-30.4)).s().p("ArvTiMAAAgnDIXeAAMAABAnDg");
	this.shape_2.setTransform(74.4,125);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.692,-0.003,0,0.546,-15.4,-30.4)).s().p("AruTiMAAAgnDIXcAAQgBTjADTgg");
	this.shape_3.setTransform(73.4,125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.691,-0.005,-0.001,0.546,-15.1,-30.3)).s().p("AruTiMAAAgnDIXaAAQAATlADTeg");
	this.shape_4.setTransform(72,125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.689,-0.007,-0.001,0.547,-14.9,-30.2)).s().p("ArtTiMAAAgnDIXWAAQgBTnAGTcg");
	this.shape_5.setTransform(70.1,125);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.687,-0.01,-0.002,0.547,-14.5,-30.2)).s().p("ArsTiMAAAgnDIXTAAQgCTqAITZg");
	this.shape_6.setTransform(67.8,125);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.684,-0.014,-0.003,0.548,-14.1,-30)).s().p("ArrTiMAAAgnDIXPAAQgETtAMTWg");
	this.shape_7.setTransform(65.2,125);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.681,-0.018,-0.003,0.549,-13.6,-29.9)).s().p("ArqTiMAAAgnDIXKAAQgFTxAQTSg");
	this.shape_8.setTransform(62.1,125);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.678,-0.023,-0.004,0.55,-13.1,-29.7)).s().p("AroTiMAAAgnDIXDAAQgFT1ATTOg");
	this.shape_9.setTransform(58.6,125);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.674,-0.028,-0.005,0.551,-12.5,-29.5)).s().p("ArnTiMAAAgnDIW8AAQgFT5AXTKg");
	this.shape_10.setTransform(54.7,125);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.67,-0.034,-0.006,0.552,-11.9,-29.3)).s().p("ArkTiMAAAgnEIW0AAQgIT/AdTGg");
	this.shape_11.setTransform(50.3,125.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.666,-0.041,-0.008,0.553,-11.2,-29)).s().p("AriTiMAAAgnEIWsAAQgJUFAiTAg");
	this.shape_12.setTransform(45.6,125.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.661,-0.048,-0.009,0.555,-10.4,-28.8)).s().p("ArgThMAAAgnDIWjAAQgLULApS6g");
	this.shape_13.setTransform(40.5,125.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.655,-0.055,-0.01,0.556,-9.6,-28.5)).s().p("ArdThMAAAgnDIWZAAQgMUSAuSzg");
	this.shape_14.setTransform(34.9,125.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.649,-0.063,-0.012,0.558,-8.7,-28.2)).s().p("ArbThMAAAgnDIWPAAQgOUZA2Ssg");
	this.shape_15.setTransform(28.9,125.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.643,-0.072,-0.014,0.559,-7.8,-27.9)).s().p("ArYThMAAAgnDIWDAAQgPUgA9Slg");
	this.shape_16.setTransform(22.5,125.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.637,-0.081,-0.015,0.561,-6.8,-27.6)).s().p("ArVThMAAAgnDIV3AAQgRUpBFScg");
	this.shape_17.setTransform(15.7,125.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.63,-0.091,-0.017,0.563,-5.6,-27.3)).s().p("ArRThMAAAgnDIVqAAQgTUxBMSUg");
	this.shape_18.setTransform(8.5,125.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.622,-0.102,-0.019,0.565,-4.5,-26.9)).s().p("ArOThMAAAgnDIVdAAQgWU6BWSLg");
	this.shape_19.setTransform(0.9,125.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.615,-0.113,-0.021,0.567,-3.3,-26.5)).s().p("ArKThMAAAgnEIVPAAQgYVFBfSBg");
	this.shape_20.setTransform(-7.1,125.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.606,-0.124,-0.023,0.569,-2.1,-26.1)).s().p("ArHTgMAAAgnDIVAAAQgaVOBpR5g");
	this.shape_21.setTransform(-15.6,125.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.598,-0.136,-0.026,0.572,-0.7,-25.7)).s().p("ArDTgMAAAgnDIUxAAQgdVZBzRug");
	this.shape_22.setTransform(-24.5,125.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.589,-0.149,-0.028,0.574,0.6,-25.2)).s().p("Aq/TgMAAAgnDIUhAAQggVjB+Rkg");
	this.shape_23.setTransform(-33.7,125.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.58,-0.162,-0.031,0.577,2.1,-24.8)).s().p("Aq6TgMAAAgnDIUPAAQgjVvCJRYg");
	this.shape_24.setTransform(-43.4,125.2);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.57,-0.176,-0.033,0.579,3.6,-24.3)).s().p("Aq2TgMAAAgnDIT+AAQgmV7CVRMg");
	this.shape_25.setTransform(-53.5,125.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.bf(img.tovaglia, null, new cjs.Matrix2D(0.56,-0.19,-0.036,0.582,5.2,-23.7)).s().p("AqxTgMAAAgnEITrAAQgpWJChQ/g");
	this.shape_26.setTransform(-64,125.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,180.1,338.8);


(lib.speciale = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{esci:25});

	// timeline functions:
	this.frame_0 = function() {
		this.visible = false;
	}
	this.frame_1 = function() {
		this.visible = true;
	}
	this.frame_23 = function() {
		var tl = this;
		tl.stop();
		var delay = 1000;
		var startTime = createjs.Ticker.getTime();
		createjs.Ticker.addEventListener('tick', f);
		function f(e) {
			if (createjs.Ticker.getTime() - startTime > delay) {
				tl.play();
				createjs.Ticker.removeEventListener('tick', f);
			}
		}
	}
	this.frame_24 = function() {
		this.stop();
		this.nastro.gotoAndPlay("luce");
	}
	this.frame_44 = function() {
		this.stop();
		this.parent.gotoAndPlay("fine");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(22).call(this.frame_23).wait(1).call(this.frame_24).wait(20).call(this.frame_44).wait(1));

	// grigliate-tx
	this.instance = new lib.grigliatetx();
	this.instance.parent = this;
	this.instance.setTransform(7.6,55.6,1.188,1.188);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},1).wait(13).to({_off:false,scaleX:2.5,scaleY:2.5,rotation:-13,y:55.4},0).to({scaleX:1.11,scaleY:1.11,rotation:5.2,y:55.6},6,cjs.Ease.get(-1)).to({scaleX:1.19,scaleY:1.19,rotation:0},3,cjs.Ease.get(1)).wait(2).to({regX:0.1,regY:0.1,scaleX:1.28,scaleY:1.28,rotation:5.1,x:7.7,y:55.7},3).to({regX:0,regY:0,scaleX:0.22,scaleY:0.22,rotation:-12.8,x:7.6,y:55.4},6).to({_off:true},1).wait(10));

	// Livello_6 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_1 = new cjs.Graphics().p("AhsQMMAAAggXIDZAAMAAAAgXg");
	var mask_graphics_2 = new cjs.Graphics().p("AmEvIILCh+MABHAgPIrDB+g");
	var mask_graphics_3 = new cjs.Graphics().p("AqbuEISqj+MACNAgHIyqD+g");
	var mask_graphics_4 = new cjs.Graphics().p("AuytAIaSl9IDTf+I6TF9g");
	var mask_graphics_5 = new cjs.Graphics().p("AzJr9MAh6gH7IEZf1Mgh6AH8g");
	var mask_graphics_6 = new cjs.Graphics().p("A3gq5MApigJ6IFfftMgpiAJ6g");
	var mask_graphics_7 = new cjs.Graphics().p("A73p1MAxKgL6IGlflMgxKAL6g");
	var mask_graphics_8 = new cjs.Graphics().p("EggPgIxMA4zgN4IHsfcMg4zAN3g");
	var mask_graphics_38 = new cjs.Graphics().p("EggPgIxMA4zgN4IHsfcMg4zAN3g");
	var mask_graphics_39 = new cjs.Graphics().p("A7yp2MAv5gLvIHsfcMgv5ALvg");
	var mask_graphics_40 = new cjs.Graphics().p("A3Uq6MAm+gJnIHsfcMgm/AJog");
	var mask_graphics_41 = new cjs.Graphics().p("Ay4r+IeFnfIHsfcI+FHgg");
	var mask_graphics_42 = new cjs.Graphics().p("AubtCIVLlXIHsfcI1LFXg");
	var mask_graphics_43 = new cjs.Graphics().p("Ap+uGIMRjPIHsfcIsRDPg");
	var mask_graphics_44 = new cjs.Graphics().p("AlhvKIDYhHIHrfcIjYBHg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(1).to({graphics:mask_graphics_1,x:-220.9,y:-23.3}).wait(1).to({graphics:mask_graphics_2,x:-195.7,y:-23.3}).wait(1).to({graphics:mask_graphics_3,x:-170.6,y:-23.3}).wait(1).to({graphics:mask_graphics_4,x:-145.4,y:-23.3}).wait(1).to({graphics:mask_graphics_5,x:-120.2,y:-23.3}).wait(1).to({graphics:mask_graphics_6,x:-95.1,y:-23.3}).wait(1).to({graphics:mask_graphics_7,x:-69.9,y:-23.3}).wait(1).to({graphics:mask_graphics_8,x:-44.7,y:-23.3}).wait(30).to({graphics:mask_graphics_38,x:-44.7,y:-23.3}).wait(1).to({graphics:mask_graphics_39,x:-16.2,y:-30.1}).wait(1).to({graphics:mask_graphics_40,x:12.3,y:-36.9}).wait(1).to({graphics:mask_graphics_41,x:40.8,y:-43.7}).wait(1).to({graphics:mask_graphics_42,x:69.2,y:-50.6}).wait(1).to({graphics:mask_graphics_43,x:97.7,y:-57.4}).wait(1).to({graphics:mask_graphics_44,x:126.2,y:-64.2}).wait(1));

	// speciale-tx
	this.instance_1 = new lib.specialetx();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-48.1,-75.4);

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({_off:true},1).wait(7).to({_off:false,rotation:-18,x:-258.7,y:-1.2,alpha:0},0).to({rotation:0,x:-48.1,y:-75.4,alpha:1},6,cjs.Ease.get(-1)).wait(20).to({regX:-0.1,rotation:19,x:174.9,y:-78.4},6).to({_off:true},1).wait(4));

	// nastro
	this.nastro = new lib.nastro();
	this.nastro.name = "nastro";
	this.nastro.parent = this;
	this.nastro.setTransform(-51.4,-55.4);

	var maskedShapeInstanceList = [this.nastro];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.nastro).wait(45));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-441.5,-189.4,638.3,408.8);


// stage content:
(lib._300x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{sipario:0,ini:1,fine:34});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_33 = function() {
		this.stop();
	}
	this.frame_49 = function() {
		this.cta.gotoAndPlay("lamp");
		
		var tl = this;
		tl.stop();
		var delay = 4500;
		var startTime = createjs.Ticker.getTime();
		createjs.Ticker.addEventListener('tick', f);
		function f(e) {
			if (createjs.Ticker.getTime() - startTime > delay) {
				tl.play();
				createjs.Ticker.removeEventListener('tick', f);
			}
		}
	}
	this.frame_50 = function() {
		if (!this.alreadyExecuted) {
			this.alreadyExecuted = true;
			this.loopNum = 1;
		} else {
			this.loopNum++;
			if (this.loopNum == 2) {
				this.stop();
			}
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(33).call(this.frame_33).wait(16).call(this.frame_49).wait(1).call(this.frame_50).wait(1));

	// cornice
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#725559").ss(2,1,0,3).p("A3bzhMAu3AAAMAAAAnDMgu3AAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(51));

	// tovaglia
	this.tovagliasx = new lib.tovagliaanim();
	this.tovagliasx.name = "tovagliasx";
	this.tovagliasx.parent = this;
	this.tovagliasx.setTransform(300,0,1.1,1,0,0,180);

	this.tovagliadx = new lib.tovagliaanim();
	this.tovagliadx.name = "tovagliadx";
	this.tovagliadx.parent = this;
	this.tovagliadx.setTransform(0,0,1.156,1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.tovagliadx},{t:this.tovagliasx}]}).to({state:[]},1).wait(50));

	// cta
	this.cta = new lib.cta();
	this.cta.name = "cta";
	this.cta.parent = this;
	this.cta.setTransform(77.6,276.4,0.46,0.46,0,0,0,0.2,5.4);
	this.cta._off = true;

	this.timeline.addTween(cjs.Tween.get(this.cta).wait(41).to({_off:false},0).to({y:167.4},8,cjs.Ease.get(-1)).wait(2));

	// logo-specialissimi
	this.instance = new lib.logospecialissimi();
	this.instance.parent = this;
	this.instance.setTransform(80.6,-66.9,0.56,0.56,0,0,0,1.1,0.8);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(34).to({_off:false},0).to({y:63.1},7,cjs.Ease.get(1)).wait(10));

	// data
	this.instance_1 = new lib.data();
	this.instance_1.parent = this;
	this.instance_1.setTransform(77.6,123.9,0.19,0.19,0,0,0,0.2,0.2);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(34).to({_off:false},0).to({regX:0,regY:0,scaleX:1,scaleY:1,x:77.5,alpha:1},7,cjs.Ease.get(-1)).wait(10));

	// volantino
	this.instance_2 = new lib.volantino_1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(375.4,93.5,0.688,0.688,0,0,0,0.2,0);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(34).to({_off:false},0).to({x:219.2},7,cjs.Ease.get(-1)).wait(10));

	// tx
	this.instance_3 = new lib.speciale();
	this.instance_3.parent = this;
	this.instance_3.setTransform(154.6,97.5,0.593,0.593,0,0,0,0,0.1);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(33).to({_off:false},0).to({_off:true},1).wait(17));

	// gialla
	this.instance_4 = new lib.gialla();
	this.instance_4.parent = this;
	this.instance_4.setTransform(380.1,267.4,0.4,0.4,-8.5,0,0,0.2,0.1);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(2).to({_off:false},0).to({regX:0.1,rotation:11.3,x:238.8,y:86.2},7,cjs.Ease.get(-1)).to({regX:0.3,regY:0.2,rotation:8.3,x:224,y:138.1},8,cjs.Ease.get(-1)).to({regX:0.4,rotation:5.3,x:43,y:45.6},8,cjs.Ease.get(-1)).to({regX:0,regY:0,rotation:0,x:-31.9,y:-33.5},8,cjs.Ease.get(-1)).to({_off:true},1).wait(17));

	// blu
	this.instance_5 = new lib.blu();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-40,277.5,0.391,0.391);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(2).to({_off:false},0).to({x:33.6,y:169.5},3,cjs.Ease.get(-1)).to({x:134,y:137.5},9,cjs.Ease.get(-1)).to({x:194.9,y:145.5},6,cjs.Ease.get(-1)).to({x:242,y:48.5},7,cjs.Ease.get(-1)).to({x:344.4,y:111.6},6,cjs.Ease.get(-1)).to({_off:true},1).wait(17));

	// logo
	this.instance_6 = new lib.logo();
	this.instance_6.parent = this;
	this.instance_6.setTransform(150.1,283.8,0.96,0.96,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({x:150.9,y:180.7},4,cjs.Ease.get(-1)).to({y:202.5},2,cjs.Ease.get(1)).wait(45));

	// bg
	this.instance_7 = new lib.bg();
	this.instance_7.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(51));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149,124,302,339.8);
// library properties:
lib.properties = {
	id: '37B5A1A697A54202A6EEAA3083230580',
	width: 300,
	height: 250,
	fps: 24,
	color: "#CCCCCC",
	opacity: 1.00,
	manifest: [
		{src:"alabludx.png", id:"alabludx"},
		{src:"alablusx.png", id:"alablusx"},
		{src:"alagialladx.png", id:"alagialladx"},
		{src:"alagiallasx.png", id:"alagiallasx"},
		{src:"bg.jpg", id:"bg"},
		{src:"corpofarfallablu.png", id:"corpofarfallablu"},
		{src:"corpofarfallagiallo.png", id:"corpofarfallagiallo"},
		{src:"tovaglia.jpg", id:"tovaglia"},
		{src:"volantino.png", id:"volantino"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['37B5A1A697A54202A6EEAA3083230580'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;